// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_invitation.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const findInvitationByID = `-- name: FindInvitationByID :one
SELECT id, company_id, email, role, name, status, token, expires_at, created_at
FROM invitations
WHERE id = $1
LIMIT 1
`

// ID 一致の招待を返す（会社スコープの認可判定に使う。status は問わない）。
func (q *Queries) FindInvitationByID(ctx context.Context, id int64) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, findInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Role,
		&i.Name,
		&i.Status,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findPendingInvitationByEmail = `-- name: FindPendingInvitationByEmail :one
SELECT id, company_id, email, role, name, status, token, expires_at, created_at
FROM invitations
WHERE lower(btrim(email, E'\t\n\x0B\f\r ')) = $1
  AND status = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type FindPendingInvitationByEmailParams struct {
	EmailNormal string
	Status      string
}

// pending の招待を email で引く（受諾フロー判定用）。突き合わせは domain.NormalizeEmail と同じ
// 正規形どうしで行う。引数は Go 側で畳み、列は users の一意索引と同じ SQL 式
// lower(btrim(email, EmailTrimCutset)) で畳む。expires は問わない（pending なら期限切れでも返す）。
// 1 件しか返さないため、順序が揺れると「どの招待が受理されるか」が変わる。created_at DESC, id DESC で固定。
func (q *Queries) FindPendingInvitationByEmail(ctx context.Context, arg FindPendingInvitationByEmailParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, findPendingInvitationByEmail, arg.EmailNormal, arg.Status)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Role,
		&i.Name,
		&i.Status,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findPendingInvitationByToken = `-- name: FindPendingInvitationByToken :one
SELECT id, company_id, email, role, name, status, token, expires_at, created_at
FROM invitations
WHERE token = $1
  AND status = $2
  AND expires_at > $3
ORDER BY id ASC
LIMIT 1
`

type FindPendingInvitationByTokenParams struct {
	Token  sql.NullString
	Status string
	Now    time.Time
}

// token 一致 かつ pending かつ 未期限切れの招待のみ返す。期限比較は DB 関数でなく
// Go の UTC 現在時刻をバインドする（DB エンジン非依存 / ローカル TZ 設定に左右されない）。
// token は UNIQUE なので 1 行だが、順序を固定するため id ASC を置く。
func (q *Queries) FindPendingInvitationByToken(ctx context.Context, arg FindPendingInvitationByTokenParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, findPendingInvitationByToken, arg.Token, arg.Status, arg.Now)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.Role,
		&i.Name,
		&i.Status,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertInvitation = `-- name: InsertInvitation :one
INSERT INTO invitations
  (company_id, email, role, name, status, token, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, created_at
`

type InsertInvitationParams struct {
	CompanyID int64
	Email     string
	Role      string
	Name      string
	Status    string
	Token     sql.NullString
	ExpiresAt time.Time
	CreatedAt time.Time
}

type InsertInvitationRow struct {
	ID        int64
	CreatedAt time.Time
}

// 招待行を保存する。email は呼び出し側が正規形へ畳んで渡す。id は採番列なので省き
// RETURNING で id / created_at を書き戻す。created_at は DB 既定値が無いため呼び出し側が渡す
// （GORM autoCreateTime 相当。ゼロなら now を入れる）。updated_at 列は持たない。
// token は未設定を NULL にして UNIQUE を避けるため nullable。
func (q *Queries) InsertInvitation(ctx context.Context, arg InsertInvitationParams) (InsertInvitationRow, error) {
	row := q.db.QueryRowContext(ctx, insertInvitation,
		arg.CompanyID,
		arg.Email,
		arg.Role,
		arg.Name,
		arg.Status,
		arg.Token,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i InsertInvitationRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT id, company_id, email, role, name, status, token, expires_at, created_at
FROM invitations
WHERE status = $1
ORDER BY created_at DESC, id DESC
`

// 全社横断で pending の招待を返す（SuperAdmin 用）。物理削除はせず status のみ更新するため
// accepted / canceled は WHERE で除外する。created_at は一意でないため id DESC をタイブレークに置く。
func (q *Queries) ListPendingInvitations(ctx context.Context, status string) ([]Invitation, error) {
	rows, err := q.db.QueryContext(ctx, listPendingInvitations, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.Role,
			&i.Name,
			&i.Status,
			&i.Token,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsByCompany = `-- name: ListPendingInvitationsByCompany :many
SELECT id, company_id, email, role, name, status, token, expires_at, created_at
FROM invitations
WHERE company_id = $1 AND status = $2
ORDER BY created_at DESC, id DESC
`

type ListPendingInvitationsByCompanyParams struct {
	CompanyID int64
	Status    string
}

// 自社の pending 招待のみ返す（CompanyAdmin 用）。
func (q *Queries) ListPendingInvitationsByCompany(ctx context.Context, arg ListPendingInvitationsByCompanyParams) ([]Invitation, error) {
	rows, err := q.db.QueryContext(ctx, listPendingInvitationsByCompany, arg.CompanyID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.Role,
			&i.Name,
			&i.Status,
			&i.Token,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :exec
UPDATE invitations SET
  status = $1
WHERE id = $2
`

type UpdateInvitationStatusParams struct {
	Status string
	ID     int64
}

// 招待の status のみ更新する（accepted / canceled への遷移。物理削除はしない）。
// 対象は id 一致の 1 行だけで、他の列は触らない。
func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInvitationStatus, arg.Status, arg.ID)
	return err
}
