// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_chat_session.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const deleteAiChatSession = `-- name: DeleteAiChatSession :execrows
DELETE FROM ai_chat_sessions WHERE id = $1
`

// セッションを物理削除する（ai_chat_sessions は soft delete 列を持たない）。
// UpdateAiChatSessionTitle と同じ理由で :execrows（0 行削除を成功と区別するため）。
func (q *Queries) DeleteAiChatSession(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAiChatSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAiChatSessionByID = `-- name: GetAiChatSessionByID :one
SELECT id, user_id, title, session_type, scenario_id, created_at, updated_at
FROM ai_chat_sessions
WHERE id = $1
`

// 内部 ID で 1 件取得（存在しなければ sql.ErrNoRows）。所有者検証は usecase 側。
func (q *Queries) GetAiChatSessionByID(ctx context.Context, id int64) (AiChatSession, error) {
	row := q.db.QueryRowContext(ctx, getAiChatSessionByID, id)
	var i AiChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SessionType,
		&i.ScenarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAiChatSession = `-- name: InsertAiChatSession :one
INSERT INTO ai_chat_sessions (user_id, title, session_type, scenario_id, created_at, updated_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, created_at, updated_at
`

type InsertAiChatSessionParams struct {
	UserID      int64
	Title       string
	SessionType string
	ScenarioID  sql.NullInt64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type InsertAiChatSessionRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

// セッションを 1 件作成する。id は採番列なので省き RETURNING で id / 時刻を書き戻す。
// created_at / updated_at は DB 既定値が無いため呼び出し側が値を渡す（GORM の autoTime 相当。
// ゼロなら呼び出し側が now() を入れる）。scenario_id は NULL 可（練習シナリオ紐付けが無いセッション）。
func (q *Queries) InsertAiChatSession(ctx context.Context, arg InsertAiChatSessionParams) (InsertAiChatSessionRow, error) {
	row := q.db.QueryRowContext(ctx, insertAiChatSession,
		arg.UserID,
		arg.Title,
		arg.SessionType,
		arg.ScenarioID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InsertAiChatSessionRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listAiChatSessionsByUserID = `-- name: ListAiChatSessionsByUserID :many
SELECT id, user_id, title, session_type, scenario_id, created_at, updated_at
FROM ai_chat_sessions
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

// 自分の AI チャットセッションを新しい順で返す。
// created_at は一意でない。同時刻セッションの順序を固定するため id をタイブレークに置く。
func (q *Queries) ListAiChatSessionsByUserID(ctx context.Context, userID int64) ([]AiChatSession, error) {
	rows, err := q.db.QueryContext(ctx, listAiChatSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiChatSession{}
	for rows.Next() {
		var i AiChatSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.SessionType,
			&i.ScenarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAiChatSessionTitle = `-- name: UpdateAiChatSessionTitle :execrows
UPDATE ai_chat_sessions SET
  title      = $1,
  updated_at = now()
WHERE id = $2
`

type UpdateAiChatSessionTitleParams struct {
	Title string
	ID    int64
}

// セッションのタイトルを更新する。書くのは title と updated_at の 2 列だけで、
// user_id / session_type / scenario_id / created_at は不変。
// updated_at は DB 既定値が無いため now() を明示する（autoUpdateTime 相当）。
//
// :exec ではなく :execrows にしている理由:
//
//	:exec は「SQL がエラーなく流れたか」しか返さない。UPDATE は 1 行も一致しなくても
//	成功なので、存在しない id を渡しても呼び出し側には成功として見える。
//	:execrows は実際に書き換わった行数（RowsAffected）を返すので、repository が 0 行を
//	「対象なし」として domain.ErrNotFound に翻訳できる。
func (q *Queries) UpdateAiChatSessionTitle(ctx context.Context, arg UpdateAiChatSessionTitleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAiChatSessionTitle, arg.Title, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
