// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_stats.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countMembersByWorkspace = `-- name: CountMembersByWorkspace :many
SELECT
  workspace_id,
  COUNT(*) AS total,
  COUNT(*) FILTER (WHERE is_active) AS active,
  COUNT(*) FILTER (WHERE role_id = $1) AS trainees
FROM users
WHERE workspace_id IS NOT NULL AND deleted_at IS NULL
GROUP BY workspace_id
`

type CountMembersByWorkspaceRow struct {
	WorkspaceID uuid.NullUUID
	Total       int64
	Active      int64
	Trainees    int64
}

// ワークスペースごとの在籍メンバー数（総数 / 有効 / trainee）を 1 クエリで集計する（運営の横断ビュー用）。
// 論理削除済み（deleted_at IS NOT NULL）とワークスペース未所属（workspace_id IS NULL）は除外する。
// trainee 判定は正規化後の正である role_id で行う（パラメータで渡す）。
func (q *Queries) CountMembersByWorkspace(ctx context.Context, traineeRoleID int32) ([]CountMembersByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, countMembersByWorkspace, traineeRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMembersByWorkspaceRow{}
	for rows.Next() {
		var i CountMembersByWorkspaceRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Total,
			&i.Active,
			&i.Trainees,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
