// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_application.sql

package sqlcgen

import (
	"context"
)

const listCompanyApplications = `-- name: ListCompanyApplications :many
SELECT id, company_name, applicant_name, email, message, status, created_at, updated_at FROM company_applications
ORDER BY created_at DESC
`

// 利用申請一覧（新しい順）。super_admin が確認する。
func (q *Queries) ListCompanyApplications(ctx context.Context) ([]CompanyApplication, error) {
	rows, err := q.db.QueryContext(ctx, listCompanyApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompanyApplication{}
	for rows.Next() {
		var i CompanyApplication
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.ApplicantName,
			&i.Email,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
