// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company.sql

package sqlcgen

import (
	"context"
)

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, is_active, created_at, updated_at, workspace_id FROM companies
WHERE id = $1
`

// ID で企業を 1 件取得。
func (q *Queries) GetCompanyByID(ctx context.Context, id int64) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, is_active, created_at, updated_at, workspace_id FROM companies
ORDER BY name ASC, id ASC
`

// 企業一覧（名前昇順）。name に一意制約は無いので同名企業の順序を固定する id ASC を付ける。
func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mirrorCompanySettingsToWorkspace = `-- name: MirrorCompanySettingsToWorkspace :exec
UPDATE workspaces w
SET is_active = c.is_active,
    updated_at = now()
FROM companies c
WHERE c.id = $1 AND c.workspace_id = w.id
`

// 会社のテナント設定を、対応する workspaces 行へ写す。
// is_active は最終的に workspaces の列になる。今は companies が正本で、workspaces 側は
// その写し。設定を書く経路が増えても写し忘れないよう、companies から写すこの 1 か所に
// 集約する。まだワークスペースに紐付いていない会社（workspace_id IS NULL）は 0 件更新で、
// 写す先が無い。
func (q *Queries) MirrorCompanySettingsToWorkspace(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, mirrorCompanySettingsToWorkspace, id)
	return err
}

const updateCompanyActive = `-- name: UpdateCompanyActive :execrows
UPDATE companies SET is_active = $2, updated_at = now() WHERE id = $1
`

type UpdateCompanyActiveParams struct {
	ID       int64
	IsActive bool
}

// 会社アカウントの有効/無効を更新する。0 件なら対象が存在しない（呼び出し側が not-found にする）。
// 判定は companies 側の件数で行う。写し先（workspaces）の件数を見ると、まだ紐付いていない
// 会社が not-found に化ける。
func (q *Queries) UpdateCompanyActive(ctx context.Context, arg UpdateCompanyActiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCompanyActive, arg.ID, arg.IsActive)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
