// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_chapter.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const countChaptersByCourseForCompany = `-- name: CountChaptersByCourseForCompany :many
SELECT course_id, COUNT(*) AS cnt
FROM course_chapters
WHERE company_id = $1
  AND ($2::bool OR is_published = TRUE)
GROUP BY course_id
`

type CountChaptersByCourseForCompanyParams struct {
	CompanyID          int64
	IncludeUnpublished bool
}

type CountChaptersByCourseForCompanyRow struct {
	CourseID int64
	Cnt      int64
}

// course_id ごとの教材件数を 1 クエリで集計する。
// include_unpublished=false（trainee 相当）は published のみ数える。
func (q *Queries) CountChaptersByCourseForCompany(ctx context.Context, arg CountChaptersByCourseForCompanyParams) ([]CountChaptersByCourseForCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, countChaptersByCourseForCompany, arg.CompanyID, arg.IncludeUnpublished)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountChaptersByCourseForCompanyRow{}
	for rows.Next() {
		var i CountChaptersByCourseForCompanyRow
		if err := rows.Scan(&i.CourseID, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChapter = `-- name: DeleteChapter :exec
DELETE FROM course_chapters WHERE id = $1
`

// 教材を物理削除する（course_chapters は soft delete 列を持たない）。
func (q *Queries) DeleteChapter(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChapter, id)
	return err
}

const deleteChaptersByCourse = `-- name: DeleteChaptersByCourse :exec
DELETE FROM course_chapters WHERE course_id = $1
`

// コース削除時の cascade 用に配下教材を全削除する（FK に頼らず明示削除）。
func (q *Queries) DeleteChaptersByCourse(ctx context.Context, courseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteChaptersByCourse, courseID)
	return err
}

const getChapterByID = `-- name: GetChapterByID :one
SELECT id, company_id, course_id, created_by_user_id, title, doc, revision, schema_version, sort_order, is_published, created_at, updated_at
FROM course_chapters
WHERE id = $1
`

// 単一教材を返す（本文 doc を含む）。存在しなければ sql.ErrNoRows。
func (q *Queries) GetChapterByID(ctx context.Context, id int64) (CourseChapter, error) {
	row := q.db.QueryRowContext(ctx, getChapterByID, id)
	var i CourseChapter
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.CreatedByUserID,
		&i.Title,
		&i.Doc,
		&i.Revision,
		&i.SchemaVersion,
		&i.SortOrder,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChapter = `-- name: InsertChapter :one
INSERT INTO course_chapters
  (company_id, course_id, created_by_user_id, title, revision, schema_version, sort_order, is_published, created_at, updated_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  COALESCE(NULLIF($5::bigint, 0), 1),
  COALESCE(NULLIF($6::bigint, 0), 1),
  COALESCE(NULLIF($7::bigint, 0), 100),
  $8,
  $9,
  $10
)
RETURNING id, revision, schema_version, sort_order, created_at, updated_at
`

type InsertChapterParams struct {
	CompanyID       int64
	CourseID        int64
	CreatedByUserID int64
	Title           string
	Revision        int64
	SchemaVersion   int64
	SortOrder       int64
	IsPublished     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type InsertChapterRow struct {
	ID            int64
	Revision      int64
	SchemaVersion int64
	SortOrder     int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// 教材（章）を 1 件作成する。id は採番列なので省き RETURNING で書き戻す。doc は作成時 NULL。
// created_at / updated_at は DB 既定値が無いため呼び出し側が値を渡す（autoTime 相当）。
// revision / schema_version は 0 のとき既定 1、sort_order は 0 のとき既定 100 を当てる
// （GORM の `default:` タグと同じ挙動。RETURNING で確定値を書き戻す）。
func (q *Queries) InsertChapter(ctx context.Context, arg InsertChapterParams) (InsertChapterRow, error) {
	row := q.db.QueryRowContext(ctx, insertChapter,
		arg.CompanyID,
		arg.CourseID,
		arg.CreatedByUserID,
		arg.Title,
		arg.Revision,
		arg.SchemaVersion,
		arg.SortOrder,
		arg.IsPublished,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InsertChapterRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.SchemaVersion,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChaptersByCompany = `-- name: ListChaptersByCompany :many
SELECT id, company_id, course_id, created_by_user_id, title, doc, revision, schema_version, sort_order, is_published, created_at, updated_at
FROM course_chapters
WHERE company_id = $1
  AND ($2::bool OR is_published = TRUE)
ORDER BY updated_at DESC, id DESC
`

type ListChaptersByCompanyParams struct {
	CompanyID          int64
	IncludeUnpublished bool
}

// 会社内の全教材（章）を更新日降順で返す backward-compat 用。
// include_unpublished=false なら公開済み（is_published=true）のみに絞る。
func (q *Queries) ListChaptersByCompany(ctx context.Context, arg ListChaptersByCompanyParams) ([]CourseChapter, error) {
	rows, err := q.db.QueryContext(ctx, listChaptersByCompany, arg.CompanyID, arg.IncludeUnpublished)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseChapter{}
	for rows.Next() {
		var i CourseChapter
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CourseID,
			&i.CreatedByUserID,
			&i.Title,
			&i.Doc,
			&i.Revision,
			&i.SchemaVersion,
			&i.SortOrder,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaptersByCourse = `-- name: ListChaptersByCourse :many
SELECT id, company_id, course_id, created_by_user_id, title, sort_order, is_published, created_at, updated_at
FROM course_chapters
WHERE course_id = $1
  AND ($2::bool OR is_published = TRUE)
ORDER BY sort_order ASC, id ASC
`

type ListChaptersByCourseParams struct {
	CourseID           int64
	IncludeUnpublished bool
}

type ListChaptersByCourseRow struct {
	ID              int64
	CompanyID       int64
	CourseID        int64
	CreatedByUserID int64
	Title           string
	SortOrder       int64
	IsPublished     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// コース内の章を sort_order 昇順（同値時 id 昇順）で返す。
// 一覧は本文（doc・jsonb）を返さない（章ごとに重く、全章を先読みすると非効率）。
func (q *Queries) ListChaptersByCourse(ctx context.Context, arg ListChaptersByCourseParams) ([]ListChaptersByCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, listChaptersByCourse, arg.CourseID, arg.IncludeUnpublished)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChaptersByCourseRow{}
	for rows.Next() {
		var i ListChaptersByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CourseID,
			&i.CreatedByUserID,
			&i.Title,
			&i.SortOrder,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChapter = `-- name: UpdateChapter :one
UPDATE course_chapters SET
  title        = $1,
  sort_order   = $2,
  is_published = $3,
  updated_at   = now()
WHERE id = $4
RETURNING updated_at
`

type UpdateChapterParams struct {
	Title       string
	SortOrder   int64
	IsPublished bool
	ID          int64
}

// 教材のメタ情報を部分更新する。書くのは title / sort_order / is_published の 3 列だけで、
// created_by_user_id / company_id / course_id / doc / revision は不変（GORM の Updates(map) と同じ）。
// updated_at は now() へ進めて RETURNING で書き戻す（autoUpdateTime 相当）。
func (q *Queries) UpdateChapter(ctx context.Context, arg UpdateChapterParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, updateChapter,
		arg.Title,
		arg.SortOrder,
		arg.IsPublished,
		arg.ID,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const updateChapterDocWithRevision = `-- name: UpdateChapterDocWithRevision :one
UPDATE course_chapters SET
  doc        = $1,
  revision   = revision + 1,
  updated_at = now()
WHERE id = $2 AND revision = $3
RETURNING id, company_id, course_id, created_by_user_id, title, doc, revision, schema_version, sort_order, is_published, created_at, updated_at
`

type UpdateChapterDocWithRevisionParams struct {
	Doc              *json.RawMessage
	ID               int64
	ExpectedRevision int64
}

// リッチ本文（tiptap JSON）を楽観ロックで更新する。expected_revision が現在値と一致した行だけを
// 更新し、revision を +1・updated_at を now() へ進める。0 行なら sql.ErrNoRows（呼び出し側が
// 存在確認で 404 / 409 を切り分ける）。RETURNING で更新後の行全体を返す。
func (q *Queries) UpdateChapterDocWithRevision(ctx context.Context, arg UpdateChapterDocWithRevisionParams) (CourseChapter, error) {
	row := q.db.QueryRowContext(ctx, updateChapterDocWithRevision, arg.Doc, arg.ID, arg.ExpectedRevision)
	var i CourseChapter
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CourseID,
		&i.CreatedByUserID,
		&i.Title,
		&i.Doc,
		&i.Revision,
		&i.SchemaVersion,
		&i.SortOrder,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
