// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercise_submission.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const existsCorrectSubmission = `-- name: ExistsCorrectSubmission :one
SELECT EXISTS(
  SELECT 1 FROM exercise_submissions
  WHERE user_id = $1
    AND exercise_id = $2
    AND exercise_kind = $3
    AND is_correct = TRUE
) AS solved
`

type ExistsCorrectSubmissionParams struct {
	UserID       int64
	ExerciseID   int64
	ExerciseKind string
}

// user が (kind, exercise_id) を 1 回でも is_correct=true で解いたかを返す。
func (q *Queries) ExistsCorrectSubmission(ctx context.Context, arg ExistsCorrectSubmissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsCorrectSubmission, arg.UserID, arg.ExerciseID, arg.ExerciseKind)
	var solved bool
	err := row.Scan(&solved)
	return solved, err
}

const existsSubmission = `-- name: ExistsSubmission :one
SELECT EXISTS(
  SELECT 1 FROM exercise_submissions
  WHERE user_id = $1
    AND exercise_id = $2
    AND exercise_kind = $3
) AS attempted
`

type ExistsSubmissionParams struct {
	UserID       int64
	ExerciseID   int64
	ExerciseKind string
}

// user が (kind, exercise_id) に 1 回でも提出したかを返す。
func (q *Queries) ExistsSubmission(ctx context.Context, arg ExistsSubmissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsSubmission, arg.UserID, arg.ExerciseID, arg.ExerciseKind)
	var attempted bool
	err := row.Scan(&attempted)
	return attempted, err
}

const insertExerciseSubmission = `-- name: InsertExerciseSubmission :one
INSERT INTO exercise_submissions
  (user_id, exercise_kind, exercise_id, submitted_code, stdout, stderr, exit_code, is_correct, submitted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertExerciseSubmissionParams struct {
	UserID        int64
	ExerciseKind  string
	ExerciseID    int64
	SubmittedCode string
	Stdout        sql.NullString
	Stderr        sql.NullString
	ExitCode      int64
	IsCorrect     bool
	SubmittedAt   time.Time
}

// 提出履歴を 1 件追加する（append-only）。id は採番列なので省き RETURNING で書き戻す。
// submitted_at は DB 既定値が無く autoTime 対象でもないため呼び出し側（usecase）が必ず値を渡す。
// stdout / stderr は nullable 列だが、GORM 版は非ポインタ string を常に書いていたため
// 空文字も NULL ではなく ” として保存する（Valid=true で渡す）。
func (q *Queries) InsertExerciseSubmission(ctx context.Context, arg InsertExerciseSubmissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertExerciseSubmission,
		arg.UserID,
		arg.ExerciseKind,
		arg.ExerciseID,
		arg.SubmittedCode,
		arg.Stdout,
		arg.Stderr,
		arg.ExitCode,
		arg.IsCorrect,
		arg.SubmittedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listSubmissionsByUserAndExercise = `-- name: ListSubmissionsByUserAndExercise :many
SELECT id, user_id, exercise_kind, exercise_id, submitted_code, stdout, stderr, exit_code, is_correct, submitted_at
FROM exercise_submissions
WHERE user_id = $1
  AND exercise_id = $2
  AND exercise_kind = $3
ORDER BY submitted_at DESC, id DESC
`

type ListSubmissionsByUserAndExerciseParams struct {
	UserID       int64
	ExerciseID   int64
	ExerciseKind string
}

// user × (kind, exercise_id) の提出履歴を新しい順に返す。
// submitted_at は同着し得るため id 降順をタイブレークに置いて並びを固定する。
func (q *Queries) ListSubmissionsByUserAndExercise(ctx context.Context, arg ListSubmissionsByUserAndExerciseParams) ([]ExerciseSubmission, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissionsByUserAndExercise, arg.UserID, arg.ExerciseID, arg.ExerciseKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseSubmission{}
	for rows.Next() {
		var i ExerciseSubmission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseKind,
			&i.ExerciseID,
			&i.SubmittedCode,
			&i.Stdout,
			&i.Stderr,
			&i.ExitCode,
			&i.IsCorrect,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
