// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge_base_permission.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deletePageRestriction = `-- name: DeletePageRestriction :execrows
DELETE FROM page_restrictions
WHERE workspace_id = $1 AND page_id = $2 AND principal_id = $3 AND capability = $4
`

type DeletePageRestrictionParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	PrincipalID uuid.UUID
	Capability  string
}

// ページの例外の解除。最後の 1 行が消えるとその段には制限が無くなり、
// 解決は「より遠い祖先の制限」→「grant の既定」の順に戻る。
func (q *Queries) DeletePageRestriction(ctx context.Context, arg DeletePageRestrictionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePageRestriction,
		arg.WorkspaceID,
		arg.PageID,
		arg.PrincipalID,
		arg.Capability,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePrincipal = `-- name: DeletePrincipal :execrows
DELETE FROM principals
WHERE workspace_id = $1 AND id = $2
`

type DeletePrincipalParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// 主体の削除。grant / restriction / principal_members は FK の CASCADE で一緒に消える
// （権限だけが残って別人に引き継がれることが無いように、行を残さず消す）。
func (q *Queries) DeletePrincipal(ctx context.Context, arg DeletePrincipalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePrincipal, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePrincipalMember = `-- name: DeletePrincipalMember :execrows
DELETE FROM principal_members
WHERE workspace_id = $1 AND group_principal_id = $2 AND member_principal_id = $3
`

type DeletePrincipalMemberParams struct {
	WorkspaceID       uuid.UUID
	GroupPrincipalID  uuid.UUID
	MemberPrincipalID uuid.UUID
}

// グループからの所属削除。
func (q *Queries) DeletePrincipalMember(ctx context.Context, arg DeletePrincipalMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePrincipalMember, arg.WorkspaceID, arg.GroupPrincipalID, arg.MemberPrincipalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSpaceGrant = `-- name: DeleteSpaceGrant :execrows
DELETE FROM space_grants
WHERE workspace_id = $1 AND space_id = $2 AND principal_id = $3
`

type DeleteSpaceGrantParams struct {
	WorkspaceID uuid.UUID
	SpaceID     uuid.UUID
	PrincipalID uuid.UUID
}

// スペースでの既定の役割の剥奪。
func (q *Queries) DeleteSpaceGrant(ctx context.Context, arg DeleteSpaceGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSpaceGrant, arg.WorkspaceID, arg.SpaceID, arg.PrincipalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWorkspaceGrant = `-- name: DeleteWorkspaceGrant :execrows
DELETE FROM workspace_grants
WHERE workspace_id = $1 AND principal_id = $2
`

type DeleteWorkspaceGrantParams struct {
	WorkspaceID uuid.UUID
	PrincipalID uuid.UUID
}

// ワークスペース全体での既定の役割の剥奪。
func (q *Queries) DeleteWorkspaceGrant(ctx context.Context, arg DeleteWorkspaceGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkspaceGrant, arg.WorkspaceID, arg.PrincipalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPrincipal = `-- name: GetPrincipal :one
SELECT id, workspace_id, kind, user_id, space_id, page_id, name, created_at, updated_at FROM principals
WHERE workspace_id = $1 AND id = $2
`

type GetPrincipalParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// 主体を 1 件取得。workspace_id を含めることで別テナントの principal ID を弾く。
func (q *Queries) GetPrincipal(ctx context.Context, arg GetPrincipalParams) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipal, arg.WorkspaceID, arg.ID)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.UserID,
		&i.SpaceID,
		&i.PageID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShareLink = `-- name: GetShareLink :one
SELECT id, workspace_id, page_id, principal_id, principal_kind, capability, token_hash, password_hash, expires_at, revoked_at, created_by_user_id, created_at, updated_at FROM share_links
WHERE workspace_id = $1 AND id = $2
`

type GetShareLinkParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// 共有リンクを 1 件取得（失効操作の対象確認用）。
func (q *Queries) GetShareLink(ctx context.Context, arg GetShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRowContext(ctx, getShareLink, arg.WorkspaceID, arg.ID)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PageID,
		&i.PrincipalID,
		&i.PrincipalKind,
		&i.Capability,
		&i.TokenHash,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShareLinkByTokenHash = `-- name: GetShareLinkByTokenHash :one
SELECT id, workspace_id, page_id, principal_id, principal_kind, capability, token_hash, password_hash, expires_at, revoked_at, created_by_user_id, created_at, updated_at FROM share_links
WHERE token_hash = $1
`

// トークン（の SHA-256）から共有リンクを引く。期限・失効・パスワードの判定は呼び出し側で行う
// （「トークンが違う」と「期限切れ」を同じ経路で扱うと、どちらなのかを利用者に返せない）。
func (q *Queries) GetShareLinkByTokenHash(ctx context.Context, tokenHash []byte) (ShareLink, error) {
	row := q.db.QueryRowContext(ctx, getShareLinkByTokenHash, tokenHash)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PageID,
		&i.PrincipalID,
		&i.PrincipalKind,
		&i.Capability,
		&i.TokenHash,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpaceEveryonePrincipal = `-- name: GetSpaceEveryonePrincipal :one
SELECT id, workspace_id, kind, user_id, space_id, page_id, name, created_at, updated_at FROM principals
WHERE workspace_id = $1 AND kind = 'space_all' AND space_id = $2
`

type GetSpaceEveryonePrincipalParams struct {
	WorkspaceID uuid.UUID
	SpaceID     uuid.NullUUID
}

// そのスペースの「全員」を表す主体。
func (q *Queries) GetSpaceEveryonePrincipal(ctx context.Context, arg GetSpaceEveryonePrincipalParams) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getSpaceEveryonePrincipal, arg.WorkspaceID, arg.SpaceID)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.UserID,
		&i.SpaceID,
		&i.PageID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPrincipal = `-- name: GetUserPrincipal :one
SELECT id, workspace_id, kind, user_id, space_id, page_id, name, created_at, updated_at FROM principals
WHERE workspace_id = $1 AND kind = 'user' AND user_id = $2
`

type GetUserPrincipalParams struct {
	WorkspaceID uuid.UUID
	UserID      sql.NullInt64
}

// ユーザーの主体（＝ ワークスペース所属そのもの）。無ければ「メンバーではない」。
func (q *Queries) GetUserPrincipal(ctx context.Context, arg GetUserPrincipalParams) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getUserPrincipal, arg.WorkspaceID, arg.UserID)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.UserID,
		&i.SpaceID,
		&i.PageID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPrincipal = `-- name: InsertPrincipal :one

INSERT INTO principals (id, workspace_id, kind, user_id, space_id, page_id, name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, kind, user_id, space_id, page_id, name, created_at, updated_at
`

type InsertPrincipalParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Kind        string
	UserID      sql.NullInt64
	SpaceID     uuid.NullUUID
	PageID      uuid.NullUUID
	Name        string
}

// ナレッジ基盤の権限モデル（principals / principal_members / workspace_grants /
// space_grants / page_restrictions / share_links）のクエリ。
//
// 作法（knowledge_base.sql と同じ）:
//   - すべての SELECT / UPDATE / DELETE の WHERE に workspace_id を含める。
//     DB の複合 FK が守るのは「書き込み時に境界を越えられないこと」までで、
//     読み出しのテナント越えはクエリレベルで塞ぐ。
//   - UPDATE 文には必ず updated_at = now() を明示する（GORM を通さないため自動更新が無い）。
//
// 権限解決の方針:
//   - SQL が返すのは「事実」（既定の役割・最も近い制限の段の集計）だけで、
//     どう組み合わせるかの規則は domain.ResolvePagePermission が持つ。
//     規則を SQL と Go の 2 か所に書くと、片方だけ直したときに
//     「1 ページを開くと見えるのに一覧には出ない」という直しにくいずれ方をする。
//   - 祖先をたどるのに再帰は使わない。page_paths（closure）を 1 回 JOIN して
//     depth が最小の段だけを見る。
//
// 主体の作成。使う列は kind で決まり、DB の CHECK が「その kind のときだけ非 NULL」を強制する。
func (q *Queries) InsertPrincipal(ctx context.Context, arg InsertPrincipalParams) (Principal, error) {
	row := q.db.QueryRowContext(ctx, insertPrincipal,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.UserID,
		arg.SpaceID,
		arg.PageID,
		arg.Name,
	)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.UserID,
		&i.SpaceID,
		&i.PageID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPrincipalMember = `-- name: InsertPrincipalMember :exec
INSERT INTO principal_members (workspace_id, group_principal_id, member_principal_id)
VALUES ($1, $2, $3)
ON CONFLICT (group_principal_id, member_principal_id) DO NOTHING
`

type InsertPrincipalMemberParams struct {
	WorkspaceID       uuid.UUID
	GroupPrincipalID  uuid.UUID
	MemberPrincipalID uuid.UUID
}

// グループへの所属追加。既にあれば何もしない（冪等）。
// group / member の kind は DB 側の生成列 + 複合 FK が固定するため、ここでは渡さない。
func (q *Queries) InsertPrincipalMember(ctx context.Context, arg InsertPrincipalMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertPrincipalMember, arg.WorkspaceID, arg.GroupPrincipalID, arg.MemberPrincipalID)
	return err
}

const insertShareLink = `-- name: InsertShareLink :one
INSERT INTO share_links (
    id, workspace_id, page_id, principal_id, capability,
    token_hash, password_hash, expires_at, created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, page_id, principal_id, principal_kind, capability, token_hash, password_hash, expires_at, revoked_at, created_by_user_id, created_at, updated_at
`

type InsertShareLinkParams struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	PageID          uuid.UUID
	PrincipalID     uuid.UUID
	Capability      string
	TokenHash       []byte
	PasswordHash    sql.NullString
	ExpiresAt       sql.NullTime
	CreatedByUserID int64
}

// 共有リンクの発行。principal（kind='share_link'）は同じトランザクションで先に作る。
func (q *Queries) InsertShareLink(ctx context.Context, arg InsertShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRowContext(ctx, insertShareLink,
		arg.ID,
		arg.WorkspaceID,
		arg.PageID,
		arg.PrincipalID,
		arg.Capability,
		arg.TokenHash,
		arg.PasswordHash,
		arg.ExpiresAt,
		arg.CreatedByUserID,
	)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PageID,
		&i.PrincipalID,
		&i.PrincipalKind,
		&i.Capability,
		&i.TokenHash,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isWorkspaceMember = `-- name: IsWorkspaceMember :one
SELECT EXISTS (
    SELECT 1 FROM principals
    WHERE workspace_id = $1 AND kind = 'user' AND user_id = $2
) AS is_member
`

type IsWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      sql.NullInt64
}

// ワークスペース所属の判定。principals が所属の唯一の表現なので、この 1 行の有無がすべて。
func (q *Queries) IsWorkspaceMember(ctx context.Context, arg IsWorkspaceMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listPageRestrictions = `-- name: ListPageRestrictions :many
SELECT workspace_id, page_id, principal_id, capability, mode, created_at, updated_at FROM page_restrictions
WHERE workspace_id = $1 AND page_id = $2
ORDER BY principal_id, capability
`

type ListPageRestrictionsParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
}

// そのページ自身に張られた例外の一覧（祖先から継承したものは含まない）。
func (q *Queries) ListPageRestrictions(ctx context.Context, arg ListPageRestrictionsParams) ([]PageRestriction, error) {
	rows, err := q.db.QueryContext(ctx, listPageRestrictions, arg.WorkspaceID, arg.PageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageRestriction{}
	for rows.Next() {
		var i PageRestriction
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.PageID,
			&i.PrincipalID,
			&i.Capability,
			&i.Mode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageShareLinks = `-- name: ListPageShareLinks :many
SELECT id, workspace_id, page_id, principal_id, principal_kind, capability, token_hash, password_hash, expires_at, revoked_at, created_by_user_id, created_at, updated_at FROM share_links
WHERE workspace_id = $1 AND page_id = $2
ORDER BY created_at DESC
`

type ListPageShareLinksParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
}

// そのページに発行された共有リンクの一覧（失効済みも含む）。
func (q *Queries) ListPageShareLinks(ctx context.Context, arg ListPageShareLinksParams) ([]ShareLink, error) {
	rows, err := q.db.QueryContext(ctx, listPageShareLinks, arg.WorkspaceID, arg.PageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareLink{}
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PageID,
			&i.PrincipalID,
			&i.PrincipalKind,
			&i.Capability,
			&i.TokenHash,
			&i.PasswordHash,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceGrants = `-- name: ListSpaceGrants :many
SELECT workspace_id, space_id, principal_id, role, created_at, updated_at FROM space_grants
WHERE workspace_id = $1 AND space_id = $2
ORDER BY principal_id
`

type ListSpaceGrantsParams struct {
	WorkspaceID uuid.UUID
	SpaceID     uuid.UUID
}

// スペースの grant 一覧（権限設定画面用）。
func (q *Queries) ListSpaceGrants(ctx context.Context, arg ListSpaceGrantsParams) ([]SpaceGrant, error) {
	rows, err := q.db.QueryContext(ctx, listSpaceGrants, arg.WorkspaceID, arg.SpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpaceGrant{}
	for rows.Next() {
		var i SpaceGrant
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.SpaceID,
			&i.PrincipalID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacePageViewFacts = `-- name: ListSpacePageViewFacts :many
WITH me AS (
    SELECT p.id
    FROM principals p
    WHERE p.workspace_id = $1
      AND p.kind = 'user' AND p.user_id = $3
),
mine AS (
    SELECT id FROM me
    UNION
    SELECT pm.group_principal_id
    FROM principal_members pm
    JOIN me ON me.id = pm.member_principal_id
    WHERE pm.workspace_id = $1
    UNION
    SELECT sp.id
    FROM principals sp
    WHERE sp.workspace_id = $1
      AND sp.kind = 'space_all' AND sp.space_id = $2
      AND EXISTS (SELECT 1 FROM me)
),
nearest AS (
    SELECT pp.page_id, pp.depth, r.mode, r.principal_id,
           MIN(pp.depth) OVER (PARTITION BY pp.page_id) AS nearest_depth
    FROM page_paths pp
    JOIN pages tp ON tp.workspace_id = pp.workspace_id AND tp.id = pp.page_id
    JOIN page_restrictions r
      ON r.workspace_id = pp.workspace_id AND r.page_id = pp.ancestor_id AND r.capability = 'view'
    WHERE pp.workspace_id = $1
      AND tp.space_id = $2 AND tp.archived_at IS NULL
),
exception AS (
    SELECT page_id,
           bool_or(mode = 'deny'  AND principal_id IN (SELECT id FROM mine)) AS denied,
           bool_or(mode = 'allow' AND principal_id IN (SELECT id FROM mine)) AS allowed,
           bool_or(mode = 'allow') AS has_allow_list
    FROM nearest
    WHERE depth = nearest_depth
    GROUP BY page_id
)
SELECT
    p.id, p.workspace_id, p.space_id, p.parent_id, p.position, p.title, p.created_by_user_id, p.archived_at, p.created_at, p.updated_at,
    EXISTS (SELECT 1 FROM me) AS is_member,
    -- 既定の役割の強さ。意味と 0 の扱いは ResolvePagePermissionFacts と同じ。
    COALESCE((
        SELECT max(CASE g."role"
                     WHEN 'admin' THEN 4 WHEN 'editor' THEN 3
                     WHEN 'commenter' THEN 2 WHEN 'viewer' THEN 1 ELSE 0 END)
        FROM (
            SELECT wg."role" FROM workspace_grants wg
             WHERE wg.workspace_id = $1
               AND wg.principal_id IN (SELECT id FROM mine)
            UNION ALL
            SELECT sg."role" FROM space_grants sg
             WHERE sg.workspace_id = $1 AND sg.space_id = $2
               AND sg.principal_id IN (SELECT id FROM mine)
        ) g
    ), 0)::integer AS grant_rank,
    (e.page_id IS NOT NULL)::boolean AS view_restricted,
    COALESCE(e.denied, false)::boolean AS view_denied,
    COALESCE(e.allowed, false)::boolean AS view_allowed,
    COALESCE(e.has_allow_list, false)::boolean AS view_has_allow_list
FROM pages p
LEFT JOIN exception e ON e.page_id = p.id
WHERE p.workspace_id = $1
  AND p.space_id = $2
  AND p.archived_at IS NULL
ORDER BY p."position"
`

type ListSpacePageViewFactsParams struct {
	WorkspaceID uuid.UUID
	SpaceID     uuid.UUID
	UserID      sql.NullInt64
}

type ListSpacePageViewFactsRow struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	SpaceID          uuid.UUID
	ParentID         uuid.NullUUID
	Position         string
	Title            string
	CreatedByUserID  int64
	ArchivedAt       sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
	IsMember         bool
	GrantRank        int32
	ViewRestricted   bool
	ViewDenied       bool
	ViewAllowed      bool
	ViewHasAllowList bool
}

// スペース配下の現役ページ全件と、それぞれの「閲覧の事実」を 1 回のクエリで返す。
// 判定は domain.ResolvePagePermission が行い、呼び出し側がふるい落とす。
//
// ページごとに権限クエリを投げる（N+1）ことは避ける。ツリー表示は 1 スペースで
// 数百〜数千ページを一度に扱うため、1 ページ 1 往復では表示のたびにその回数だけ往復する。
// 制限を持つページはごく少数なので、closure との JOIN で拾えるのは実際には数行だけになる。
func (q *Queries) ListSpacePageViewFacts(ctx context.Context, arg ListSpacePageViewFactsParams) ([]ListSpacePageViewFactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpacePageViewFacts, arg.WorkspaceID, arg.SpaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpacePageViewFactsRow{}
	for rows.Next() {
		var i ListSpacePageViewFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SpaceID,
			&i.ParentID,
			&i.Position,
			&i.Title,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsMember,
			&i.GrantRank,
			&i.ViewRestricted,
			&i.ViewDenied,
			&i.ViewAllowed,
			&i.ViewHasAllowList,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceGrants = `-- name: ListWorkspaceGrants :many
SELECT workspace_id, principal_id, role, created_at, updated_at FROM workspace_grants
WHERE workspace_id = $1
ORDER BY principal_id
`

// ワークスペースの grant 一覧（権限設定画面用）。
func (q *Queries) ListWorkspaceGrants(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceGrant, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceGrants, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceGrant{}
	for rows.Next() {
		var i WorkspaceGrant
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.PrincipalID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePagePermissionFacts = `-- name: ResolvePagePermissionFacts :one
WITH target AS (
    SELECT p.space_id
    FROM pages p
    WHERE p.workspace_id = $1 AND p.id = $2
),
me AS (
    SELECT p.id, p.kind
    FROM principals p
    WHERE p.workspace_id = $1
      AND (
            (p.kind = 'user' AND p.user_id = $3::bigint)
         OR (p.kind = 'share_link' AND p.id = $4::uuid)
      )
),
mine AS (
    SELECT id FROM me
    UNION
    SELECT pm.group_principal_id
    FROM principal_members pm
    JOIN me ON me.id = pm.member_principal_id
    WHERE pm.workspace_id = $1
    UNION
    SELECT sp.id
    FROM principals sp
    CROSS JOIN target t
    WHERE sp.workspace_id = $1
      AND sp.kind = 'space_all'
      AND sp.space_id = t.space_id
      AND EXISTS (SELECT 1 FROM me WHERE me.kind = 'user')
),
nearest AS (
    SELECT r.capability, r.mode, r.principal_id, pp.depth,
           MIN(pp.depth) OVER (PARTITION BY r.capability) AS nearest_depth
    FROM page_paths pp
    JOIN page_restrictions r
      ON r.workspace_id = pp.workspace_id AND r.page_id = pp.ancestor_id
    WHERE pp.workspace_id = $1 AND pp.page_id = $2
),
exception AS (
    SELECT capability,
           bool_or(mode = 'deny'  AND principal_id IN (SELECT id FROM mine)) AS denied,
           bool_or(mode = 'allow' AND principal_id IN (SELECT id FROM mine)) AS allowed,
           bool_or(mode = 'allow') AS has_allow_list
    FROM nearest
    WHERE depth = nearest_depth
    GROUP BY capability
)
SELECT
    EXISTS (SELECT 1 FROM target) AS page_exists,
    EXISTS (SELECT 1 FROM me WHERE me.kind = 'user') AS is_member,
    -- ワークスペースの grant とスペースの grant を合わせ、最も強い役割の強さを返す。
    -- 弱い方を採るとスペースに viewer を張るだけでワークスペース管理者を締め出せてしまう。
    --
    -- 役割そのもの（text）ではなく強さ（整数）を返すのは、役割が 1 つも無いときに
    -- NULL ではなく 0 で返すため。sqlc はスカラ副問い合わせの NULL 可能性を推論できず
    -- string 型を生成してしまい、grant が無い行の Scan がそこで落ちる。
    -- 0 は「grant が無い」を表し、persistence が domain.GrantRoleByRank で nil に直す
    -- （この値がそのまま上の層へ出ることはない）。
    -- CASE の並びは domain.GrantRole.Rank と一対一に対応させること。
    COALESCE((
        SELECT max(CASE g."role"
                     WHEN 'admin' THEN 4 WHEN 'editor' THEN 3
                     WHEN 'commenter' THEN 2 WHEN 'viewer' THEN 1 ELSE 0 END)
        FROM (
            SELECT wg."role" FROM workspace_grants wg
             WHERE wg.workspace_id = $1
               AND wg.principal_id IN (SELECT id FROM mine)
            UNION ALL
            SELECT sg."role" FROM space_grants sg CROSS JOIN target t
             WHERE sg.workspace_id = $1 AND sg.space_id = t.space_id
               AND sg.principal_id IN (SELECT id FROM mine)
        ) g
    ), 0)::integer AS grant_rank,
    EXISTS (SELECT 1 FROM exception e WHERE e.capability = 'view') AS view_restricted,
    COALESCE((SELECT e.denied FROM exception e WHERE e.capability = 'view'), false)::boolean AS view_denied,
    COALESCE((SELECT e.allowed FROM exception e WHERE e.capability = 'view'), false)::boolean AS view_allowed,
    COALESCE((SELECT e.has_allow_list FROM exception e WHERE e.capability = 'view'), false)::boolean AS view_has_allow_list,
    EXISTS (SELECT 1 FROM exception e WHERE e.capability = 'edit') AS edit_restricted,
    COALESCE((SELECT e.denied FROM exception e WHERE e.capability = 'edit'), false)::boolean AS edit_denied,
    COALESCE((SELECT e.allowed FROM exception e WHERE e.capability = 'edit'), false)::boolean AS edit_allowed,
    COALESCE((SELECT e.has_allow_list FROM exception e WHERE e.capability = 'edit'), false)::boolean AS edit_has_allow_list
`

type ResolvePagePermissionFactsParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	UserID      sql.NullInt64
	PrincipalID uuid.NullUUID
}

type ResolvePagePermissionFactsRow struct {
	PageExists       bool
	IsMember         bool
	GrantRank        int32
	ViewRestricted   bool
	ViewDenied       bool
	ViewAllowed      bool
	ViewHasAllowList bool
	EditRestricted   bool
	EditDenied       bool
	EditAllowed      bool
	EditHasAllowList bool
}

// 1 ページの実効権限を決めるのに必要な「事実」を 1 回のクエリで集める。
// 判定そのものは domain.ResolvePagePermission が行う（ここには規則を書かない）。
//
// user_id / principal_id はどちらか一方だけを渡す。前者はログイン済みユーザーとして、
// 後者は共有リンクの来訪者（kind='share_link'）として解決する。
//
// CTE の役割:
//
//	target    … 対象ページの所属スペース（space_grants を引くのに要る）
//	me        … 自分自身の主体
//	mine      … 自分に効く主体すべて（自分 + 所属グループ + スペース全員）。
//	             グループの入れ子は DB 側で禁じているので 1 段の JOIN で足りる。
//	             スペース全員はメンバーにだけ効かせる（共有リンクの来訪者には効かせない）。
//	nearest   … 自分と祖先に張られた制限。ケイパビリティごとに最小 depth を窓関数で求める
//	exception … その最小 depth の段「だけ」を集計する（より遠い祖先は見ない）
func (q *Queries) ResolvePagePermissionFacts(ctx context.Context, arg ResolvePagePermissionFactsParams) (ResolvePagePermissionFactsRow, error) {
	row := q.db.QueryRowContext(ctx, resolvePagePermissionFacts,
		arg.WorkspaceID,
		arg.PageID,
		arg.UserID,
		arg.PrincipalID,
	)
	var i ResolvePagePermissionFactsRow
	err := row.Scan(
		&i.PageExists,
		&i.IsMember,
		&i.GrantRank,
		&i.ViewRestricted,
		&i.ViewDenied,
		&i.ViewAllowed,
		&i.ViewHasAllowList,
		&i.EditRestricted,
		&i.EditDenied,
		&i.EditAllowed,
		&i.EditHasAllowList,
	)
	return i, err
}

const revokeShareLink = `-- name: RevokeShareLink :execrows
UPDATE share_links
SET revoked_at = now(), updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND revoked_at IS NULL
`

type RevokeShareLinkParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// 共有リンクの失効。行は消さず revoked_at を立てる（誰がいつ止めたかを追えるように）。
// 既に失効しているものは触らない（最初に止めた時刻を保つ）。
func (q *Queries) RevokeShareLink(ctx context.Context, arg RevokeShareLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeShareLink, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertPageRestriction = `-- name: UpsertPageRestriction :one
INSERT INTO page_restrictions (workspace_id, page_id, principal_id, capability, mode)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, page_id, principal_id, capability)
DO UPDATE SET mode = EXCLUDED.mode, updated_at = now()
RETURNING workspace_id, page_id, principal_id, capability, mode, created_at, updated_at
`

type UpsertPageRestrictionParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	PrincipalID uuid.UUID
	Capability  string
	Mode        string
}

// ページの例外の設定。同じ (ページ, 主体, ケイパビリティ) の行は 1 つだけなので、
// allow と deny を入れ替えるときも行は増えない。
func (q *Queries) UpsertPageRestriction(ctx context.Context, arg UpsertPageRestrictionParams) (PageRestriction, error) {
	row := q.db.QueryRowContext(ctx, upsertPageRestriction,
		arg.WorkspaceID,
		arg.PageID,
		arg.PrincipalID,
		arg.Capability,
		arg.Mode,
	)
	var i PageRestriction
	err := row.Scan(
		&i.WorkspaceID,
		&i.PageID,
		&i.PrincipalID,
		&i.Capability,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSpaceGrant = `-- name: UpsertSpaceGrant :one
INSERT INTO space_grants (workspace_id, space_id, principal_id, "role")
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, space_id, principal_id)
DO UPDATE SET "role" = EXCLUDED."role", updated_at = now()
RETURNING workspace_id, space_id, principal_id, role, created_at, updated_at
`

type UpsertSpaceGrantParams struct {
	WorkspaceID uuid.UUID
	SpaceID     uuid.UUID
	PrincipalID uuid.UUID
	Role        string
}

// スペースでの既定の役割の付与（同じ主体には 1 行だけ）。
func (q *Queries) UpsertSpaceGrant(ctx context.Context, arg UpsertSpaceGrantParams) (SpaceGrant, error) {
	row := q.db.QueryRowContext(ctx, upsertSpaceGrant,
		arg.WorkspaceID,
		arg.SpaceID,
		arg.PrincipalID,
		arg.Role,
	)
	var i SpaceGrant
	err := row.Scan(
		&i.WorkspaceID,
		&i.SpaceID,
		&i.PrincipalID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspaceGrant = `-- name: UpsertWorkspaceGrant :one
INSERT INTO workspace_grants (workspace_id, principal_id, "role")
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, principal_id)
DO UPDATE SET "role" = EXCLUDED."role", updated_at = now()
RETURNING workspace_id, principal_id, role, created_at, updated_at
`

type UpsertWorkspaceGrantParams struct {
	WorkspaceID uuid.UUID
	PrincipalID uuid.UUID
	Role        string
}

// ワークスペース全体での既定の役割の付与（同じ主体には 1 行だけ）。
func (q *Queries) UpsertWorkspaceGrant(ctx context.Context, arg UpsertWorkspaceGrantParams) (WorkspaceGrant, error) {
	row := q.db.QueryRowContext(ctx, upsertWorkspaceGrant, arg.WorkspaceID, arg.PrincipalID, arg.Role)
	var i WorkspaceGrant
	err := row.Scan(
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
