// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: master_exercise_example.sql

package sqlcgen

import (
	"context"
)

const listMasterExerciseExamplesByExerciseID = `-- name: ListMasterExerciseExamplesByExerciseID :many
SELECT id, exercise_id, order_index, input_text, expected_output, created_at, updated_at FROM master_exercise_examples
WHERE exercise_id = $1
ORDER BY order_index ASC, id ASC
`

// 1 問の入力例 / 期待出力例を表示・採点順（order_index, id）で返す。
func (q *Queries) ListMasterExerciseExamplesByExerciseID(ctx context.Context, exerciseID int64) ([]MasterExerciseExample, error) {
	rows, err := q.db.QueryContext(ctx, listMasterExerciseExamplesByExerciseID, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterExerciseExample{}
	for rows.Next() {
		var i MasterExerciseExample
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.OrderIndex,
			&i.InputText,
			&i.ExpectedOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
