// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: material_permission.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteChapterGrant = `-- name: DeleteChapterGrant :execrows
DELETE FROM chapter_grants
WHERE workspace_id = $1 AND chapter_id = $2 AND principal_id = $3
`

type DeleteChapterGrantParams struct {
	WorkspaceID uuid.UUID
	ChapterID   int64
	PrincipalID uuid.UUID
}

func (q *Queries) DeleteChapterGrant(ctx context.Context, arg DeleteChapterGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChapterGrant, arg.WorkspaceID, arg.ChapterID, arg.PrincipalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCourseGrant = `-- name: DeleteCourseGrant :execrows
DELETE FROM course_grants
WHERE workspace_id = $1 AND course_id = $2 AND principal_id = $3
`

type DeleteCourseGrantParams struct {
	WorkspaceID uuid.UUID
	CourseID    int64
	PrincipalID uuid.UUID
}

func (q *Queries) DeleteCourseGrant(ctx context.Context, arg DeleteCourseGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCourseGrant, arg.WorkspaceID, arg.CourseID, arg.PrincipalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listChapterGrants = `-- name: ListChapterGrants :many
SELECT workspace_id, chapter_id, principal_id, role, created_at, updated_at FROM chapter_grants
WHERE workspace_id = $1 AND chapter_id = $2
ORDER BY principal_id
`

type ListChapterGrantsParams struct {
	WorkspaceID uuid.UUID
	ChapterID   int64
}

// その章自身に張られた付与の一覧（コースから降りてくる分は含まない）。
func (q *Queries) ListChapterGrants(ctx context.Context, arg ListChapterGrantsParams) ([]ChapterGrant, error) {
	rows, err := q.db.QueryContext(ctx, listChapterGrants, arg.WorkspaceID, arg.ChapterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChapterGrant{}
	for rows.Next() {
		var i ChapterGrant
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChapterID,
			&i.PrincipalID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseFactsForUser = `-- name: ListCourseFactsForUser :many
WITH me AS (
    SELECT pr.id
    FROM principals pr
    WHERE pr.workspace_id = $1
      AND pr.kind = 'user' AND pr.user_id = $2
),
mine AS (
    SELECT id FROM me
    UNION
    SELECT pm.group_principal_id
    FROM principal_members pm
    JOIN me ON me.id = pm.member_principal_id
    WHERE pm.workspace_id = $1
),
ranks AS (
    SELECT cg.course_id,
           max(CASE cg."role"
                 WHEN 'admin' THEN 4 WHEN 'editor' THEN 3
                 WHEN 'commenter' THEN 2 WHEN 'viewer' THEN 1 ELSE 0 END) AS rank
    FROM course_grants cg
    WHERE cg.workspace_id = $1
      AND cg.principal_id IN (SELECT id FROM mine)
    GROUP BY cg.course_id
)
SELECT c.id, c.created_by_user_id, c.title, c.description, c.category, c.language, c.sort_order, c.is_published, c.created_at, c.updated_at, c.workspace_id,
    EXISTS (SELECT 1 FROM me) AS is_member,
    EXISTS (
        SELECT 1 FROM workspace_grants wg
         WHERE wg.workspace_id = $1
           AND wg.principal_id IN (SELECT id FROM mine)
           AND wg."role" = 'admin'
    ) AS is_workspace_admin,
    COALESCE(r.rank, 0)::integer AS grant_rank
FROM courses c
LEFT JOIN ranks r ON r.course_id = c.id
WHERE c.workspace_id = $1
ORDER BY c.sort_order, c.id
`

type ListCourseFactsForUserParams struct {
	WorkspaceID uuid.UUID
	UserID      sql.NullInt64
}

type ListCourseFactsForUserRow struct {
	ID               int64
	CreatedByUserID  int64
	Title            string
	Description      string
	Category         string
	Language         string
	SortOrder        int64
	IsPublished      bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
	WorkspaceID      uuid.NullUUID
	IsMember         bool
	IsWorkspaceAdmin bool
	GrantRank        int32
}

// ワークスペース内のコース全件と、その実効権限を決める事実を 1 回のクエリで返す。
//
// **返り値はまだ「見せてよいコース」ではない。** ふるい落とすのは呼び出し側で、
// 判定は domain.ResolveMaterialPermission が行う（ここで絞ると規則が 2 箇所に分かれる）。
//
// コースごとに ResolveCoursePermissionFacts を呼ぶ（N+1）ことはしない。一覧は画面を
// 開くたびに引くので、コース数だけ往復するとそのまま待ち時間になる。
func (q *Queries) ListCourseFactsForUser(ctx context.Context, arg ListCourseFactsForUserParams) ([]ListCourseFactsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listCourseFactsForUser, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourseFactsForUserRow{}
	for rows.Next() {
		var i ListCourseFactsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByUserID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Language,
			&i.SortOrder,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
			&i.IsMember,
			&i.IsWorkspaceAdmin,
			&i.GrantRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseGrants = `-- name: ListCourseGrants :many
SELECT workspace_id, course_id, principal_id, role, created_at, updated_at FROM course_grants
WHERE workspace_id = $1 AND course_id = $2
ORDER BY principal_id
`

type ListCourseGrantsParams struct {
	WorkspaceID uuid.UUID
	CourseID    int64
}

// そのコース自身に張られた付与の一覧（章に張った分は含まない）。
func (q *Queries) ListCourseGrants(ctx context.Context, arg ListCourseGrantsParams) ([]CourseGrant, error) {
	rows, err := q.db.QueryContext(ctx, listCourseGrants, arg.WorkspaceID, arg.CourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseGrant{}
	for rows.Next() {
		var i CourseGrant
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.CourseID,
			&i.PrincipalID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveChapterPermissionFacts = `-- name: ResolveChapterPermissionFacts :one

WITH me AS (
    SELECT pr.id
    FROM principals pr
    WHERE pr.workspace_id = $1
      AND pr.kind = 'user' AND pr.user_id = $2
),
mine AS (
    SELECT id FROM me
    UNION
    SELECT pm.group_principal_id
    FROM principal_members pm
    JOIN me ON me.id = pm.member_principal_id
    WHERE pm.workspace_id = $1
),
target AS (
    SELECT ch.id, ch.course_id, ch.is_published
    FROM course_chapters ch
    WHERE ch.workspace_id = $1 AND ch.id = $3
)
SELECT
    EXISTS (SELECT 1 FROM target) AS target_exists,
    EXISTS (SELECT 1 FROM me) AS is_member,
    -- COALESCE(bool 式, false) だと sqlc の型推論が interface{} に落ちるので EXISTS で書く
    -- （driver が NULL を bool へ Scan できずに落ちることを別の口で確認済み）。
    -- 対象が無ければ false になるが、その場合は呼び出し側が target_exists で先に断る。
    EXISTS (SELECT 1 FROM target WHERE is_published) AS is_published,
    EXISTS (
        SELECT 1 FROM workspace_grants wg
         WHERE wg.workspace_id = $1
           AND wg.principal_id IN (SELECT id FROM mine)
           AND wg."role" = 'admin'
    ) AS is_workspace_admin,
    GREATEST(
        COALESCE((
            SELECT max(CASE cg."role"
                         WHEN 'admin' THEN 4 WHEN 'editor' THEN 3
                         WHEN 'commenter' THEN 2 WHEN 'viewer' THEN 1 ELSE 0 END)
            FROM course_grants cg
            JOIN target t ON t.course_id = cg.course_id
            WHERE cg.workspace_id = $1
              AND cg.principal_id IN (SELECT id FROM mine)
        ), 0),
        COALESCE((
            SELECT max(CASE chg."role"
                         WHEN 'admin' THEN 4 WHEN 'editor' THEN 3
                         WHEN 'commenter' THEN 2 WHEN 'viewer' THEN 1 ELSE 0 END)
            FROM chapter_grants chg
            JOIN target t ON t.id = chg.chapter_id
            WHERE chg.workspace_id = $1
              AND chg.principal_id IN (SELECT id FROM mine)
        ), 0)
    )::integer AS grant_rank
`

type ResolveChapterPermissionFactsParams struct {
	WorkspaceID uuid.UUID
	UserID      sql.NullInt64
	ChapterID   int64
}

type ResolveChapterPermissionFactsRow struct {
	TargetExists     bool
	IsMember         bool
	IsPublished      bool
	IsWorkspaceAdmin bool
	GrantRank        int32
}

// 教材（コース / 章）の権限。
//
// ノートと同じ「事実だけを集めて、規則は domain が持つ」分担にする。ここが返すのは
// 所属・公開状態・ワークスペースの admin か・届いている役割の強さの 4 つで、
// そこから何ができるかは domain.ResolveMaterialPermission だけが決める。
//
// 役割は強さ（整数）で返す。役割そのもの（text）を返すと「付与が 1 つも無い」が NULL に
// なり、生成コードの型付けが崩れる（ノート側と同じ理由）。
// 章 1 つの実効権限を決める事実を 1 回のクエリで集める。
//
// **ワークスペースの grant は admin だけを見る。** editor / commenter / viewer は
// ノートの木に対する既定で、教材には届かせない（届かせると、ノートの editor である人が
// 教材の編集権まで一度に得てしまう）。この 1 行がその境目そのもの。
//
// 「スペースの全員」（kind='space_all'）も混ぜない。あれはノートのスペースに紐づく主体で、
// 教材はスペースに属さない。
func (q *Queries) ResolveChapterPermissionFacts(ctx context.Context, arg ResolveChapterPermissionFactsParams) (ResolveChapterPermissionFactsRow, error) {
	row := q.db.QueryRowContext(ctx, resolveChapterPermissionFacts, arg.WorkspaceID, arg.UserID, arg.ChapterID)
	var i ResolveChapterPermissionFactsRow
	err := row.Scan(
		&i.TargetExists,
		&i.IsMember,
		&i.IsPublished,
		&i.IsWorkspaceAdmin,
		&i.GrantRank,
	)
	return i, err
}

const resolveCoursePermissionFacts = `-- name: ResolveCoursePermissionFacts :one
WITH me AS (
    SELECT pr.id
    FROM principals pr
    WHERE pr.workspace_id = $1
      AND pr.kind = 'user' AND pr.user_id = $2
),
mine AS (
    SELECT id FROM me
    UNION
    SELECT pm.group_principal_id
    FROM principal_members pm
    JOIN me ON me.id = pm.member_principal_id
    WHERE pm.workspace_id = $1
),
target AS (
    SELECT c.id, c.is_published
    FROM courses c
    WHERE c.workspace_id = $1 AND c.id = $3
)
SELECT
    EXISTS (SELECT 1 FROM target) AS target_exists,
    EXISTS (SELECT 1 FROM me) AS is_member,
    -- COALESCE(bool 式, false) だと sqlc の型推論が interface{} に落ちるので EXISTS で書く
    -- （driver が NULL を bool へ Scan できずに落ちることを別の口で確認済み）。
    -- 対象が無ければ false になるが、その場合は呼び出し側が target_exists で先に断る。
    EXISTS (SELECT 1 FROM target WHERE is_published) AS is_published,
    EXISTS (
        SELECT 1 FROM workspace_grants wg
         WHERE wg.workspace_id = $1
           AND wg.principal_id IN (SELECT id FROM mine)
           AND wg."role" = 'admin'
    ) AS is_workspace_admin,
    COALESCE((
        SELECT max(CASE cg."role"
                     WHEN 'admin' THEN 4 WHEN 'editor' THEN 3
                     WHEN 'commenter' THEN 2 WHEN 'viewer' THEN 1 ELSE 0 END)
        FROM course_grants cg
        JOIN target t ON t.id = cg.course_id
        WHERE cg.workspace_id = $1
          AND cg.principal_id IN (SELECT id FROM mine)
    ), 0)::integer AS grant_rank
`

type ResolveCoursePermissionFactsParams struct {
	WorkspaceID uuid.UUID
	UserID      sql.NullInt64
	CourseID    int64
}

type ResolveCoursePermissionFactsRow struct {
	TargetExists     bool
	IsMember         bool
	IsPublished      bool
	IsWorkspaceAdmin bool
	GrantRank        int32
}

// コース 1 つの実効権限を決める事実を集める。見方は章と同じで、章の付与は見ない
// （章に張った権限はその章にしか効かず、コースそのものへは上がらない）。
func (q *Queries) ResolveCoursePermissionFacts(ctx context.Context, arg ResolveCoursePermissionFactsParams) (ResolveCoursePermissionFactsRow, error) {
	row := q.db.QueryRowContext(ctx, resolveCoursePermissionFacts, arg.WorkspaceID, arg.UserID, arg.CourseID)
	var i ResolveCoursePermissionFactsRow
	err := row.Scan(
		&i.TargetExists,
		&i.IsMember,
		&i.IsPublished,
		&i.IsWorkspaceAdmin,
		&i.GrantRank,
	)
	return i, err
}

const upsertChapterGrant = `-- name: UpsertChapterGrant :one
INSERT INTO chapter_grants (workspace_id, chapter_id, principal_id, "role")
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, chapter_id, principal_id)
DO UPDATE SET "role" = EXCLUDED."role", updated_at = now()
RETURNING workspace_id, chapter_id, principal_id, role, created_at, updated_at
`

type UpsertChapterGrantParams struct {
	WorkspaceID uuid.UUID
	ChapterID   int64
	PrincipalID uuid.UUID
	Role        string
}

// 章 1 つでの既定の役割の付与。コースの付与より弱い役割をここに張っても下がらない
// （合成は最も強いものを採る）。
func (q *Queries) UpsertChapterGrant(ctx context.Context, arg UpsertChapterGrantParams) (ChapterGrant, error) {
	row := q.db.QueryRowContext(ctx, upsertChapterGrant,
		arg.WorkspaceID,
		arg.ChapterID,
		arg.PrincipalID,
		arg.Role,
	)
	var i ChapterGrant
	err := row.Scan(
		&i.WorkspaceID,
		&i.ChapterID,
		&i.PrincipalID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCourseGrant = `-- name: UpsertCourseGrant :one
INSERT INTO course_grants (workspace_id, course_id, principal_id, "role")
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, course_id, principal_id)
DO UPDATE SET "role" = EXCLUDED."role", updated_at = now()
RETURNING workspace_id, course_id, principal_id, role, created_at, updated_at
`

type UpsertCourseGrantParams struct {
	WorkspaceID uuid.UUID
	CourseID    int64
	PrincipalID uuid.UUID
	Role        string
}

// コースでの既定の役割の付与（同じ主体には 1 行だけ）。
func (q *Queries) UpsertCourseGrant(ctx context.Context, arg UpsertCourseGrantParams) (CourseGrant, error) {
	row := q.db.QueryRowContext(ctx, upsertCourseGrant,
		arg.WorkspaceID,
		arg.CourseID,
		arg.PrincipalID,
		arg.Role,
	)
	var i CourseGrant
	err := row.Scan(
		&i.WorkspaceID,
		&i.CourseID,
		&i.PrincipalID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
