// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AuditEvent struct {
	ID         int64
	ActorID    int64
	ActorEmail string
	ActorRole  string
	Action     string
	TargetID   int64
	CreatedAt  time.Time
}

type Block struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	ParentID    uuid.NullUUID
	Position    string
	Type        string
	Attrs       json.RawMessage
	Inline      *json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Company struct {
	ID                       int64
	Name                     string
	AiChatEnabledForTrainees bool
	IsActive                 bool
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type CompanyApplication struct {
	ID            int64
	CompanyName   string
	ApplicantName string
	Email         string
	Message       string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Course struct {
	ID              int64
	CompanyID       int64
	CreatedByUserID int64
	Title           string
	Description     string
	Category        string
	Language        string
	SortOrder       int32
	IsPublished     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type MasterExerciseExample struct {
	ID             int64
	ExerciseID     int64
	OrderIndex     int16
	InputText      string
	ExpectedOutput string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Note struct {
	ID        int64
	UserID    int64
	Title     string
	Content   string
	IsPublic  bool
	IsPinned  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Notification struct {
	ID        int64
	UserID    int64
	Type      string
	Title     string
	Body      string
	IsRead    bool
	CreatedAt time.Time
}

type Page struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	SpaceID         uuid.UUID
	ParentID        uuid.NullUUID
	Position        string
	Title           string
	CreatedByUserID int64
	ArchivedAt      sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type PageAllowList struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	Capability  string
	CreatedAt   time.Time
}

type PagePath struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	AncestorID  uuid.UUID
	Depth       int32
}

type PageRestriction struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	PrincipalID uuid.UUID
	Capability  string
	Mode        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PageSnapshot struct {
	PageID  uuid.UUID
	Doc     json.RawMessage
	BuiltAt time.Time
}

type Principal struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Kind        string
	UserID      sql.NullInt64
	SpaceID     uuid.NullUUID
	PageID      uuid.NullUUID
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PrincipalMember struct {
	WorkspaceID       uuid.UUID
	GroupPrincipalID  uuid.UUID
	MemberPrincipalID uuid.UUID
	GroupKind         sql.NullString
	MemberKind        sql.NullString
	CreatedAt         time.Time
}

type Profile struct {
	UserID        int64
	Bio           string
	AvatarUrl     string
	StatusMessage string
	UpdatedAt     time.Time
}

type Role struct {
	ID          int16
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SessionNote struct {
	ID        int64
	SessionID int64
	UserID    int64
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ShareLink struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	PageID          uuid.UUID
	PrincipalID     uuid.UUID
	PrincipalKind   sql.NullString
	Capability      string
	TokenHash       []byte
	PasswordHash    sql.NullString
	ExpiresAt       sql.NullTime
	RevokedAt       sql.NullTime
	CreatedByUserID int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Space struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Key         string
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SpaceGrant struct {
	WorkspaceID uuid.UUID
	SpaceID     uuid.UUID
	PrincipalID uuid.UUID
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID            int64
	Email         string
	PasswordHash  sql.NullString
	Name          string
	CompanyID     sql.NullInt64
	RoleID        int16
	AiChatEnabled sql.NullBool
	IsActive      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type UserOidcIdentity struct {
	ID        int64
	UserID    int64
	Provider  string
	Subject   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Workspace struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type WorkspaceGrant struct {
	WorkspaceID uuid.UUID
	PrincipalID uuid.UUID
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
