// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Block struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	ParentID    uuid.NullUUID
	Position    string
	Type        string
	Attrs       json.RawMessage
	Inline      *json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ExerciseSubmission struct {
	ID            int64
	UserID        int64
	ExerciseKind  string
	ExerciseID    int64
	SubmittedCode string
	Stdout        sql.NullString
	Stderr        sql.NullString
	ExitCode      int64
	IsCorrect     bool
	SubmittedAt   time.Time
}

type MasterExercise struct {
	ID             int64
	Slug           string
	Language       string
	SortOrder      int32
	Category       string
	Title          string
	Description    string
	StarterCode    string
	HintText       sql.NullString
	ExpectedOutput sql.NullString
	Mode           string
	Explanation    string
	Difficulty     int16
	IsPublished    bool
	ChapterID      sql.NullInt64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type MasterExerciseExample struct {
	ID             int64
	ExerciseID     int64
	OrderIndex     int16
	InputText      string
	ExpectedOutput string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Notification struct {
	ID        int64
	UserID    int64
	Type      string
	Title     string
	Body      string
	IsRead    bool
	CreatedAt time.Time
}

type Page struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	SpaceID         uuid.UUID
	ParentID        uuid.NullUUID
	Position        string
	Title           string
	CreatedByUserID int64
	ArchivedAt      sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type PageGrant struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	PrincipalID uuid.UUID
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PagePath struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	AncestorID  uuid.UUID
	Depth       int32
}

type PageSnapshot struct {
	PageID  uuid.UUID
	Doc     json.RawMessage
	BuiltAt time.Time
}

type Principal struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Kind        string
	UserID      sql.NullInt64
	SpaceID     uuid.NullUUID
	PageID      uuid.NullUUID
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PrincipalMember struct {
	WorkspaceID       uuid.UUID
	GroupPrincipalID  uuid.UUID
	MemberPrincipalID uuid.UUID
	GroupKind         sql.NullString
	MemberKind        sql.NullString
	CreatedAt         time.Time
}

type Profile struct {
	UserID        int64
	Bio           string
	AvatarUrl     string
	StatusMessage string
	UpdatedAt     time.Time
}

type ShareLink struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	PageID          uuid.UUID
	PrincipalID     uuid.UUID
	PrincipalKind   sql.NullString
	Capability      string
	TokenHash       []byte
	PasswordHash    sql.NullString
	ExpiresAt       sql.NullTime
	RevokedAt       sql.NullTime
	CreatedByUserID int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Space struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Key         string
	Name        string
	Visibility  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SpaceGrant struct {
	WorkspaceID uuid.UUID
	SpaceID     uuid.UUID
	PrincipalID uuid.UUID
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash sql.NullString
	Name         string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
	WorkspaceID  uuid.NullUUID
}

type UserDailyActivity struct {
	UserID        int64
	ActivityDate  time.Time
	ExerciseCount int32
	CorrectCount  int32
	ChapterCount  int32
	NoteCount     int32
}

type UserOidcIdentity struct {
	ID        int64
	UserID    int64
	Provider  string
	Subject   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Workspace struct {
	ID                  uuid.UUID
	Slug                string
	Name                string
	IsActive            bool
	PersonalOwnerUserID sql.NullInt64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type WorkspaceGrant struct {
	WorkspaceID uuid.UUID
	PrincipalID uuid.UUID
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
