// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type MasterExerciseExample struct {
	ID             int64
	ExerciseID     int64
	OrderIndex     int16
	InputText      string
	ExpectedOutput string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Note struct {
	ID        int64
	UserID    int64
	Title     string
	Content   string
	IsPublic  bool
	IsPinned  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID          int64
	CognitoSub  string
	Email       string
	DisplayName string
	CompanyID   sql.NullInt64
	Role        string
	OnboardedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}
