// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note.sql

package sqlcgen

import (
	"context"
)

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, user_id, title, content, is_public, is_pinned, created_at, updated_at FROM notes
WHERE id = $1
`

// 内部 ID で 1 件取得（所有者検証は usecase 側で user_id を突き合わせる）。
func (q *Queries) GetNoteByID(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotesByUserID = `-- name: ListNotesByUserID :many
SELECT id, user_id, title, content, is_public, is_pinned, created_at, updated_at FROM notes
WHERE user_id = $1
ORDER BY updated_at DESC
`

// 自分の学習メモ一覧を更新日時の新しい順で返す。
func (q *Queries) ListNotesByUserID(ctx context.Context, userID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.IsPinned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
