// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: page_label.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addPageLabel = `-- name: AddPageLabel :execrows

INSERT INTO page_labels (workspace_id, page_id, label_id, created_at)
VALUES ($1, $2, $3, now())
ON CONFLICT DO NOTHING
`

type AddPageLabelParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	LabelID     uuid.UUID
}

// ページへのラベル付け外し（page_labels）のクエリ（段 13）。labels 表そのもの・
// CRUD（Create/Find/List/Update/Delete）は ticket_label.sql をそのまま流用する
// （ページ専用の labels は作らない。語彙をチケットと共有する）。
// 付け外しは冪等（AddTicketLabel と同じ形 — 複合主キーの重複を無視する）。
func (q *Queries) AddPageLabel(ctx context.Context, arg AddPageLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addPageLabel, arg.WorkspaceID, arg.PageID, arg.LabelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listLabelsByPage = `-- name: ListLabelsByPage :many
SELECT l.id, l.workspace_id, l.name, l.name_key, l.color, l.created_at, l.updated_at FROM labels l
JOIN page_labels pl ON pl.workspace_id = l.workspace_id AND pl.label_id = l.id
WHERE pl.workspace_id = $1 AND pl.page_id = $2
ORDER BY l.name_key
`

type ListLabelsByPageParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
}

func (q *Queries) ListLabelsByPage(ctx context.Context, arg ListLabelsByPageParams) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabelsByPage, arg.WorkspaceID, arg.PageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.NameKey,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByPageIDs = `-- name: ListLabelsByPageIDs :many
SELECT pl.page_id, l.id, l.workspace_id, l.name, l.name_key, l.color, l.created_at, l.updated_at FROM page_labels pl
JOIN labels l ON l.workspace_id = pl.workspace_id AND l.id = pl.label_id
WHERE pl.workspace_id = $1
  AND pl.page_id IN (
    SELECT value::uuid FROM json_array_elements_text($2::json) AS t(value)
  )
ORDER BY pl.page_id, l.name_key
`

type ListLabelsByPageIDsParams struct {
	WorkspaceID uuid.UUID
	PageIds     json.RawMessage
}

type ListLabelsByPageIDsRow struct {
	PageID      uuid.UUID
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	NameKey     sql.NullString
	Color       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// page_id ごとのラベル一覧を 1 回でまとめて引く（ListLabelsByTicketIDs と同じ理由・同じ形）。
func (q *Queries) ListLabelsByPageIDs(ctx context.Context, arg ListLabelsByPageIDsParams) ([]ListLabelsByPageIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLabelsByPageIDs, arg.WorkspaceID, arg.PageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsByPageIDsRow{}
	for rows.Next() {
		var i ListLabelsByPageIDsRow
		if err := rows.Scan(
			&i.PageID,
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.NameKey,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePageLabel = `-- name: RemovePageLabel :execrows
DELETE FROM page_labels WHERE workspace_id = $1 AND page_id = $2 AND label_id = $3
`

type RemovePageLabelParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	LabelID     uuid.UUID
}

func (q *Queries) RemovePageLabel(ctx context.Context, arg RemovePageLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removePageLabel, arg.WorkspaceID, arg.PageID, arg.LabelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
