// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: page_attachment.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createPageAttachment = `-- name: CreatePageAttachment :one

INSERT INTO page_attachments
  (id, workspace_id, page_id, key, filename, content_type, size_bytes, uploaded_by_user_id, created_at)
VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, now()
)
RETURNING id, workspace_id, page_id, key, filename, content_type, size_bytes, uploaded_by_user_id, created_at
`

type CreatePageAttachmentParams struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	PageID           uuid.UUID
	Key              string
	Filename         string
	ContentType      string
	SizeBytes        int64
	UploadedByUserID int64
}

// ナレッジのページ本文に置く添付ファイルのメタデータ。本体は Cloud Storage。
func (q *Queries) CreatePageAttachment(ctx context.Context, arg CreatePageAttachmentParams) (PageAttachment, error) {
	row := q.db.QueryRowContext(ctx, createPageAttachment,
		arg.ID,
		arg.WorkspaceID,
		arg.PageID,
		arg.Key,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.UploadedByUserID,
	)
	var i PageAttachment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PageID,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const findPageAttachment = `-- name: FindPageAttachment :one
SELECT id, workspace_id, page_id, key, filename, content_type, size_bytes, uploaded_by_user_id, created_at FROM page_attachments WHERE workspace_id = $1 AND page_id = $2 AND id = $3
`

type FindPageAttachmentParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	ID          uuid.UUID
}

// ダウンロード URL の発行で 1 件を引く。ワークスペースとページで絞るので、見つかった時点で
// 「このページの添付」だと確定する（別ページの ID を URL に入れても 0 行）。
func (q *Queries) FindPageAttachment(ctx context.Context, arg FindPageAttachmentParams) (PageAttachment, error) {
	row := q.db.QueryRowContext(ctx, findPageAttachment, arg.WorkspaceID, arg.PageID, arg.ID)
	var i PageAttachment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PageID,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listPageAttachmentsByIDs = `-- name: ListPageAttachmentsByIDs :many
SELECT id, workspace_id, page_id, key, filename, content_type, size_bytes, uploaded_by_user_id, created_at FROM page_attachments
WHERE workspace_id = $1
  AND page_id = $2
  AND id IN (SELECT value::uuid FROM json_array_elements_text($3::json))
`

type ListPageAttachmentsByIDsParams struct {
	WorkspaceID   uuid.UUID
	PageID        uuid.UUID
	AttachmentIds json.RawMessage
}

// 本文の保存時に、本文の attachment ノードが指す ID 群のうち「このページの添付」を 1 回で返す。
// 返らなかった ID は別ページ・別ワークスペース・存在しないのどれか（呼び出し側が保存を断る）。
//
// attachment_ids は json 配列（文字列の UUID）。IN 句のスライス展開を使わない理由と、呼び出し側
// （Go）が UUID として読めない値を先に落とす理由は ListWorkspacePageViewFactsByIDs と同じ
// （database/sql モードでは lib/pq 依存が増える・ここで ::uuid が失敗するとクエリ全体が落ちる）。
func (q *Queries) ListPageAttachmentsByIDs(ctx context.Context, arg ListPageAttachmentsByIDsParams) ([]PageAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listPageAttachmentsByIDs, arg.WorkspaceID, arg.PageID, arg.AttachmentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageAttachment{}
	for rows.Next() {
		var i PageAttachment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PageID,
			&i.Key,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.UploadedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
