// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: page_version.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createPageVersion = `-- name: CreatePageVersion :one
INSERT INTO page_versions (workspace_id, page_id, seq, doc, author_user_id, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING workspace_id, page_id, seq, doc, author_user_id, note, created_at
`

type CreatePageVersionParams struct {
	WorkspaceID  uuid.UUID
	PageID       uuid.UUID
	Seq          int64
	Doc          json.RawMessage
	AuthorUserID int64
	Note         sql.NullString
}

// 版を 1 件挿入する。seq は呼び出し側（Go）が LockPageForVersioning でロックした後に
// GetLatestPageVersion の結果 + 1（無ければ 1）で計算して渡す — SQL 側では採番しない
// （採番を SQL の DEFAULT やシーケンスに任せると、ロックの外で採番が起きて衝突しうる）。
func (q *Queries) CreatePageVersion(ctx context.Context, arg CreatePageVersionParams) (PageVersion, error) {
	row := q.db.QueryRowContext(ctx, createPageVersion,
		arg.WorkspaceID,
		arg.PageID,
		arg.Seq,
		arg.Doc,
		arg.AuthorUserID,
		arg.Note,
	)
	var i PageVersion
	err := row.Scan(
		&i.WorkspaceID,
		&i.PageID,
		&i.Seq,
		&i.Doc,
		&i.AuthorUserID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldPageVersions = `-- name: DeleteOldPageVersions :exec
DELETE FROM page_versions
WHERE workspace_id = $1 AND page_id = $2 AND created_at < $3
`

type DeleteOldPageVersionsParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	Cutoff      time.Time
}

// 30 日保持の掃除。CreatePageVersion と同じトランザクションで、挿入の直後に呼ぶ。
// cutoff は Go 側の time.Now().Add(-30*24*time.Hour) を渡す（DB の now() には頼らない —
// 10 分規則の判定も Go 側の time.Now() を使っており、両者の時刻の出どころを揃えるため）。
// 今挿入した行は created_at が cutoff より新しいので、この DELETE の対象にはならない。
func (q *Queries) DeleteOldPageVersions(ctx context.Context, arg DeleteOldPageVersionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldPageVersions, arg.WorkspaceID, arg.PageID, arg.Cutoff)
	return err
}

const getLatestPageVersion = `-- name: GetLatestPageVersion :one
SELECT workspace_id, page_id, seq, doc, author_user_id, note, created_at FROM page_versions
WHERE workspace_id = $1 AND page_id = $2
ORDER BY seq DESC
LIMIT 1
`

type GetLatestPageVersionParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
}

// そのページの直近の版（seq 降順 1 件）。PK (page_id, seq) の btree だけで素引きできる
// （schema.hcl の page_versions のコメント参照）。版が 1 つも無ければ sql.ErrNoRows —
// これは「まだ版が無い」という正常な状態で、呼び出し側はエラーとして扱わない。
func (q *Queries) GetLatestPageVersion(ctx context.Context, arg GetLatestPageVersionParams) (PageVersion, error) {
	row := q.db.QueryRowContext(ctx, getLatestPageVersion, arg.WorkspaceID, arg.PageID)
	var i PageVersion
	err := row.Scan(
		&i.WorkspaceID,
		&i.PageID,
		&i.Seq,
		&i.Doc,
		&i.AuthorUserID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getPageVersion = `-- name: GetPageVersion :one
SELECT workspace_id, page_id, seq, doc, author_user_id, note, created_at FROM page_versions
WHERE workspace_id = $1 AND page_id = $2 AND seq = $3
`

type GetPageVersionParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
	Seq         int64
}

// 版 1 件の取得。workspace_id まで絞ることで、他ページ・他テナントの seq を渡されても
// 見つからない（＝存在しないのと同じ）ようにする。
func (q *Queries) GetPageVersion(ctx context.Context, arg GetPageVersionParams) (PageVersion, error) {
	row := q.db.QueryRowContext(ctx, getPageVersion, arg.WorkspaceID, arg.PageID, arg.Seq)
	var i PageVersion
	err := row.Scan(
		&i.WorkspaceID,
		&i.PageID,
		&i.Seq,
		&i.Doc,
		&i.AuthorUserID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listPageVersions = `-- name: ListPageVersions :many
SELECT workspace_id, page_id, seq, doc, author_user_id, note, created_at FROM page_versions
WHERE workspace_id = $1 AND page_id = $2
ORDER BY seq DESC
LIMIT 500
`

type ListPageVersionsParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
}

// 版一覧。seq 降順・上限 500 件（defensive な LIMIT。ページネーションは今回作らない。
// 500 を超えるページでは 501 件目以降が一覧に出ない — repository.PageVersionRepository の
// ListVersions のコメント参照）。
func (q *Queries) ListPageVersions(ctx context.Context, arg ListPageVersionsParams) ([]PageVersion, error) {
	rows, err := q.db.QueryContext(ctx, listPageVersions, arg.WorkspaceID, arg.PageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageVersion{}
	for rows.Next() {
		var i PageVersion
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.PageID,
			&i.Seq,
			&i.Doc,
			&i.AuthorUserID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPageForVersioning = `-- name: LockPageForVersioning :one

SELECT id FROM pages
WHERE workspace_id = $1 AND id = $2
FOR UPDATE
`

type LockPageForVersioningParams struct {
	WorkspaceID uuid.UUID
	PageID      uuid.UUID
}

// page_versions（ページ本文の明示的なスナップショット履歴）のクエリ。FRESTYLE-433 段 3。
//
// 採番・間引き・掃除の判定はすべて Go 側（PageVersionRepository.CreateVersionIfDue）が行う。
// ここに並ぶクエリはその手順 1 つずつの実体で、単独では「版を残すべきか」の意味を持たない。
// 版の書き込み（本文保存経路・「版を残す」・復元のすべて）が最初に呼ぶ。この 1 行をロックする
// ことで、同じページへの同時書き込みはここで直列化され、page_versions の PK (page_id, seq) の
// 衝突が原理的に起きない（usecase/repository/page_version.go の CreateVersionIfDue ドキュメント
// 参照）。対象が無ければ呼び出し側は sql.ErrNoRows を repository.ErrPageNotFound へ翻訳する。
func (q *Queries) LockPageForVersioning(ctx context.Context, arg LockPageForVersioningParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, lockPageForVersioning, arg.WorkspaceID, arg.PageID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
