// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlcgen

import (
	"context"
	"time"
)

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT user_id, bio, avatar_url, status_message, updated_at FROM profiles
WHERE user_id = $1
`

// user_id でプロフィールを 1 件取得（無ければ usecase 側で空表示にフォールバック）。
func (q *Queries) GetProfileByUserID(ctx context.Context, userID int64) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.Bio,
		&i.AvatarUrl,
		&i.StatusMessage,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO profiles (user_id, bio, avatar_url, status_message, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id) DO UPDATE SET
  bio            = EXCLUDED.bio,
  avatar_url     = EXCLUDED.avatar_url,
  status_message = EXCLUDED.status_message,
  updated_at     = now()
RETURNING updated_at
`

type UpsertProfileParams struct {
	UserID        int64
	Bio           string
	AvatarUrl     string
	StatusMessage string
}

// user_id 単位のプロフィール upsert。GORM Save（PK=user_id の INSERT-or-UPDATE）を
// ON CONFLICT (user_id) DO UPDATE で置き換える。updated_at に DB 既定値は無いので
// （GORM autoUpdateTime 依存）now() をクエリ側で明示し、更新時も now() へ進める。
// RETURNING で updated_at を書き戻す（GORM Save 相当）。
func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, upsertProfile,
		arg.UserID,
		arg.Bio,
		arg.AvatarUrl,
		arg.StatusMessage,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
