// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getProject = `-- name: GetProject :one
SELECT id, workspace_id, key, name, created_at, updated_at FROM projects
WHERE workspace_id = $1 AND id = $2
`

type GetProjectParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// プロジェクト 1 件。別ワークスペースの ID はここで 0 行になる。
func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.WorkspaceID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, workspace_id, key, name, created_at, updated_at FROM projects
WHERE workspace_id = $1 AND lower("key") = $2
`

type GetProjectByKeyParams struct {
	WorkspaceID uuid.UUID
	Key         string
}

// 表示キーの接頭辞（小文字）からプロジェクトを引く。チケットのキー解決が使う。
func (q *Queries) GetProjectByKey(ctx context.Context, arg GetProjectByKeyParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByKey, arg.WorkspaceID, arg.Key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one

INSERT INTO projects (id, workspace_id, "key", name)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, key, name, created_at, updated_at
`

type InsertProjectParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Key         string
	Name        string
}

// プロジェクト（バックログの入れ物）のクエリ。
//
// projects はワークスペースだけを参照し、spaces（ナレッジの入れ物）とは関係を持たない
// （schema.hcl の projects のコメント参照）。作法は knowledge_base.sql と同じで、
// SELECT / UPDATE の WHERE には必ず workspace_id を含める（テナント越えをクエリで塞ぐ）。
// プロジェクトの作成。key はワークスペース内で一意（uq_projects_workspace_key）。
// key は表示キーの接頭辞（FRESTYLE-12 の FRESTYLE）になるので、作成後は変えない
// （改名は name だけ。UpdateProjectName 参照）。
func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, insertProject,
		arg.ID,
		arg.WorkspaceID,
		arg.Key,
		arg.Name,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, workspace_id, key, name, created_at, updated_at FROM projects
WHERE workspace_id = $1
ORDER BY created_at, id
`

// ワークスペース内のプロジェクト一覧。並びは作成順（採番の若い順に安定させる）。
func (q *Queries) ListProjects(ctx context.Context, workspaceID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Key,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectName = `-- name: UpdateProjectName :execrows
UPDATE projects SET name = $3, updated_at = now()
WHERE workspace_id = $1 AND id = $2
`

type UpdateProjectNameParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	Name        string
}

// 表示名だけを変える。key は表示キーの接頭辞なので触らない（変えると既存チケットの
// キーの見え方が全部変わり、外に貼られたキーが指す先を失う）。
func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProjectName, arg.WorkspaceID, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
