// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rich_document.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getRichDocumentByID = `-- name: GetRichDocumentByID :one
SELECT id, owner_id, company_id, kind, title, is_public, schema_version, doc, revision, created_at, updated_at, deleted_at
FROM rich_documents
WHERE id = $1 AND deleted_at IS NULL
`

// ID で 1 件引く（論理削除は除外）。無ければ sql.ErrNoRows。
// 誰が読めるか（テナント境界）は domain.RichDocument.CanBeReadBy が決めるので、ここでは
// 可視性条件を足さない（SQL 側へ写経すると片方だけ直したときに食い違う）。
func (q *Queries) GetRichDocumentByID(ctx context.Context, id uuid.UUID) (RichDocument, error) {
	row := q.db.QueryRowContext(ctx, getRichDocumentByID, id)
	var i RichDocument
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CompanyID,
		&i.Kind,
		&i.Title,
		&i.IsPublic,
		&i.SchemaVersion,
		&i.Doc,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertRichDocument = `-- name: InsertRichDocument :one
INSERT INTO rich_documents
  (id, owner_id, company_id, kind, title, is_public, schema_version, doc, revision, created_at, updated_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  COALESCE(NULLIF($7::bigint, 0), 1),
  $8,
  COALESCE(NULLIF($9::bigint, 0), 1),
  $10,
  $11
)
RETURNING schema_version, revision, created_at, updated_at
`

type InsertRichDocumentParams struct {
	ID            uuid.UUID
	OwnerID       int64
	CompanyID     sql.NullInt64
	Kind          string
	Title         string
	IsPublic      bool
	SchemaVersion int64
	Doc           json.RawMessage
	Revision      int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type InsertRichDocumentRow struct {
	SchemaVersion int64
	Revision      int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// 文書を 1 件作成する。id はアプリ採番の uuid なので明示的に渡す。
// created_at / updated_at は DB 既定値が無いため呼び出し側が値を渡す（autoTime 相当。
// ゼロなら呼び出し側で now() を入れる）。schema_version / revision は 0 のとき既定 1 を当てる
// （GORM の `default:1` タグと同じ挙動。RETURNING で確定値を書き戻す）。
func (q *Queries) InsertRichDocument(ctx context.Context, arg InsertRichDocumentParams) (InsertRichDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, insertRichDocument,
		arg.ID,
		arg.OwnerID,
		arg.CompanyID,
		arg.Kind,
		arg.Title,
		arg.IsPublic,
		arg.SchemaVersion,
		arg.Doc,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InsertRichDocumentRow
	err := row.Scan(
		&i.SchemaVersion,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRichDocumentsByOwner = `-- name: ListRichDocumentsByOwner :many
SELECT id, owner_id, company_id, kind, title, is_public, schema_version, revision, created_at, updated_at
FROM rich_documents
WHERE owner_id = $1
  AND deleted_at IS NULL
  AND ($2::text = '' OR kind = $2)
ORDER BY updated_at DESC, id DESC
`

type ListRichDocumentsByOwnerParams struct {
	OwnerID int64
	Kind    string
}

type ListRichDocumentsByOwnerRow struct {
	ID            uuid.UUID
	OwnerID       int64
	CompanyID     sql.NullInt64
	Kind          string
	Title         string
	IsPublic      bool
	SchemaVersion int64
	Revision      int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// owner の文書を更新日降順（同時刻は id 降順）で返す（論理削除は除外）。
// kind が空文字なら絞り込まない。一覧用途のため doc(jsonb) 本体は読み込まない（軽量サマリ）。
func (q *Queries) ListRichDocumentsByOwner(ctx context.Context, arg ListRichDocumentsByOwnerParams) ([]ListRichDocumentsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listRichDocumentsByOwner, arg.OwnerID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRichDocumentsByOwnerRow{}
	for rows.Next() {
		var i ListRichDocumentsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CompanyID,
			&i.Kind,
			&i.Title,
			&i.IsPublic,
			&i.SchemaVersion,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRichDocument = `-- name: SoftDeleteRichDocument :execrows
UPDATE rich_documents SET
  deleted_at = now()
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type SoftDeleteRichDocumentParams struct {
	ID      uuid.UUID
	OwnerID int64
}

// owner を条件に論理削除する（他人の文書は消せない）。RowsAffected=0 は対象なし（404）。
func (q *Queries) SoftDeleteRichDocument(ctx context.Context, arg SoftDeleteRichDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteRichDocument, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRichDocumentWithRevision = `-- name: UpdateRichDocumentWithRevision :one
UPDATE rich_documents SET
  title          = $1,
  is_public      = $2,
  schema_version = $3,
  doc            = $4,
  revision       = revision + 1,
  updated_at     = now()
WHERE id = $5 AND revision = $6 AND deleted_at IS NULL
RETURNING id, owner_id, company_id, kind, title, is_public, schema_version, doc, revision, created_at, updated_at, deleted_at
`

type UpdateRichDocumentWithRevisionParams struct {
	Title            string
	IsPublic         bool
	SchemaVersion    int64
	Doc              json.RawMessage
	ID               uuid.UUID
	ExpectedRevision int64
}

// 楽観ロック付き更新。expected_revision が現在値と一致し論理削除されていない行だけを更新し、
// revision を +1・updated_at を now() へ進める。0 行なら sql.ErrNoRows（呼び出し側が存在確認で
// 404 / 409 を切り分ける）。RETURNING で更新後の行全体を返し struct に反映する。
func (q *Queries) UpdateRichDocumentWithRevision(ctx context.Context, arg UpdateRichDocumentWithRevisionParams) (RichDocument, error) {
	row := q.db.QueryRowContext(ctx, updateRichDocumentWithRevision,
		arg.Title,
		arg.IsPublic,
		arg.SchemaVersion,
		arg.Doc,
		arg.ID,
		arg.ExpectedRevision,
	)
	var i RichDocument
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CompanyID,
		&i.Kind,
		&i.Title,
		&i.IsPublic,
		&i.SchemaVersion,
		&i.Doc,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
