// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_note.sql

package sqlcgen

import (
	"context"
)

const getSessionNoteBySessionID = `-- name: GetSessionNoteBySessionID :one
SELECT id, session_id, user_id, content, created_at, updated_at FROM session_notes
WHERE session_id = $1
`

// セッション ID でメモを 1 件取得（所有者検証は usecase 側）。
func (q *Queries) GetSessionNoteBySessionID(ctx context.Context, sessionID int64) (SessionNote, error) {
	row := q.db.QueryRowContext(ctx, getSessionNoteBySessionID, sessionID)
	var i SessionNote
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
