// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/norman6464/frestyle/backend/internal/adapter/persistence/pgtext"
)

const archiveTicket = `-- name: ArchiveTicket :execrows
UPDATE tickets
SET archived_at = now(), updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND archived_at IS NULL AND deleted_at IS NULL
`

type ArchiveTicketParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) ArchiveTicket(ctx context.Context, arg ArchiveTicketParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveTicket, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const archiveTicketStatus = `-- name: ArchiveTicketStatus :execrows
UPDATE ticket_statuses
SET archived_at = now(), updated_at = now()
WHERE workspace_id = $1 AND project_id = $2 AND id = $3 AND archived_at IS NULL
`

type ArchiveTicketStatusParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) ArchiveTicketStatus(ctx context.Context, arg ArchiveTicketStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveTicketStatus, arg.WorkspaceID, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const archiveTicketType = `-- name: ArchiveTicketType :execrows
UPDATE ticket_types
SET archived_at = now(), updated_at = now()
WHERE workspace_id = $1 AND project_id = $2 AND id = $3 AND archived_at IS NULL
`

type ArchiveTicketTypeParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) ArchiveTicketType(ctx context.Context, arg ArchiveTicketTypeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveTicketType, arg.WorkspaceID, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const attachTicketPathSubtree = `-- name: AttachTicketPathSubtree :exec
INSERT INTO ticket_paths (workspace_id, ticket_id, ancestor_id, depth)
SELECT sub.workspace_id, sub.ticket_id, sup.ancestor_id, sub.depth + sup.depth + 1
FROM ticket_paths sub
JOIN ticket_paths sup
  ON sup.workspace_id = sub.workspace_id AND sup.ticket_id = $1
WHERE sub.workspace_id = $2 AND sub.ancestor_id = $3
`

type AttachTicketPathSubtreeParams struct {
	NewParentID uuid.UUID
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
}

// 親の付け替え（後半）: 新しい親の祖先集合（親自身を含む）×サブツリー全員の直積を張る。
// 深さは「サブツリー内での深さ + 親までの深さ + 1」。ルートへ戻す付け替え（親なし）では
// このクエリは呼ばない（Detach だけで完結する）。呼び出し順は Detach → Attach 固定
// （逆にすると Attach で張った行を Detach が消してしまう。page_paths と同じ注意）。
func (q *Queries) AttachTicketPathSubtree(ctx context.Context, arg AttachTicketPathSubtreeParams) error {
	_, err := q.db.ExecContext(ctx, attachTicketPathSubtree, arg.NewParentID, arg.WorkspaceID, arg.TicketID)
	return err
}

const changeTicketStatus = `-- name: ChangeTicketStatus :one
UPDATE tickets
SET status_id = $3, closed_at = $4, resolution = $5, updated_at = now()
WHERE workspace_id = $1 AND id = $2
RETURNING id, workspace_id, project_id, number, type_id, status_id, parent_id, title, doc, plain_text, priority, story_points, team_id, start_date, due_date, closed_at, resolution, created_by_user_id, archived_at, deleted_at, created_at, updated_at
`

type ChangeTicketStatusParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	StatusID    uuid.UUID
	ClosedAt    sql.NullTime
	Resolution  sql.NullString
}

// closed_at / resolution は usecase が domain.ResolveTicketClosedFields で導出した値を
// そのまま渡す（ここでは category との整合を判断しない）。
// 並び順を返さない理由は UpdateTicket と同じ。
func (q *Queries) ChangeTicketStatus(ctx context.Context, arg ChangeTicketStatusParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, changeTicketStatus,
		arg.WorkspaceID,
		arg.ID,
		arg.StatusID,
		arg.ClosedAt,
		arg.Resolution,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Number,
		&i.TypeID,
		&i.StatusID,
		&i.ParentID,
		&i.Title,
		&i.Doc,
		&i.PlainText,
		&i.Priority,
		&i.StoryPoints,
		&i.TeamID,
		&i.StartDate,
		&i.DueDate,
		&i.ClosedAt,
		&i.Resolution,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearTicketStatusInitial = `-- name: ClearTicketStatusInitial :execrows
UPDATE ticket_statuses
SET is_initial = false, updated_at = now()
WHERE workspace_id = $1 AND project_id = $2 AND is_initial AND archived_at IS NULL
`

type ClearTicketStatusInitialParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
}

// SetInitialTicketStatus は「旧初期状態を先に false へ倒す → 新しい状態を true にする」の
// 2 文で、usecase が同一トランザクションで呼ぶ（部分 UNIQUE のため同時に 2 つは作れない。
// 旧初期状態が無いプロジェクトでは 0 行更新で構わない）。
func (q *Queries) ClearTicketStatusInitial(ctx context.Context, arg ClearTicketStatusInitialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearTicketStatusInitial, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearTicketTypeDefault = `-- name: ClearTicketTypeDefault :execrows
UPDATE ticket_types
SET is_default = false, updated_at = now()
WHERE workspace_id = $1 AND project_id = $2 AND is_default AND archived_at IS NULL
`

type ClearTicketTypeDefaultParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
}

func (q *Queries) ClearTicketTypeDefault(ctx context.Context, arg ClearTicketTypeDefaultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearTicketTypeDefault, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countActiveTicketChildren = `-- name: CountActiveTicketChildren :one
SELECT count(*) FROM tickets
WHERE workspace_id = $1 AND parent_id = $2 AND archived_at IS NULL
`

type CountActiveTicketChildrenParams struct {
	WorkspaceID uuid.UUID
	ParentID    uuid.NullUUID
}

func (q *Queries) CountActiveTicketChildren(ctx context.Context, arg CountActiveTicketChildrenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTicketChildren, arg.WorkspaceID, arg.ParentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveTicketsByStatus = `-- name: CountActiveTicketsByStatus :one
SELECT count(*) FROM tickets
WHERE workspace_id = $1 AND project_id = $2 AND status_id = $3 AND archived_at IS NULL
`

type CountActiveTicketsByStatusParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	StatusID    uuid.UUID
}

func (q *Queries) CountActiveTicketsByStatus(ctx context.Context, arg CountActiveTicketsByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTicketsByStatus, arg.WorkspaceID, arg.ProjectID, arg.StatusID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveTicketsByType = `-- name: CountActiveTicketsByType :one
SELECT count(*) FROM tickets
WHERE workspace_id = $1 AND project_id = $2 AND type_id = $3 AND archived_at IS NULL
`

type CountActiveTicketsByTypeParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	TypeID      uuid.UUID
}

func (q *Queries) CountActiveTicketsByType(ctx context.Context, arg CountActiveTicketsByTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTicketsByType, arg.WorkspaceID, arg.ProjectID, arg.TypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveTicketsGroupedByStatus = `-- name: CountActiveTicketsGroupedByStatus :many
SELECT status_id, count(*)::bigint AS count FROM tickets
WHERE workspace_id = $1 AND project_id = $2 AND archived_at IS NULL
GROUP BY status_id
`

type CountActiveTicketsGroupedByStatusParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
}

type CountActiveTicketsGroupedByStatusRow struct {
	StatusID uuid.UUID
	Count    int64
}

// 管理画面の「使用中 N 件」。状態 1 つずつ CountActiveTicketsByStatus を呼ぶと
// 状態の数だけ問い合わせが増えるので、スペース 1 回の GROUP BY でまとめて数える。
// 現役（archived_at IS NULL）だけを数えるのは、アーカイブ済みのチケットが
// 状態のアーカイブを妨げないため（usecase の 409 判定と同じ範囲に揃える）。
func (q *Queries) CountActiveTicketsGroupedByStatus(ctx context.Context, arg CountActiveTicketsGroupedByStatusParams) ([]CountActiveTicketsGroupedByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countActiveTicketsGroupedByStatus, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActiveTicketsGroupedByStatusRow{}
	for rows.Next() {
		var i CountActiveTicketsGroupedByStatusRow
		if err := rows.Scan(&i.StatusID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveTicketsGroupedByType = `-- name: CountActiveTicketsGroupedByType :many
SELECT type_id, count(*)::bigint AS count FROM tickets
WHERE workspace_id = $1 AND project_id = $2 AND archived_at IS NULL
GROUP BY type_id
`

type CountActiveTicketsGroupedByTypeParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
}

type CountActiveTicketsGroupedByTypeRow struct {
	TypeID uuid.UUID
	Count  int64
}

func (q *Queries) CountActiveTicketsGroupedByType(ctx context.Context, arg CountActiveTicketsGroupedByTypeParams) ([]CountActiveTicketsGroupedByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countActiveTicketsGroupedByType, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActiveTicketsGroupedByTypeRow{}
	for rows.Next() {
		var i CountActiveTicketsGroupedByTypeRow
		if err := rows.Scan(&i.TypeID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTicketWatchers = `-- name: CountTicketWatchers :one
SELECT count(*) FROM ticket_watchers WHERE workspace_id = $1 AND ticket_id = $2
`

type CountTicketWatchersParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
}

func (q *Queries) CountTicketWatchers(ctx context.Context, arg CountTicketWatchersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTicketWatchers, arg.WorkspaceID, arg.TicketID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTickets = `-- name: CountTickets :one
SELECT COUNT(*) FROM tickets t
LEFT JOIN ticket_assignments a ON a.workspace_id = t.workspace_id AND a.ticket_id = t.id
LEFT JOIN ticket_statuses s ON s.workspace_id = t.workspace_id AND s.id = t.status_id
WHERE t.workspace_id = $1 AND t.project_id = $2
  AND t.deleted_at IS NULL
  AND (t.archived_at IS NOT NULL) = $3::boolean
  AND ($4::uuid IS NULL OR t.status_id = $4::uuid)
  AND ($5::uuid IS NULL OR t.type_id = $5::uuid)
  AND (
    $6::uuid IS NULL
    OR a.assignee_principal_id = $6::uuid
  )
  AND (NOT $7::boolean OR a.assignee_principal_id IS NULL)
  AND (
    $8::uuid IS NULL
    OR a.assignee_principal_id = $8::uuid
  )
  AND (
    $9::uuid IS NULL
    OR EXISTS (
      SELECT 1 FROM ticket_labels tl
      WHERE tl.workspace_id = t.workspace_id AND tl.ticket_id = t.id AND tl.label_id = $9::uuid
    )
  )
  AND ($10::date IS NULL OR t.due_date <= $10::date)
  AND ($11::date IS NULL OR t.start_date >= $11::date)
  AND (NOT $12::boolean OR (t.due_date < CURRENT_DATE AND s.category <> 'done'))
  AND (
    $13::text IS NULL
    OR t.title ILIKE '%' || $13::text || '%'
    OR t.plain_text ILIKE '%' || $13::text || '%'
    OR word_similarity($13::text, t.title) > 0.6
    OR word_similarity($13::text, t.plain_text) > 0.6
  )
`

type CountTicketsParams struct {
	WorkspaceID             uuid.UUID
	ProjectID               uuid.UUID
	IncludeArchived         bool
	StatusID                uuid.NullUUID
	TypeID                  uuid.NullUUID
	AssigneePrincipalID     uuid.NullUUID
	Unassigned              bool
	AssignedToMePrincipalID uuid.NullUUID
	LabelID                 uuid.NullUUID
	DueBefore               pgtext.NullDate
	StartAfter              pgtext.NullDate
	Overdue                 bool
	Q                       sql.NullString
}

// 利用者が保存した絞り込み（ticket_saved_filters）の件数バッジ用。ListTickets と同じ条件に
// 合う行を数える。sqlc は SQL の断片を共有できないので WHERE は ListTickets をそのまま写して
// ある — ListTickets の条件を変えるときはここも同じに保つこと。ずれは結合テスト
// （TestTicketRepository_CountTickets_Integration: CountTickets は ListTickets の件数と一致する）
// が捕まえる。並び順の JOIN（ticket_backlog_ranks）は数えるだけなので要らない。
func (q *Queries) CountTickets(ctx context.Context, arg CountTicketsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTickets,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.IncludeArchived,
		arg.StatusID,
		arg.TypeID,
		arg.AssigneePrincipalID,
		arg.Unassigned,
		arg.AssignedToMePrincipalID,
		arg.LabelID,
		arg.DueBefore,
		arg.StartAfter,
		arg.Overdue,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :one

WITH n AS (
  INSERT INTO ticket_counters (workspace_id, project_id, last_number, updated_at)
  VALUES ($2, $3, 1, now())
  ON CONFLICT (workspace_id, project_id)
  DO UPDATE SET last_number = ticket_counters.last_number + 1, updated_at = now()
  RETURNING last_number
)
INSERT INTO tickets
  (id, workspace_id, project_id, number, type_id, status_id, parent_id, title, doc, plain_text,
   priority, start_date, due_date, created_by_user_id, created_at, updated_at)
SELECT
  $1, $2, $3, n.last_number,
  $4, $5, $6, $7,
  $8, $9, $10,
  $11::date, $12::date,
  $13, now(), now()
FROM n
RETURNING id, workspace_id, project_id, number, type_id, status_id, parent_id, title, doc, plain_text, priority, story_points, team_id, start_date, due_date, closed_at, resolution, created_by_user_id, archived_at, deleted_at, created_at, updated_at
`

type CreateTicketParams struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	ProjectID       uuid.UUID
	TypeID          uuid.UUID
	StatusID        uuid.UUID
	ParentID        uuid.NullUUID
	Title           string
	Doc             json.RawMessage
	PlainText       string
	Priority        int32
	StartDate       pgtext.NullDate
	DueDate         pgtext.NullDate
	CreatedByUserID int64
}

// =============================================================================
// tickets 本体
// =============================================================================
// 採番と INSERT を 1 文の CTE にまとめる（設計 Ⅳ-B）。本番の transaction pooler 越しでも
// 接続が同じであることが保証され、行ロックで直列化される（20 並行で番号が連続することを
// 実機で確認済み）。VALUES に 1 を渡すのは初回の初期化（ON CONFLICT で 2 回目以降は +1）。
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, createTicket,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TypeID,
		arg.StatusID,
		arg.ParentID,
		arg.Title,
		arg.Doc,
		arg.PlainText,
		arg.Priority,
		arg.StartDate,
		arg.DueDate,
		arg.CreatedByUserID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Number,
		&i.TypeID,
		&i.StatusID,
		&i.ParentID,
		&i.Title,
		&i.Doc,
		&i.PlainText,
		&i.Priority,
		&i.StoryPoints,
		&i.TeamID,
		&i.StartDate,
		&i.DueDate,
		&i.ClosedAt,
		&i.Resolution,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :execrows
UPDATE tickets
SET deleted_at = now(), updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NULL
`

type DeleteTicketParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// 「消えたことにする」（設計 Ⅳ-J）。archived_at と独立の列で、戻す口は
// RestoreDeletedTicket だけ（一覧・検索・URL 直打ちのどこにも出てこなくなる）。
// 既に削除済みなら 0 行（呼び出し側は ErrTicketNotFound に畳む。冪等な 404）。
func (q *Queries) DeleteTicket(ctx context.Context, arg DeleteTicketParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTicket, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTicketAssignment = `-- name: DeleteTicketAssignment :execrows
DELETE FROM ticket_assignments
WHERE workspace_id = $1 AND ticket_id = $2
`

type DeleteTicketAssignmentParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
}

func (q *Queries) DeleteTicketAssignment(ctx context.Context, arg DeleteTicketAssignmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTicketAssignment, arg.WorkspaceID, arg.TicketID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTicketPageLinksBySource = `-- name: DeleteTicketPageLinksBySource :exec

DELETE FROM ticket_page_links
WHERE workspace_id = $1 AND source_ticket_id = $2
`

type DeleteTicketPageLinksBySourceParams struct {
	WorkspaceID    uuid.UUID
	SourceTicketID uuid.UUID
}

// =============================================================================
// ticket_page_links / ticket_ticket_links（派生表）
// =============================================================================
func (q *Queries) DeleteTicketPageLinksBySource(ctx context.Context, arg DeleteTicketPageLinksBySourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteTicketPageLinksBySource, arg.WorkspaceID, arg.SourceTicketID)
	return err
}

const deleteTicketPageLinksBySourceCascade = `-- name: DeleteTicketPageLinksBySourceCascade :exec
UPDATE ticket_page_links
SET deleted_at = now()
WHERE workspace_id = $1 AND source_ticket_id = $2 AND deleted_at IS NULL
`

type DeleteTicketPageLinksBySourceCascadeParams struct {
	WorkspaceID    uuid.UUID
	SourceTicketID uuid.UUID
}

// チケット削除時、その本文からの参照（派生索引）も一緒に「消えたことにする」。
// 物理削除しないのは、DeleteTicketPageLinksBySource（本文保存時の張り替え）と役割が違うため
// — こちらは「参照元が消えたので隠す」、あちらは「本文が変わったので作り直す」。
func (q *Queries) DeleteTicketPageLinksBySourceCascade(ctx context.Context, arg DeleteTicketPageLinksBySourceCascadeParams) error {
	_, err := q.db.ExecContext(ctx, deleteTicketPageLinksBySourceCascade, arg.WorkspaceID, arg.SourceTicketID)
	return err
}

const deleteTicketTicketLinksBySource = `-- name: DeleteTicketTicketLinksBySource :exec
DELETE FROM ticket_ticket_links
WHERE workspace_id = $1 AND source_ticket_id = $2
`

type DeleteTicketTicketLinksBySourceParams struct {
	WorkspaceID    uuid.UUID
	SourceTicketID uuid.UUID
}

func (q *Queries) DeleteTicketTicketLinksBySource(ctx context.Context, arg DeleteTicketTicketLinksBySourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteTicketTicketLinksBySource, arg.WorkspaceID, arg.SourceTicketID)
	return err
}

const deleteTicketTicketLinksBySourceCascade = `-- name: DeleteTicketTicketLinksBySourceCascade :exec
UPDATE ticket_ticket_links
SET deleted_at = now()
WHERE workspace_id = $1 AND source_ticket_id = $2 AND deleted_at IS NULL
`

type DeleteTicketTicketLinksBySourceCascadeParams struct {
	WorkspaceID    uuid.UUID
	SourceTicketID uuid.UUID
}

func (q *Queries) DeleteTicketTicketLinksBySourceCascade(ctx context.Context, arg DeleteTicketTicketLinksBySourceCascadeParams) error {
	_, err := q.db.ExecContext(ctx, deleteTicketTicketLinksBySourceCascade, arg.WorkspaceID, arg.SourceTicketID)
	return err
}

const deleteTicketWatcher = `-- name: DeleteTicketWatcher :execrows
DELETE FROM ticket_watchers WHERE workspace_id = $1 AND ticket_id = $2 AND user_id = $3
`

type DeleteTicketWatcherParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
	UserID      int64
}

func (q *Queries) DeleteTicketWatcher(ctx context.Context, arg DeleteTicketWatcherParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTicketWatcher, arg.WorkspaceID, arg.TicketID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const detachTicketPathSubtree = `-- name: DetachTicketPathSubtree :exec
DELETE FROM ticket_paths
WHERE ticket_paths.workspace_id = $1
  AND ticket_paths.ticket_id IN (
      SELECT tp.ticket_id FROM ticket_paths tp
      WHERE tp.workspace_id = $1 AND tp.ancestor_id = $2
  )
  AND ticket_paths.ancestor_id NOT IN (
      SELECT tp.ticket_id FROM ticket_paths tp
      WHERE tp.workspace_id = $1 AND tp.ancestor_id = $2
  )
`

type DetachTicketPathSubtreeParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
}

// 親の付け替え（前半）: サブツリー内の各チケットと「サブツリー外の祖先」との組を消す。
// サブツリー内部同士の組（自己参照 depth=0 を含む）は付け替え後も変わらないため残す。
// page_paths の DetachPageSubtreePaths と同じ形（doc 参照）。
func (q *Queries) DetachTicketPathSubtree(ctx context.Context, arg DetachTicketPathSubtreeParams) error {
	_, err := q.db.ExecContext(ctx, detachTicketPathSubtree, arg.WorkspaceID, arg.TicketID)
	return err
}

const findDeletedTicket = `-- name: FindDeletedTicket :one
SELECT id, workspace_id, project_id, number, type_id, status_id, parent_id, title, doc, plain_text, priority, story_points, team_id, start_date, due_date, closed_at, resolution, created_by_user_id, archived_at, deleted_at, created_at, updated_at FROM tickets
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NOT NULL
`

type FindDeletedTicketParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// RestoreDeletedTicketUseCase 専用。GetTicket と逆に、削除済み（deleted_at IS NOT NULL）の
// 行だけを引く（現役の行は見えない — Archive/Restore の archived_at と対称の作法）。
func (q *Queries) FindDeletedTicket(ctx context.Context, arg FindDeletedTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, findDeletedTicket, arg.WorkspaceID, arg.ID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Number,
		&i.TypeID,
		&i.StatusID,
		&i.ParentID,
		&i.Title,
		&i.Doc,
		&i.PlainText,
		&i.Priority,
		&i.StoryPoints,
		&i.TeamID,
		&i.StartDate,
		&i.DueDate,
		&i.ClosedAt,
		&i.Resolution,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultTicketType = `-- name: GetDefaultTicketType :one
SELECT id, workspace_id, project_id, name, name_lower, color, hierarchy_level, position, is_default, template_title, template_doc, archived_at, deleted_at, created_at, updated_at FROM ticket_types
WHERE workspace_id = $1 AND project_id = $2 AND is_default AND archived_at IS NULL
`

type GetDefaultTicketTypeParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
}

func (q *Queries) GetDefaultTicketType(ctx context.Context, arg GetDefaultTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRowContext(ctx, getDefaultTicketType, arg.WorkspaceID, arg.ProjectID)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.NameLower,
		&i.Color,
		&i.HierarchyLevel,
		&i.Position,
		&i.IsDefault,
		&i.TemplateTitle,
		&i.TemplateDoc,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInitialTicketStatus = `-- name: GetInitialTicketStatus :one
SELECT id, workspace_id, project_id, name, name_lower, category, color, position, is_initial, archived_at, deleted_at, created_at, updated_at FROM ticket_statuses
WHERE workspace_id = $1 AND project_id = $2 AND is_initial AND archived_at IS NULL
`

type GetInitialTicketStatusParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
}

func (q *Queries) GetInitialTicketStatus(ctx context.Context, arg GetInitialTicketStatusParams) (TicketStatus, error) {
	row := q.db.QueryRowContext(ctx, getInitialTicketStatus, arg.WorkspaceID, arg.ProjectID)
	var i TicketStatus
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.NameLower,
		&i.Category,
		&i.Color,
		&i.Position,
		&i.IsInitial,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT t.id, t.workspace_id, t.project_id, t.number, t.type_id, t.status_id, t.parent_id, t.title, t.doc, t.plain_text, t.priority, t.story_points, t.team_id, t.start_date, t.due_date, t.closed_at, t.resolution, t.created_by_user_id, t.archived_at, t.deleted_at, t.created_at, t.updated_at, a.assignee_principal_id, COALESCE(r."position", '')::text AS rank_position FROM tickets t
LEFT JOIN ticket_backlog_ranks r ON r.workspace_id = t.workspace_id AND r.ticket_id = t.id
LEFT JOIN ticket_assignments a ON a.workspace_id = t.workspace_id AND a.ticket_id = t.id
WHERE t.workspace_id = $1 AND t.id = $2 AND t.deleted_at IS NULL
`

type GetTicketParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type GetTicketRow struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	ProjectID           uuid.UUID
	Number              int64
	TypeID              uuid.UUID
	StatusID            uuid.UUID
	ParentID            uuid.NullUUID
	Title               string
	Doc                 json.RawMessage
	PlainText           string
	Priority            int32
	StoryPoints         sql.NullInt32
	TeamID              uuid.NullUUID
	StartDate           pgtext.NullDate
	DueDate             pgtext.NullDate
	ClosedAt            sql.NullTime
	Resolution          sql.NullString
	CreatedByUserID     int64
	ArchivedAt          sql.NullTime
	DeletedAt           sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
	AssigneePrincipalID uuid.NullUUID
	RankPosition        string
}

// 担当（ticket_assignments）を LEFT JOIN で添える。画面は詳細でも一覧でも担当を出すので、
// チケット 1 件につき問い合わせを 2 回に分けない（設計 Ⅶ の「詳細（… 担当 …）」）。
// 担当は 1 人（ticket_id が PK）なので、この JOIN で行が増えることはない。
//
// ticket_backlog_ranks を LEFT JOIN して並び順を rank_position として添える。並び順の正本は
// この表だけで、tickets.position 列は撤去済み。
//
// INNER JOIN にはしない。並び順の行が無いだけでチケットが「無い」と誤認され、画面から
// 黙って消えるため（旧 ticket_ranks で実際に起きた壊れ方がこれ）。行が無ければ
// rank_position は空文字になり、一覧では末尾に回る —— 消えるのではなく目に見える形で残す。
//
// deleted_at IS NOT NULL のチケットは「無い」と同じ扱いにする（設計 Ⅳ-J: 消えたことにする。
// archived_at と違い戻す口を持たない）。削除済みチケットを個別に引く経路は
// FindDeletedTicket に分けてある（RestoreDeletedTicketUseCase 専用）。
func (q *Queries) GetTicket(ctx context.Context, arg GetTicketParams) (GetTicketRow, error) {
	row := q.db.QueryRowContext(ctx, getTicket, arg.WorkspaceID, arg.ID)
	var i GetTicketRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Number,
		&i.TypeID,
		&i.StatusID,
		&i.ParentID,
		&i.Title,
		&i.Doc,
		&i.PlainText,
		&i.Priority,
		&i.StoryPoints,
		&i.TeamID,
		&i.StartDate,
		&i.DueDate,
		&i.ClosedAt,
		&i.Resolution,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssigneePrincipalID,
		&i.RankPosition,
	)
	return i, err
}

const getTicketAcrossWorkspaces = `-- name: GetTicketAcrossWorkspaces :one
SELECT id, workspace_id, project_id FROM tickets
WHERE id = $1
`

type GetTicketAcrossWorkspacesRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
}

// チケットを **ID だけ** で引く。/kb/tickets/{ticketId} の URL からワークスペースを
// 特定するための、このファイルで唯一 workspace_id を WHERE に持たない読み取り
// （knowledge_base.sql の GetPageAcrossWorkspaces と同じ役割・同じ作法）。
// 引いた直後に必ずその workspace の権限判定を通すこと（判定なしで応答に使わない）。
// id は uuid の主キーで全テナント一意なので、これ自体が越境にはならない。
func (q *Queries) GetTicketAcrossWorkspaces(ctx context.Context, id uuid.UUID) (GetTicketAcrossWorkspacesRow, error) {
	row := q.db.QueryRowContext(ctx, getTicketAcrossWorkspaces, id)
	var i GetTicketAcrossWorkspacesRow
	err := row.Scan(&i.ID, &i.WorkspaceID, &i.ProjectID)
	return i, err
}

const getTicketAssignment = `-- name: GetTicketAssignment :one
SELECT workspace_id, ticket_id, assignee_principal_id, assignee_kind, assigned_by_user_id, created_at, deleted_at FROM ticket_assignments
WHERE workspace_id = $1 AND ticket_id = $2
`

type GetTicketAssignmentParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
}

func (q *Queries) GetTicketAssignment(ctx context.Context, arg GetTicketAssignmentParams) (TicketAssignment, error) {
	row := q.db.QueryRowContext(ctx, getTicketAssignment, arg.WorkspaceID, arg.TicketID)
	var i TicketAssignment
	err := row.Scan(
		&i.WorkspaceID,
		&i.TicketID,
		&i.AssigneePrincipalID,
		&i.AssigneeKind,
		&i.AssignedByUserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTicketCounts = `-- name: GetTicketCounts :one
SELECT
  COUNT(*) AS total,
  COUNT(*) FILTER (
    WHERE $1::uuid IS NOT NULL AND a.assignee_principal_id = $1::uuid
  ) AS assigned_to_me,
  COUNT(*) FILTER (WHERE t.due_date < CURRENT_DATE AND s.category <> 'done') AS overdue,
  COUNT(*) FILTER (WHERE a.assignee_principal_id IS NULL) AS unassigned
FROM tickets t
LEFT JOIN ticket_assignments a ON a.workspace_id = t.workspace_id AND a.ticket_id = t.id
LEFT JOIN ticket_statuses s ON s.workspace_id = t.workspace_id AND s.id = t.status_id
WHERE t.workspace_id = $2 AND t.project_id = $3
  AND t.archived_at IS NULL AND t.deleted_at IS NULL
`

type GetTicketCountsParams struct {
	MyPrincipalID uuid.NullUUID
	WorkspaceID   uuid.UUID
	ProjectID     uuid.UUID
}

type GetTicketCountsRow struct {
	Total        int64
	AssignedToMe int64
	Overdue      int64
	Unassigned   int64
}

// バックログのサイドバー「保存した絞り込み」が使う件数の集計（段 5）。1 クエリの
// FILTER で 4 通りをまとめて数える（4 回に分けて問い合わせると往復が増えるだけで
// 対象行の集合はどれも同じ WHERE の前段を共有するため）。
// my_principal_id は呼び出し側（handler）が principals から先に引いて渡す
// （kind='user' の principal が無い＝そのワークスペースに所属していない相手からは
// そもそもこの経路に来ない。ミドルウェアが弾く）。
func (q *Queries) GetTicketCounts(ctx context.Context, arg GetTicketCountsParams) (GetTicketCountsRow, error) {
	row := q.db.QueryRowContext(ctx, getTicketCounts, arg.MyPrincipalID, arg.WorkspaceID, arg.ProjectID)
	var i GetTicketCountsRow
	err := row.Scan(
		&i.Total,
		&i.AssignedToMe,
		&i.Overdue,
		&i.Unassigned,
	)
	return i, err
}

const getTicketForUpdate = `-- name: GetTicketForUpdate :one
SELECT id, workspace_id, project_id, number, type_id, status_id, parent_id, title, doc, plain_text, priority, story_points, team_id, start_date, due_date, closed_at, resolution, created_by_user_id, archived_at, deleted_at, created_at, updated_at FROM tickets
WHERE workspace_id = $1 AND id = $2
FOR UPDATE
`

type GetTicketForUpdateParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// 状態変更・親子変更・順位変更の直前にロックする。
func (q *Queries) GetTicketForUpdate(ctx context.Context, arg GetTicketForUpdateParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketForUpdate, arg.WorkspaceID, arg.ID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Number,
		&i.TypeID,
		&i.StatusID,
		&i.ParentID,
		&i.Title,
		&i.Doc,
		&i.PlainText,
		&i.Priority,
		&i.StoryPoints,
		&i.TeamID,
		&i.StartDate,
		&i.DueDate,
		&i.ClosedAt,
		&i.Resolution,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketStatus = `-- name: GetTicketStatus :one
SELECT id, workspace_id, project_id, name, name_lower, category, color, position, is_initial, archived_at, deleted_at, created_at, updated_at FROM ticket_statuses
WHERE workspace_id = $1 AND project_id = $2 AND id = $3
`

type GetTicketStatusParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetTicketStatus(ctx context.Context, arg GetTicketStatusParams) (TicketStatus, error) {
	row := q.db.QueryRowContext(ctx, getTicketStatus, arg.WorkspaceID, arg.ProjectID, arg.ID)
	var i TicketStatus
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.NameLower,
		&i.Category,
		&i.Color,
		&i.Position,
		&i.IsInitial,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketType = `-- name: GetTicketType :one
SELECT id, workspace_id, project_id, name, name_lower, color, hierarchy_level, position, is_default, template_title, template_doc, archived_at, deleted_at, created_at, updated_at FROM ticket_types
WHERE workspace_id = $1 AND project_id = $2 AND id = $3
`

type GetTicketTypeParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetTicketType(ctx context.Context, arg GetTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRowContext(ctx, getTicketType, arg.WorkspaceID, arg.ProjectID, arg.ID)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.NameLower,
		&i.Color,
		&i.HierarchyLevel,
		&i.Position,
		&i.IsDefault,
		&i.TemplateTitle,
		&i.TemplateDoc,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveInitialTicketStatus = `-- name: HasActiveInitialTicketStatus :one


SELECT EXISTS (
  SELECT 1 FROM ticket_statuses
  WHERE workspace_id = $1 AND project_id = $2
    AND is_initial AND archived_at IS NULL
) AS exists
`

type HasActiveInitialTicketStatusParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
}

// チケット（段 1: 骨格）のクエリ。knowledge_base.sql と同じ作法。
//
// 作法（このファイル全体の前提）:
//   - すべての SELECT / UPDATE / DELETE の WHERE に workspace_id を含める。
//   - UPDATE 文には必ず updated_at = now() を明示する。
//   - position（COLLATE "C"）の ORDER BY はバイト順（fracindex と一致）。
//   - tickets への INSERT は CreateTicket 1 本だけ（採番 CTE を含む文でなければ番号が
//     ticket_counters と無関係に振られてしまう。設計 Ⅳ-B のレビュー項目）。
//
// =============================================================================
// ticket_statuses（管理画面）
// =============================================================================
// 「有効化済み」の正本判定: 初期状態を持つ現役の状態が 1 つでもあるか。
func (q *Queries) HasActiveInitialTicketStatus(ctx context.Context, arg HasActiveInitialTicketStatusParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveInitialTicketStatus, arg.WorkspaceID, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertTicketBacklogRank = `-- name: InsertTicketBacklogRank :exec

INSERT INTO ticket_backlog_ranks (workspace_id, project_id, ticket_id, "position", created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
`

type InsertTicketBacklogRankParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	TicketID    uuid.UUID
	Position    string
}

// =============================================================================
// ticket_backlog_ranks（バックログの並び順。設計 Ⅳ-F）
// =============================================================================
// CreateTicket 成功直後に usecase が呼ぶ（tickets への INSERT とは別文。設計 Ⅳ-B の
// 「tickets への INSERT は 1 本だけ」という縛りはこの表には及ばない）。
// project_id を明示的に受け取る —— 並びの範囲がプロジェクトであることを、表の側にも
// 書き込むため（旧 ticket_ranks はこれを持たず、一意制約が表全体に効いていた）。
func (q *Queries) InsertTicketBacklogRank(ctx context.Context, arg InsertTicketBacklogRankParams) error {
	_, err := q.db.ExecContext(ctx, insertTicketBacklogRank,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TicketID,
		arg.Position,
	)
	return err
}

const insertTicketChangeGroup = `-- name: InsertTicketChangeGroup :one

INSERT INTO ticket_change_groups (id, workspace_id, ticket_id, actor_user_id, created_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, workspace_id, ticket_id, actor_user_id, created_at, deleted_at
`

type InsertTicketChangeGroupParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
	ActorUserID int64
}

// =============================================================================
// ticket_change_groups / ticket_change_items
// =============================================================================
func (q *Queries) InsertTicketChangeGroup(ctx context.Context, arg InsertTicketChangeGroupParams) (TicketChangeGroup, error) {
	row := q.db.QueryRowContext(ctx, insertTicketChangeGroup,
		arg.ID,
		arg.WorkspaceID,
		arg.TicketID,
		arg.ActorUserID,
	)
	var i TicketChangeGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TicketID,
		&i.ActorUserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertTicketChangeItem = `-- name: InsertTicketChangeItem :exec
INSERT INTO ticket_change_items
  (id, workspace_id, group_id, field, old_value, new_value, old_label, new_label)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertTicketChangeItemParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	GroupID     uuid.UUID
	Field       string
	OldValue    sql.NullString
	NewValue    sql.NullString
	OldLabel    sql.NullString
	NewLabel    sql.NullString
}

func (q *Queries) InsertTicketChangeItem(ctx context.Context, arg InsertTicketChangeItemParams) error {
	_, err := q.db.ExecContext(ctx, insertTicketChangeItem,
		arg.ID,
		arg.WorkspaceID,
		arg.GroupID,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
		arg.OldLabel,
		arg.NewLabel,
	)
	return err
}

const insertTicketPageLink = `-- name: InsertTicketPageLink :exec
INSERT INTO ticket_page_links (workspace_id, source_ticket_id, target_page_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertTicketPageLinkParams struct {
	WorkspaceID    uuid.UUID
	SourceTicketID uuid.UUID
	TargetPageID   uuid.UUID
}

func (q *Queries) InsertTicketPageLink(ctx context.Context, arg InsertTicketPageLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertTicketPageLink, arg.WorkspaceID, arg.SourceTicketID, arg.TargetPageID)
	return err
}

const insertTicketPathAncestors = `-- name: InsertTicketPathAncestors :exec
INSERT INTO ticket_paths (workspace_id, ticket_id, ancestor_id, depth)
SELECT tp.workspace_id, $1::uuid, tp.ancestor_id, tp.depth + 1
FROM ticket_paths tp
WHERE tp.workspace_id = $2 AND tp.ticket_id = $3
`

type InsertTicketPathAncestorsParams struct {
	TicketID    uuid.UUID
	WorkspaceID uuid.UUID
	ParentID    uuid.UUID
}

// チケット作成時に親の祖先集合（親自身 depth=0 を含む）を +1 して引き継ぐ。
func (q *Queries) InsertTicketPathAncestors(ctx context.Context, arg InsertTicketPathAncestorsParams) error {
	_, err := q.db.ExecContext(ctx, insertTicketPathAncestors, arg.TicketID, arg.WorkspaceID, arg.ParentID)
	return err
}

const insertTicketPathSelf = `-- name: InsertTicketPathSelf :exec

INSERT INTO ticket_paths (workspace_id, ticket_id, ancestor_id, depth)
VALUES ($1, $2, $2, 0)
`

type InsertTicketPathSelfParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
}

// =============================================================================
// ticket_paths（段 5: parent_id の閉包表。page_paths と同じ設計・同じ作法）
// =============================================================================
// closure の自己参照行（depth=0）。チケット作成と同じタイミングで張る。
func (q *Queries) InsertTicketPathSelf(ctx context.Context, arg InsertTicketPathSelfParams) error {
	_, err := q.db.ExecContext(ctx, insertTicketPathSelf, arg.WorkspaceID, arg.TicketID)
	return err
}

const insertTicketStatus = `-- name: InsertTicketStatus :one
INSERT INTO ticket_statuses
  (id, workspace_id, project_id, name, category, color, "position", is_initial, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now(), now())
RETURNING id, workspace_id, project_id, name, name_lower, category, color, position, is_initial, archived_at, deleted_at, created_at, updated_at
`

type InsertTicketStatusParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Category    string
	Color       string
	Position    string
	IsInitial   bool
}

func (q *Queries) InsertTicketStatus(ctx context.Context, arg InsertTicketStatusParams) (TicketStatus, error) {
	row := q.db.QueryRowContext(ctx, insertTicketStatus,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Name,
		arg.Category,
		arg.Color,
		arg.Position,
		arg.IsInitial,
	)
	var i TicketStatus
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.NameLower,
		&i.Category,
		&i.Color,
		&i.Position,
		&i.IsInitial,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTicketTicketLink = `-- name: InsertTicketTicketLink :exec
INSERT INTO ticket_ticket_links (workspace_id, source_ticket_id, target_ticket_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertTicketTicketLinkParams struct {
	WorkspaceID    uuid.UUID
	SourceTicketID uuid.UUID
	TargetTicketID uuid.UUID
}

func (q *Queries) InsertTicketTicketLink(ctx context.Context, arg InsertTicketTicketLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertTicketTicketLink, arg.WorkspaceID, arg.SourceTicketID, arg.TargetTicketID)
	return err
}

const insertTicketType = `-- name: InsertTicketType :one

INSERT INTO ticket_types
  (id, workspace_id, project_id, name, color, hierarchy_level, "position", is_default,
   template_title, template_doc, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now(), now())
RETURNING id, workspace_id, project_id, name, name_lower, color, hierarchy_level, position, is_default, template_title, template_doc, archived_at, deleted_at, created_at, updated_at
`

type InsertTicketTypeParams struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ProjectID      uuid.UUID
	Name           string
	Color          string
	HierarchyLevel int32
	Position       string
	IsDefault      bool
	TemplateTitle  sql.NullString
	TemplateDoc    *json.RawMessage
}

// =============================================================================
// ticket_types（管理画面）
// =============================================================================
func (q *Queries) InsertTicketType(ctx context.Context, arg InsertTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRowContext(ctx, insertTicketType,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Name,
		arg.Color,
		arg.HierarchyLevel,
		arg.Position,
		arg.IsDefault,
		arg.TemplateTitle,
		arg.TemplateDoc,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.NameLower,
		&i.Color,
		&i.HierarchyLevel,
		&i.Position,
		&i.IsDefault,
		&i.TemplateTitle,
		&i.TemplateDoc,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTicketWatcher = `-- name: InsertTicketWatcher :exec

INSERT INTO ticket_watchers (workspace_id, ticket_id, user_id, created_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (workspace_id, ticket_id, user_id) DO NOTHING
`

type InsertTicketWatcherParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
	UserID      int64
}

// =============================================================================
// ticket_watchers
// =============================================================================
// 二重に押しても落とさない（PK 衝突は「もう監視している」なので、成功と同じ扱いでよい）。
func (q *Queries) InsertTicketWatcher(ctx context.Context, arg InsertTicketWatcherParams) error {
	_, err := q.db.ExecContext(ctx, insertTicketWatcher, arg.WorkspaceID, arg.TicketID, arg.UserID)
	return err
}

const isTicketWatchedBy = `-- name: IsTicketWatchedBy :one
SELECT EXISTS (
  SELECT 1 FROM ticket_watchers
  WHERE workspace_id = $1 AND ticket_id = $2 AND user_id = $3
) AS watching
`

type IsTicketWatchedByParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
	UserID      int64
}

func (q *Queries) IsTicketWatchedBy(ctx context.Context, arg IsTicketWatchedByParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTicketWatchedBy, arg.WorkspaceID, arg.TicketID, arg.UserID)
	var watching bool
	err := row.Scan(&watching)
	return watching, err
}

const lastActiveTicketStatusPosition = `-- name: LastActiveTicketStatusPosition :one
SELECT COALESCE(max("position"), '')::text AS "position" FROM ticket_statuses
WHERE workspace_id = $1 AND project_id = $2 AND archived_at IS NULL
`

type LastActiveTicketStatusPositionParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
}

// 現役の状態のうち最後（position 最大）のもの。復元・新規作成の末尾採番に使う。
// 1 件も無ければ空文字（sqlc は :one で 0 行だと sql.ErrNoRows を返すため、
// COALESCE で空文字に畳んで「0 行エラー」を避ける）。
func (q *Queries) LastActiveTicketStatusPosition(ctx context.Context, arg LastActiveTicketStatusPositionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, lastActiveTicketStatusPosition, arg.WorkspaceID, arg.ProjectID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const lastActiveTicketTypePosition = `-- name: LastActiveTicketTypePosition :one
SELECT COALESCE(max("position"), '')::text AS "position" FROM ticket_types
WHERE workspace_id = $1 AND project_id = $2 AND archived_at IS NULL
`

type LastActiveTicketTypePositionParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
}

func (q *Queries) LastActiveTicketTypePosition(ctx context.Context, arg LastActiveTicketTypePositionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, lastActiveTicketTypePosition, arg.WorkspaceID, arg.ProjectID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const lastTicketBacklogRankPosition = `-- name: LastTicketBacklogRankPosition :one
SELECT COALESCE(max("position"), '')::text AS "position"
FROM ticket_backlog_ranks
WHERE workspace_id = $1 AND project_id = $2
`

type LastTicketBacklogRankPositionParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
}

// 末尾へ足すときの「いま一番後ろの鍵」。表が project_id を持つので、対象プロジェクトの
// 絞り込みに tickets への JOIN は要らない。
//
// **現役の行だけに絞ってはいけない。** 一意制約は表の行すべてに効くので、アーカイブ済み・
// 削除済みの行を無視して最大値を取ると、その鍵を後から作り直して重複で落ちる
// （末尾のチケットを 1 件アーカイブしてから新しく作ると必ず踏む）。
// 見えない行も含めて「一番後ろ」を取ることが、採番が衝突しない条件そのもの。
func (q *Queries) LastTicketBacklogRankPosition(ctx context.Context, arg LastTicketBacklogRankPositionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, lastTicketBacklogRankPosition, arg.WorkspaceID, arg.ProjectID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const listAssignedTicketsAcrossWorkspaces = `-- name: ListAssignedTicketsAcrossWorkspaces :many
SELECT
  t.id,
  t.project_id,
  t.number,
  t.title,
  t.priority,
  t.due_date,
  t.created_at,
  w.slug AS workspace_slug,
  w.name AS workspace_name,
  p.key AS project_key,
  p.name AS project_name,
  s.name AS status_name,
  s.category AS status_category,
  s.color AS status_color,
  ty.name AS type_name
FROM tickets t
JOIN principals me
  ON me.workspace_id = t.workspace_id AND me.kind = 'user' AND me.user_id = $1
JOIN ticket_assignments a
  ON a.workspace_id = t.workspace_id AND a.ticket_id = t.id AND a.assignee_principal_id = me.id
JOIN workspaces w
  ON w.id = t.workspace_id
JOIN projects p
  ON p.id = t.project_id
JOIN ticket_statuses s
  ON s.workspace_id = t.workspace_id AND s.id = t.status_id
JOIN ticket_types ty
  ON ty.workspace_id = t.workspace_id AND ty.id = t.type_id
WHERE t.workspace_id IN (
    SELECT value::uuid FROM json_array_elements_text($2::json) AS v(value)
  )
  AND s.category <> 'done'
  AND t.archived_at IS NULL
  AND t.deleted_at IS NULL
ORDER BY t.due_date ASC NULLS LAST, t.created_at ASC, t.id ASC
LIMIT $3
`

type ListAssignedTicketsAcrossWorkspacesParams struct {
	UserID       sql.NullInt64
	WorkspaceIds json.RawMessage
	RowLimit     int32
}

type ListAssignedTicketsAcrossWorkspacesRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Number         int64
	Title          string
	Priority       int32
	DueDate        pgtext.NullDate
	CreatedAt      time.Time
	WorkspaceSlug  string
	WorkspaceName  string
	ProjectKey     string
	ProjectName    string
	StatusName     string
	StatusCategory string
	StatusColor    string
	TypeName       string
}

// ホームの「自分の担当」。全ワークスペースを横断し、未完了のものを期限の近い順に上限まで返す。
//
// ListAssignedTicketsForPrincipal（1 ワークスペースの全件）との違いは 4 つ。
//  1. 対象のワークスペースは呼び出し側が渡す（workspace_ids）。usecase が所属一覧を domain の
//     判定にかけ、チケットを見てよいワークスペースだけに絞ってから渡す。ここでは所属も役割も
//     判定しない（判定を SQL と domain の 2 か所に置かない）。上限は、絞った後の行にかかる。
//  2. 自分の principal はワークスペースごとに別の行なので、principals（kind='user'・user_id）と
//     JOIN して「そのワークスペースでの自分」を解く。workspace_ids にあっても自分の principal が
//     無いワークスペース（判定の後に所属を外れた等）の行は、この JOIN で 1 件も出ない。
//  3. 完了（状態の枠が done）を除き、期限の近い順 → 期限なしは最後 → 作成の古い順 → id の順に
//     並べてから切る。最後の id は、期限も作成時刻も同じ行の順を毎回同じにするため（上限で切る
//     一覧は、順が揺れると境目の行が出たり消えたりする）。緊急度や重要度は推測しない。
//  4. 一覧の 1 行に要る列だけを返す（本文の doc / plain_text は返さない）。
func (q *Queries) ListAssignedTicketsAcrossWorkspaces(ctx context.Context, arg ListAssignedTicketsAcrossWorkspacesParams) ([]ListAssignedTicketsAcrossWorkspacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssignedTicketsAcrossWorkspaces, arg.UserID, arg.WorkspaceIds, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignedTicketsAcrossWorkspacesRow{}
	for rows.Next() {
		var i ListAssignedTicketsAcrossWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.WorkspaceSlug,
			&i.WorkspaceName,
			&i.ProjectKey,
			&i.ProjectName,
			&i.StatusName,
			&i.StatusCategory,
			&i.StatusColor,
			&i.TypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignedTicketsForPrincipal = `-- name: ListAssignedTicketsForPrincipal :many
SELECT
  t.id, t.workspace_id, t.project_id, t.number, t.type_id, t.status_id, t.parent_id, t.title, t.doc, t.plain_text, t.priority, t.story_points, t.team_id, t.start_date, t.due_date, t.closed_at, t.resolution, t.created_by_user_id, t.archived_at, t.deleted_at, t.created_at, t.updated_at,
  a.assignee_principal_id,
  p.key AS project_key,
  p.name AS project_name,
  s.name AS status_name,
  s.category AS status_category,
  s.color AS status_color,
  s."position" AS status_position,
  ty.name AS type_name
FROM tickets t
JOIN ticket_assignments a
  ON a.workspace_id = t.workspace_id AND a.ticket_id = t.id
JOIN projects p
  ON p.id = t.project_id
JOIN ticket_statuses s
  ON s.workspace_id = t.workspace_id AND s.id = t.status_id
JOIN ticket_types ty
  ON ty.workspace_id = t.workspace_id AND ty.id = t.type_id
WHERE t.workspace_id = $1
  AND a.assignee_principal_id = $2
  AND t.archived_at IS NULL
  AND t.deleted_at IS NULL
ORDER BY
  CASE s.category WHEN 'in_progress' THEN 0 WHEN 'todo' THEN 1 ELSE 2 END,
  s."position",
  t.due_date ASC NULLS LAST,
  t.created_at ASC
`

type ListAssignedTicketsForPrincipalParams struct {
	WorkspaceID         uuid.UUID
	AssigneePrincipalID uuid.UUID
}

type ListAssignedTicketsForPrincipalRow struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	ProjectID           uuid.UUID
	Number              int64
	TypeID              uuid.UUID
	StatusID            uuid.UUID
	ParentID            uuid.NullUUID
	Title               string
	Doc                 json.RawMessage
	PlainText           string
	Priority            int32
	StoryPoints         sql.NullInt32
	TeamID              uuid.NullUUID
	StartDate           pgtext.NullDate
	DueDate             pgtext.NullDate
	ClosedAt            sql.NullTime
	Resolution          sql.NullString
	CreatedByUserID     int64
	ArchivedAt          sql.NullTime
	DeletedAt           sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
	AssigneePrincipalID uuid.UUID
	ProjectKey          string
	ProjectName         string
	StatusName          string
	StatusCategory      string
	StatusColor         string
	StatusPosition      string
	TypeName            string
}

// 「自分の担当」の画面向け。ワークスペース**全体**（プロジェクトを横断）で、その人に
// 割り当たっている現役のチケットを返す。
//
// ListTickets との違いは 2 つ。
//  1. project_id で絞らない。この画面は「どのプロジェクトの仕事か」も込みで一覧にする。
//  2. 表示に要る隣の表の値（プロジェクトの key / 名前、状態の名前・枠・色、種別の名前）を
//     同じ行で返す。1 件ずつ引き直すと行数分の往復になるため。
//
// 並びは「状態の枠 → 状態の並び → 期限の近い順 → 作成の古い順」。枠で束ねて出す画面なので、
// SQL の時点で束の順に並べておけば、画面側は境目を見て見出しを挟むだけで済む。
// 期限が無い行は最後（NULLS LAST）。
func (q *Queries) ListAssignedTicketsForPrincipal(ctx context.Context, arg ListAssignedTicketsForPrincipalParams) ([]ListAssignedTicketsForPrincipalRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssignedTicketsForPrincipal, arg.WorkspaceID, arg.AssigneePrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignedTicketsForPrincipalRow{}
	for rows.Next() {
		var i ListAssignedTicketsForPrincipalRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Number,
			&i.TypeID,
			&i.StatusID,
			&i.ParentID,
			&i.Title,
			&i.Doc,
			&i.PlainText,
			&i.Priority,
			&i.StoryPoints,
			&i.TeamID,
			&i.StartDate,
			&i.DueDate,
			&i.ClosedAt,
			&i.Resolution,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssigneePrincipalID,
			&i.ProjectKey,
			&i.ProjectName,
			&i.StatusName,
			&i.StatusCategory,
			&i.StatusColor,
			&i.StatusPosition,
			&i.TypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingPageIDsInWorkspace = `-- name: ListExistingPageIDsInWorkspace :many
SELECT id FROM pages
WHERE workspace_id = $1
  AND id IN (
    SELECT value::uuid FROM json_array_elements_text($2::json) AS t(value)
  )
`

type ListExistingPageIDsInWorkspaceParams struct {
	WorkspaceID uuid.UUID
	PageIds     json.RawMessage
}

// 本文に貼られた pageRef 候補のうち、**そのワークスペースに実在するページ** だけを返す
// （リンク切れ・別ワークスペースの ID は黙って除外する。設計 Ⅳ-I）。
func (q *Queries) ListExistingPageIDsInWorkspace(ctx context.Context, arg ListExistingPageIDsInWorkspaceParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listExistingPageIDsInWorkspace, arg.WorkspaceID, arg.PageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingTicketIDsInWorkspace = `-- name: ListExistingTicketIDsInWorkspace :many
SELECT id FROM tickets
WHERE workspace_id = $1
  AND id IN (
    SELECT value::uuid FROM json_array_elements_text($2::json) AS t(value)
  )
`

type ListExistingTicketIDsInWorkspaceParams struct {
	WorkspaceID uuid.UUID
	TicketIds   json.RawMessage
}

func (q *Queries) ListExistingTicketIDsInWorkspace(ctx context.Context, arg ListExistingTicketIDsInWorkspaceParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listExistingTicketIDsInWorkspace, arg.WorkspaceID, arg.TicketIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketAncestors = `-- name: ListTicketAncestors :many
SELECT t.id, t.workspace_id, t.project_id, t.number, t.type_id, t.status_id, t.parent_id, t.title, t.doc, t.plain_text, t.priority, t.story_points, t.team_id, t.start_date, t.due_date, t.closed_at, t.resolution, t.created_by_user_id, t.archived_at, t.deleted_at, t.created_at, t.updated_at FROM ticket_paths tp
JOIN tickets t ON t.workspace_id = tp.workspace_id AND t.id = tp.ancestor_id
WHERE tp.workspace_id = $1 AND tp.ticket_id = $2 AND tp.depth > 0 AND t.deleted_at IS NULL
ORDER BY tp.depth DESC
`

type ListTicketAncestorsParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
}

// パンくず用。根から順（depth の大きい方が根に近い）に祖先チケットを返す。自分自身
// （depth=0）は含まない。チケットの親は常に同一スペース限定（fk_tickets_parent）なので、
// ページの ListAncestorPageIDsと違い祖先ごとの可視判定は要らない（このチケット自体が
// 見えるなら、同じスペースの祖先もすべて見える。設計 Ⅳ-H）。
//
// 論理削除済みの祖先は除く。DeleteTicketUseCase は削除を子へ連鎖させないため、
// 子が生きたまま親だけ削除された状態があり得る。ここで絞らないと、削除後に
// スペースへ権限を得た利用者が、削除より前の題名・本文をパンくず経由で読めてしまう
// （ListTicketsReferencingPage が既にこの形で deleted_at を見ている）。
// アーカイブ済みの祖先は含める（GetTicket 等の個票取得と同じ扱い。アーカイブは
// 「隠す」ではなく「畳む」ための状態で、経路から抜くと場所を偽ることになる）。
func (q *Queries) ListTicketAncestors(ctx context.Context, arg ListTicketAncestorsParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketAncestors, arg.WorkspaceID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Number,
			&i.TypeID,
			&i.StatusID,
			&i.ParentID,
			&i.Title,
			&i.Doc,
			&i.PlainText,
			&i.Priority,
			&i.StoryPoints,
			&i.TeamID,
			&i.StartDate,
			&i.DueDate,
			&i.ClosedAt,
			&i.Resolution,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketChangeGroups = `-- name: ListTicketChangeGroups :many
SELECT id, workspace_id, ticket_id, actor_user_id, created_at, deleted_at FROM ticket_change_groups
WHERE workspace_id = $1 AND ticket_id = $2
ORDER BY created_at DESC
`

type ListTicketChangeGroupsParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
}

func (q *Queries) ListTicketChangeGroups(ctx context.Context, arg ListTicketChangeGroupsParams) ([]TicketChangeGroup, error) {
	rows, err := q.db.QueryContext(ctx, listTicketChangeGroups, arg.WorkspaceID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketChangeGroup{}
	for rows.Next() {
		var i TicketChangeGroup
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TicketID,
			&i.ActorUserID,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketChangeItemsByGroupIDs = `-- name: ListTicketChangeItemsByGroupIDs :many
SELECT i.id, i.workspace_id, i.group_id, i.field, i.old_value, i.new_value, i.old_label, i.new_label, i.deleted_at FROM ticket_change_items i
WHERE i.workspace_id = $1
  AND i.group_id IN (
    SELECT value::uuid FROM json_array_elements_text($2::json) AS t(value)
  )
ORDER BY i.group_id
`

type ListTicketChangeItemsByGroupIDsParams struct {
	WorkspaceID uuid.UUID
	GroupIds    json.RawMessage
}

// group_id 群は json 配列 1 個のパラメータで渡す（no-array-param。comment.sql と同じ形）。
func (q *Queries) ListTicketChangeItemsByGroupIDs(ctx context.Context, arg ListTicketChangeItemsByGroupIDsParams) ([]TicketChangeItem, error) {
	rows, err := q.db.QueryContext(ctx, listTicketChangeItemsByGroupIDs, arg.WorkspaceID, arg.GroupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketChangeItem{}
	for rows.Next() {
		var i TicketChangeItem
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.GroupID,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.OldLabel,
			&i.NewLabel,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketChildren = `-- name: ListTicketChildren :many
SELECT t.id, t.workspace_id, t.project_id, t.number, t.type_id, t.status_id, t.parent_id, t.title, t.doc, t.plain_text, t.priority, t.story_points, t.team_id, t.start_date, t.due_date, t.closed_at, t.resolution, t.created_by_user_id, t.archived_at, t.deleted_at, t.created_at, t.updated_at, COALESCE(r."position", '')::text AS rank_position FROM tickets t
LEFT JOIN ticket_backlog_ranks r ON r.workspace_id = t.workspace_id AND r.ticket_id = t.id
WHERE t.workspace_id = $1 AND t.project_id = $2 AND t.parent_id = $3
  AND t.archived_at IS NULL AND t.deleted_at IS NULL
ORDER BY r."position"
`

type ListTicketChildrenParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	ParentID    uuid.NullUUID
}

type ListTicketChildrenRow struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	ProjectID       uuid.UUID
	Number          int64
	TypeID          uuid.UUID
	StatusID        uuid.UUID
	ParentID        uuid.NullUUID
	Title           string
	Doc             json.RawMessage
	PlainText       string
	Priority        int32
	StoryPoints     sql.NullInt32
	TeamID          uuid.NullUUID
	StartDate       pgtext.NullDate
	DueDate         pgtext.NullDate
	ClosedAt        sql.NullTime
	Resolution      sql.NullString
	CreatedByUserID int64
	ArchivedAt      sql.NullTime
	DeletedAt       sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
	RankPosition    string
}

// ticket_backlog_ranks を LEFT JOIN で並び順を rank_position として返す（同上）。
func (q *Queries) ListTicketChildren(ctx context.Context, arg ListTicketChildrenParams) ([]ListTicketChildrenRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketChildren, arg.WorkspaceID, arg.ProjectID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketChildrenRow{}
	for rows.Next() {
		var i ListTicketChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Number,
			&i.TypeID,
			&i.StatusID,
			&i.ParentID,
			&i.Title,
			&i.Doc,
			&i.PlainText,
			&i.Priority,
			&i.StoryPoints,
			&i.TeamID,
			&i.StartDate,
			&i.DueDate,
			&i.ClosedAt,
			&i.Resolution,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RankPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketPageLinksBySource = `-- name: ListTicketPageLinksBySource :many
SELECT workspace_id, source_ticket_id, target_page_id, deleted_at FROM ticket_page_links
WHERE workspace_id = $1 AND source_ticket_id = $2
`

type ListTicketPageLinksBySourceParams struct {
	WorkspaceID    uuid.UUID
	SourceTicketID uuid.UUID
}

func (q *Queries) ListTicketPageLinksBySource(ctx context.Context, arg ListTicketPageLinksBySourceParams) ([]TicketPageLink, error) {
	rows, err := q.db.QueryContext(ctx, listTicketPageLinksBySource, arg.WorkspaceID, arg.SourceTicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketPageLink{}
	for rows.Next() {
		var i TicketPageLink
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.SourceTicketID,
			&i.TargetPageID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketParentChain = `-- name: ListTicketParentChain :many
WITH RECURSIVE chain AS (
  SELECT t.id, t.workspace_id, t.project_id, t.number, t.type_id, t.status_id, t.parent_id, t.title, t.doc, t.plain_text, t.priority, t.story_points, t.team_id, t.start_date, t.due_date, t.closed_at, t.resolution, t.created_by_user_id, t.archived_at, t.deleted_at, t.created_at, t.updated_at, 0 AS depth
  FROM tickets t
  WHERE t.workspace_id = $1 AND t.id = $2
  UNION ALL
  SELECT p.id, p.workspace_id, p.project_id, p.number, p.type_id, p.status_id, p.parent_id, p.title, p.doc, p.plain_text, p.priority, p.story_points, p.team_id, p.start_date, p.due_date, p.closed_at, p.resolution, p.created_by_user_id, p.archived_at, p.deleted_at, p.created_at, p.updated_at, c.depth + 1
  FROM tickets p
  JOIN chain c ON p.workspace_id = c.workspace_id AND p.id = c.parent_id
  WHERE c.depth < 10
)
SELECT id, workspace_id, project_id, number, type_id, status_id, parent_id, title, doc,
  plain_text, priority, start_date, due_date, closed_at, resolution,
  created_by_user_id, archived_at, deleted_at, created_at, updated_at
FROM chain
WHERE depth > 0
ORDER BY depth DESC
`

type ListTicketParentChainParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
}

type ListTicketParentChainRow struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	ProjectID       uuid.UUID
	Number          int64
	TypeID          uuid.UUID
	StatusID        uuid.UUID
	ParentID        uuid.NullUUID
	Title           string
	Doc             json.RawMessage
	PlainText       string
	Priority        int32
	StartDate       pgtext.NullDate
	DueDate         pgtext.NullDate
	ClosedAt        sql.NullTime
	Resolution      sql.NullString
	CreatedByUserID int64
	ArchivedAt      sql.NullTime
	DeletedAt       sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// 親を根まで辿る（自分は含まない、根に近い順）。最大 3 段の設計なので再帰は浅く終わるが、
// 誤ったデータで循環していても RECURSIVE は無限ループしない（訪問済み id を UNION の
// 重複排除では止められないため、深さで打ち切る）。
func (q *Queries) ListTicketParentChain(ctx context.Context, arg ListTicketParentChainParams) ([]ListTicketParentChainRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketParentChain, arg.WorkspaceID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketParentChainRow{}
	for rows.Next() {
		var i ListTicketParentChainRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Number,
			&i.TypeID,
			&i.StatusID,
			&i.ParentID,
			&i.Title,
			&i.Doc,
			&i.PlainText,
			&i.Priority,
			&i.StartDate,
			&i.DueDate,
			&i.ClosedAt,
			&i.Resolution,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketStatuses = `-- name: ListTicketStatuses :many
SELECT id, workspace_id, project_id, name, name_lower, category, color, position, is_initial, archived_at, deleted_at, created_at, updated_at FROM ticket_statuses
WHERE workspace_id = $1 AND project_id = $2
  AND (archived_at IS NOT NULL) = $3::boolean
ORDER BY "position"
`

type ListTicketStatusesParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	Archived    bool
}

// sqlc.narg(archived) は bool。呼び出し側は「現役だけ」か「アーカイブ済みだけ」かを
// 明示的に渡す（NULL で「両方」は扱わない — 管理画面のタブ切り替えに 1 対 1 対応させる）。
func (q *Queries) ListTicketStatuses(ctx context.Context, arg ListTicketStatusesParams) ([]TicketStatus, error) {
	rows, err := q.db.QueryContext(ctx, listTicketStatuses, arg.WorkspaceID, arg.ProjectID, arg.Archived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketStatus{}
	for rows.Next() {
		var i TicketStatus
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Name,
			&i.NameLower,
			&i.Category,
			&i.Color,
			&i.Position,
			&i.IsInitial,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTicketLinksBySource = `-- name: ListTicketTicketLinksBySource :many
SELECT workspace_id, source_ticket_id, target_ticket_id, deleted_at FROM ticket_ticket_links
WHERE workspace_id = $1 AND source_ticket_id = $2
`

type ListTicketTicketLinksBySourceParams struct {
	WorkspaceID    uuid.UUID
	SourceTicketID uuid.UUID
}

func (q *Queries) ListTicketTicketLinksBySource(ctx context.Context, arg ListTicketTicketLinksBySourceParams) ([]TicketTicketLink, error) {
	rows, err := q.db.QueryContext(ctx, listTicketTicketLinksBySource, arg.WorkspaceID, arg.SourceTicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketTicketLink{}
	for rows.Next() {
		var i TicketTicketLink
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.SourceTicketID,
			&i.TargetTicketID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypes = `-- name: ListTicketTypes :many
SELECT id, workspace_id, project_id, name, name_lower, color, hierarchy_level, position, is_default, template_title, template_doc, archived_at, deleted_at, created_at, updated_at FROM ticket_types
WHERE workspace_id = $1 AND project_id = $2
  AND (archived_at IS NOT NULL) = $3::boolean
ORDER BY "position"
`

type ListTicketTypesParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	Archived    bool
}

func (q *Queries) ListTicketTypes(ctx context.Context, arg ListTicketTypesParams) ([]TicketType, error) {
	rows, err := q.db.QueryContext(ctx, listTicketTypes, arg.WorkspaceID, arg.ProjectID, arg.Archived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketType{}
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Name,
			&i.NameLower,
			&i.Color,
			&i.HierarchyLevel,
			&i.Position,
			&i.IsDefault,
			&i.TemplateTitle,
			&i.TemplateDoc,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT t.id, t.workspace_id, t.project_id, t.number, t.type_id, t.status_id, t.parent_id, t.title, t.doc, t.plain_text, t.priority, t.story_points, t.team_id, t.start_date, t.due_date, t.closed_at, t.resolution, t.created_by_user_id, t.archived_at, t.deleted_at, t.created_at, t.updated_at, a.assignee_principal_id, COALESCE(r."position", '')::text AS rank_position FROM tickets t
LEFT JOIN ticket_backlog_ranks r ON r.workspace_id = t.workspace_id AND r.ticket_id = t.id
LEFT JOIN ticket_assignments a ON a.workspace_id = t.workspace_id AND a.ticket_id = t.id
LEFT JOIN ticket_statuses s ON s.workspace_id = t.workspace_id AND s.id = t.status_id
WHERE t.workspace_id = $1 AND t.project_id = $2
  AND t.deleted_at IS NULL
  AND (t.archived_at IS NOT NULL) = $3::boolean
  AND ($4::uuid IS NULL OR t.status_id = $4::uuid)
  AND ($5::uuid IS NULL OR t.type_id = $5::uuid)
  AND (
    $6::uuid IS NULL
    OR a.assignee_principal_id = $6::uuid
  )
  AND (NOT $7::boolean OR a.assignee_principal_id IS NULL)
  AND (
    $8::uuid IS NULL
    OR a.assignee_principal_id = $8::uuid
  )
  AND (
    $9::uuid IS NULL
    OR EXISTS (
      SELECT 1 FROM ticket_labels tl
      WHERE tl.workspace_id = t.workspace_id AND tl.ticket_id = t.id AND tl.label_id = $9::uuid
    )
  )
  AND ($10::date IS NULL OR t.due_date <= $10::date)
  AND ($11::date IS NULL OR t.start_date >= $11::date)
  AND (NOT $12::boolean OR (t.due_date < CURRENT_DATE AND s.category <> 'done'))
  AND (
    $13::text IS NULL
    OR t.title ILIKE '%' || $13::text || '%'
    OR t.plain_text ILIKE '%' || $13::text || '%'
    OR word_similarity($13::text, t.title) > 0.6
    OR word_similarity($13::text, t.plain_text) > 0.6
  )
ORDER BY r."position"
`

type ListTicketsParams struct {
	WorkspaceID             uuid.UUID
	ProjectID               uuid.UUID
	IncludeArchived         bool
	StatusID                uuid.NullUUID
	TypeID                  uuid.NullUUID
	AssigneePrincipalID     uuid.NullUUID
	Unassigned              bool
	AssignedToMePrincipalID uuid.NullUUID
	LabelID                 uuid.NullUUID
	DueBefore               pgtext.NullDate
	StartAfter              pgtext.NullDate
	Overdue                 bool
	Q                       sql.NullString
}

type ListTicketsRow struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	ProjectID           uuid.UUID
	Number              int64
	TypeID              uuid.UUID
	StatusID            uuid.UUID
	ParentID            uuid.NullUUID
	Title               string
	Doc                 json.RawMessage
	PlainText           string
	Priority            int32
	StoryPoints         sql.NullInt32
	TeamID              uuid.NullUUID
	StartDate           pgtext.NullDate
	DueDate             pgtext.NullDate
	ClosedAt            sql.NullTime
	Resolution          sql.NullString
	CreatedByUserID     int64
	ArchivedAt          sql.NullTime
	DeletedAt           sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
	AssigneePrincipalID uuid.NullUUID
	RankPosition        string
}

// status_id / type_id / assignee_principal_id / label_id / due_before / start_after / q は
// いずれも sqlc.narg。NULL なら絞らない（段 4 で label_id / due_before / start_after を追加。
// 段 5 で unassigned / assigned_to_me / overdue / q を追加）。
// label_id は ticket_labels への EXISTS で絞る（LEFT JOIN だとラベル数だけ行が重複するため）。
// due_before / start_after は 'YYYY-MM-DD' 文字列を date として渡す（tickets.due_date /
// start_date と同じ運び方。冒頭の作法参照）。
// unassigned / assigned_to_me は担当の絞り込みが「誰でもよい/この ID/未割り当て/自分」の
// 4 通りあるため、assignee_principal_id とは別の bool narg にする（1 つの引数に "me" 等の
// 文字列を混ぜると uuid のパースと衝突するため）。呼び出し側（handler）は 3 つが同時に
// 立たないよう検証する。overdue は「期限が今日より前、かつ状態が完了(done)ではない」
// （done のチケットは「終わっているので遅延ではない」という扱い。設計 段 5）。
// q は題名（title）・本文の素テキスト写し（plain_text）の両方を対象にする。ILIKE の
// 中間一致に加えて word_similarity(q, 対象) > 0.6 を OR し、表記ゆれ・打ち間違いも拾う
// （KB ページ検索の SearchPages と同じ考え方。schema.hcl 冒頭の「pg_trgm 拡張について」参照）。
// ticket_backlog_ranks を LEFT JOIN で並び順を rank_position として返す（GetTicket と同じ理由）。
// deleted_at IS NULL は常に付ける（include_archived の有無に関わらず、削除済みは一覧に出さない）。
func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]ListTicketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTickets,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.IncludeArchived,
		arg.StatusID,
		arg.TypeID,
		arg.AssigneePrincipalID,
		arg.Unassigned,
		arg.AssignedToMePrincipalID,
		arg.LabelID,
		arg.DueBefore,
		arg.StartAfter,
		arg.Overdue,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsRow{}
	for rows.Next() {
		var i ListTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Number,
			&i.TypeID,
			&i.StatusID,
			&i.ParentID,
			&i.Title,
			&i.Doc,
			&i.PlainText,
			&i.Priority,
			&i.StoryPoints,
			&i.TeamID,
			&i.StartDate,
			&i.DueDate,
			&i.ClosedAt,
			&i.Resolution,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssigneePrincipalID,
			&i.RankPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsAssignedToPrincipal = `-- name: ListTicketsAssignedToPrincipal :many
SELECT t.id, t.workspace_id, t.project_id, t.number, t.type_id, t.status_id, t.parent_id, t.title, t.doc, t.plain_text, t.priority, t.story_points, t.team_id, t.start_date, t.due_date, t.closed_at, t.resolution, t.created_by_user_id, t.archived_at, t.deleted_at, t.created_at, t.updated_at FROM tickets t
JOIN ticket_assignments a ON a.workspace_id = t.workspace_id AND a.ticket_id = t.id
WHERE t.workspace_id = $1 AND a.assignee_principal_id = $2
  AND t.archived_at IS NULL AND t.deleted_at IS NULL
`

type ListTicketsAssignedToPrincipalParams struct {
	WorkspaceID         uuid.UUID
	AssigneePrincipalID uuid.UUID
}

func (q *Queries) ListTicketsAssignedToPrincipal(ctx context.Context, arg ListTicketsAssignedToPrincipalParams) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsAssignedToPrincipal, arg.WorkspaceID, arg.AssigneePrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Number,
			&i.TypeID,
			&i.StatusID,
			&i.ParentID,
			&i.Title,
			&i.Doc,
			&i.PlainText,
			&i.Priority,
			&i.StoryPoints,
			&i.TeamID,
			&i.StartDate,
			&i.DueDate,
			&i.ClosedAt,
			&i.Resolution,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsReferencingPage = `-- name: ListTicketsReferencingPage :many
SELECT
  t.id,
  t.title,
  t.number,
  p.key AS project_key
FROM ticket_page_links tpl
JOIN tickets t ON t.workspace_id = tpl.workspace_id AND t.id = tpl.source_ticket_id
JOIN projects p ON p.id = t.project_id
WHERE tpl.workspace_id = $1
  AND tpl.target_page_id = $2
  AND tpl.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND t.archived_at IS NULL
ORDER BY t.updated_at DESC, t.id DESC
LIMIT $3
`

type ListTicketsReferencingPageParams struct {
	WorkspaceID  uuid.UUID
	TargetPageID uuid.UUID
	RowLimit     int32
}

type ListTicketsReferencingPageRow struct {
	ID         uuid.UUID
	Title      string
	Number     int64
	ProjectKey string
}

// ページを本文の pageRef で参照しているチケット（逆参照）。ホームの「続きからはじめる」が、
// 最後に開いたページに「このページを参照しているチケット」として短く添える。
//
// deleted_at IS NULL（ticket_page_links）: 参照元チケットが削除されていれば、削除時に
// DeleteTicketPageLinksBySourceCascade がこの行にも deleted_at を立てている。ここで除かないと、
// 消えたはずのチケットの存在がページ側の逆参照一覧から漏れる（参照元チケットの deleted_at を
// 都度 JOIN で見る代わりに、削除時に伝播させて 1 列で判定できるようにしてある。設計 Ⅳ-J の
// 「読み出しの述語を単純に保つ」）。t.deleted_at IS NULL は伝播が万一漏れた場合の二重の安全弁。
//
// アーカイブしたチケットは出さない（片付けた仕事を「このページを参照している」として並べない）。
// 完了したチケットは出す（そのページが何の仕事に使われたかを知る手がかりになる）。
// 並びは更新の新しい順。上限で切るので、更新時刻が同じ行の順が毎回同じになるよう最後に id で
// 決める。返すのは一覧の 1 行に要る列（題名と表示キーの材料）だけで、本文は返さない。
func (q *Queries) ListTicketsReferencingPage(ctx context.Context, arg ListTicketsReferencingPageParams) ([]ListTicketsReferencingPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsReferencingPage, arg.WorkspaceID, arg.TargetPageID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsReferencingPageRow{}
	for rows.Next() {
		var i ListTicketsReferencingPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Number,
			&i.ProjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsReferencingTicket = `-- name: ListTicketsReferencingTicket :many
SELECT workspace_id, source_ticket_id, target_ticket_id, deleted_at FROM ticket_ticket_links
WHERE workspace_id = $1 AND target_ticket_id = $2 AND deleted_at IS NULL
`

type ListTicketsReferencingTicketParams struct {
	WorkspaceID    uuid.UUID
	TargetTicketID uuid.UUID
}

// deleted_at IS NULL: ListPagesReferencingTicket と同じ理由（参照元チケットの削除を伝播で判定）。
func (q *Queries) ListTicketsReferencingTicket(ctx context.Context, arg ListTicketsReferencingTicketParams) ([]TicketTicketLink, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsReferencingTicket, arg.WorkspaceID, arg.TargetTicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketTicketLink{}
	for rows.Next() {
		var i TicketTicketLink
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.SourceTicketID,
			&i.TargetTicketID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTicketBacklogRank = `-- name: MoveTicketBacklogRank :execrows
UPDATE ticket_backlog_ranks
SET "position" = $3, updated_at = now()
WHERE workspace_id = $1 AND ticket_id = $2
`

type MoveTicketBacklogRankParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
	Position    string
}

func (q *Queries) MoveTicketBacklogRank(ctx context.Context, arg MoveTicketBacklogRankParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveTicketBacklogRank, arg.WorkspaceID, arg.TicketID, arg.Position)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveTicketIDByKey = `-- name: ResolveTicketIDByKey :one
SELECT t.id, t.workspace_id FROM tickets t
JOIN projects p ON p.workspace_id = t.workspace_id AND p.id = t.project_id
WHERE t.workspace_id = $1
  AND lower(p."key") = $2
  AND t.number = $3
`

type ResolveTicketIDByKeyParams struct {
	WorkspaceID uuid.UUID
	ProjectKey  string
	Number      int64
}

type ResolveTicketIDByKeyRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// spaceKey（小文字。domain.ParseTicketKey が返す）+ number からチケットを引く。
func (q *Queries) ResolveTicketIDByKey(ctx context.Context, arg ResolveTicketIDByKeyParams) (ResolveTicketIDByKeyRow, error) {
	row := q.db.QueryRowContext(ctx, resolveTicketIDByKey, arg.WorkspaceID, arg.ProjectKey, arg.Number)
	var i ResolveTicketIDByKeyRow
	err := row.Scan(&i.ID, &i.WorkspaceID)
	return i, err
}

const restoreDeletedTicket = `-- name: RestoreDeletedTicket :execrows
UPDATE tickets
SET deleted_at = NULL, updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NOT NULL
`

type RestoreDeletedTicketParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// 並び順は末尾へ付け直す（削除されていた間に他のチケットの並びが進んでいる可能性が
// あるため、元の位置は復元しない）。付け直しは呼び出し側の UpsertTicketBacklogRank。
func (q *Queries) RestoreDeletedTicket(ctx context.Context, arg RestoreDeletedTicketParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreDeletedTicket, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreTicket = `-- name: RestoreTicket :execrows
UPDATE tickets
SET archived_at = NULL, updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND archived_at IS NOT NULL AND deleted_at IS NULL
`

type RestoreTicketParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// 並び順の付け直しはこの文では行わない。呼び出し側（RestoreTicketUseCase）が
// UpsertTicketBacklogRank で末尾へ置き直す。
func (q *Queries) RestoreTicket(ctx context.Context, arg RestoreTicketParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreTicket, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreTicketStatus = `-- name: RestoreTicketStatus :execrows
UPDATE ticket_statuses
SET archived_at = NULL, "position" = $4, updated_at = now()
WHERE workspace_id = $1 AND project_id = $2 AND id = $3 AND archived_at IS NOT NULL
`

type RestoreTicketStatusParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	ID          uuid.UUID
	Position    string
}

// position を末尾へ付け直す（呼び出し側が LastActiveTicketStatusPosition から
// fracindex.Between で採番した値を渡す）。
func (q *Queries) RestoreTicketStatus(ctx context.Context, arg RestoreTicketStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreTicketStatus,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ID,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreTicketType = `-- name: RestoreTicketType :execrows
UPDATE ticket_types
SET archived_at = NULL, "position" = $4, updated_at = now()
WHERE workspace_id = $1 AND project_id = $2 AND id = $3 AND archived_at IS NOT NULL
`

type RestoreTicketTypeParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	ID          uuid.UUID
	Position    string
}

func (q *Queries) RestoreTicketType(ctx context.Context, arg RestoreTicketTypeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreTicketType,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ID,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTicketStatusInitial = `-- name: SetTicketStatusInitial :execrows
UPDATE ticket_statuses
SET is_initial = true, updated_at = now()
WHERE workspace_id = $1 AND project_id = $2 AND id = $3 AND archived_at IS NULL
`

type SetTicketStatusInitialParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SetTicketStatusInitial(ctx context.Context, arg SetTicketStatusInitialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTicketStatusInitial, arg.WorkspaceID, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTicketTypeDefault = `-- name: SetTicketTypeDefault :execrows
UPDATE ticket_types
SET is_default = true, updated_at = now()
WHERE workspace_id = $1 AND project_id = $2 AND id = $3 AND archived_at IS NULL
`

type SetTicketTypeDefaultParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SetTicketTypeDefault(ctx context.Context, arg SetTicketTypeDefaultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTicketTypeDefault, arg.WorkspaceID, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET type_id = $1, parent_id = $2, title = $3,
    doc = $4, plain_text = $5, priority = $6,
    -- ::bigint で受ける（列は integer）。::integer だと sqlc が int32 で生成し、
    -- 範囲外の値が Go 側で黙って負数へ折り返す。bigint で渡せば、範囲外は
    -- PostgreSQL が "integer out of range" で弾く（縮小を DB に判定させる）。
    story_points = $7::bigint,
    start_date = $8::date, due_date = $9::date,
    updated_at = now()
WHERE workspace_id = $10 AND id = $11
RETURNING id, workspace_id, project_id, number, type_id, status_id, parent_id, title, doc, plain_text, priority, story_points, team_id, start_date, due_date, closed_at, resolution, created_by_user_id, archived_at, deleted_at, created_at, updated_at
`

type UpdateTicketParams struct {
	TypeID      uuid.UUID
	ParentID    uuid.NullUUID
	Title       string
	Doc         json.RawMessage
	PlainText   string
	Priority    int32
	StoryPoints sql.NullInt64
	StartDate   pgtext.NullDate
	DueDate     pgtext.NullDate
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// 並び順（rank_position）は返さない。RETURNING に JOIN は書けず、CTE で繋ぐ形も
// RETURNING の中の相関副問い合わせも、sqlc の解析器が RETURNING * の列を追えずに
// 「workspace_id が曖昧」で落ちる（PostgreSQL 自体は通す文なのに、生成が通らない）。
// 更新は並び順に触らないので、呼び出し側は position を空のまま受け取り、並びが要る画面は
// 一覧（ListTickets）を読み直す。詳しくは toDomainTicket の doc を参照。
func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, updateTicket,
		arg.TypeID,
		arg.ParentID,
		arg.Title,
		arg.Doc,
		arg.PlainText,
		arg.Priority,
		arg.StoryPoints,
		arg.StartDate,
		arg.DueDate,
		arg.WorkspaceID,
		arg.ID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Number,
		&i.TypeID,
		&i.StatusID,
		&i.ParentID,
		&i.Title,
		&i.Doc,
		&i.PlainText,
		&i.Priority,
		&i.StoryPoints,
		&i.TeamID,
		&i.StartDate,
		&i.DueDate,
		&i.ClosedAt,
		&i.Resolution,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicketStatus = `-- name: UpdateTicketStatus :one
UPDATE ticket_statuses
SET name = $4, category = $5, color = $6, updated_at = now()
WHERE workspace_id = $1 AND project_id = $2 AND id = $3
RETURNING id, workspace_id, project_id, name, name_lower, category, color, position, is_initial, archived_at, deleted_at, created_at, updated_at
`

type UpdateTicketStatusParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	ID          uuid.UUID
	Name        string
	Category    string
	Color       string
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (TicketStatus, error) {
	row := q.db.QueryRowContext(ctx, updateTicketStatus,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Color,
	)
	var i TicketStatus
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.NameLower,
		&i.Category,
		&i.Color,
		&i.Position,
		&i.IsInitial,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicketType = `-- name: UpdateTicketType :one
UPDATE ticket_types
SET name = $4, color = $5, hierarchy_level = $6,
    template_title = $7, template_doc = $8, updated_at = now()
WHERE workspace_id = $1 AND project_id = $2 AND id = $3
RETURNING id, workspace_id, project_id, name, name_lower, color, hierarchy_level, position, is_default, template_title, template_doc, archived_at, deleted_at, created_at, updated_at
`

type UpdateTicketTypeParams struct {
	WorkspaceID    uuid.UUID
	ProjectID      uuid.UUID
	ID             uuid.UUID
	Name           string
	Color          string
	HierarchyLevel int32
	TemplateTitle  sql.NullString
	TemplateDoc    *json.RawMessage
}

func (q *Queries) UpdateTicketType(ctx context.Context, arg UpdateTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRowContext(ctx, updateTicketType,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.HierarchyLevel,
		arg.TemplateTitle,
		arg.TemplateDoc,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.NameLower,
		&i.Color,
		&i.HierarchyLevel,
		&i.Position,
		&i.IsDefault,
		&i.TemplateTitle,
		&i.TemplateDoc,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTicketAssignment = `-- name: UpsertTicketAssignment :one

INSERT INTO ticket_assignments
  (workspace_id, ticket_id, assignee_principal_id, assigned_by_user_id, created_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (ticket_id)
DO UPDATE SET assignee_principal_id = EXCLUDED.assignee_principal_id,
              assigned_by_user_id = EXCLUDED.assigned_by_user_id
WHERE ticket_assignments.workspace_id = EXCLUDED.workspace_id
RETURNING workspace_id, ticket_id, assignee_principal_id, assignee_kind, assigned_by_user_id, created_at, deleted_at
`

type UpsertTicketAssignmentParams struct {
	WorkspaceID         uuid.UUID
	TicketID            uuid.UUID
	AssigneePrincipalID uuid.UUID
	AssignedByUserID    int64
}

// =============================================================================
// ticket_assignments
// =============================================================================
// 衝突キー (ticket_id) は PK 単独だが、行の所有者列 workspace_id が EXCLUDED と一致する
// ときだけ更新する（blocks の upsert と同じ形。呼び出し側が ticket_id と workspace_id を
// 取り違えても、他テナントの行を上書きしない歯止めになる）。
func (q *Queries) UpsertTicketAssignment(ctx context.Context, arg UpsertTicketAssignmentParams) (TicketAssignment, error) {
	row := q.db.QueryRowContext(ctx, upsertTicketAssignment,
		arg.WorkspaceID,
		arg.TicketID,
		arg.AssigneePrincipalID,
		arg.AssignedByUserID,
	)
	var i TicketAssignment
	err := row.Scan(
		&i.WorkspaceID,
		&i.TicketID,
		&i.AssigneePrincipalID,
		&i.AssigneeKind,
		&i.AssignedByUserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertTicketBacklogRank = `-- name: UpsertTicketBacklogRank :exec
INSERT INTO ticket_backlog_ranks (workspace_id, project_id, ticket_id, "position", created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
ON CONFLICT (workspace_id, ticket_id)
DO UPDATE SET "position" = EXCLUDED."position", updated_at = now()
`

type UpsertTicketBacklogRankParams struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	TicketID    uuid.UUID
	Position    string
}

// 復元（アーカイブ解除・削除取り消し）で末尾へ置き直すときに使う。
//
// 素の UPDATE ではなく upsert にしてあるのは、並び順の行が無いチケットが有り得るため
// —— この表より前に作られたチケットは、移行で現役の分だけに行を入れた（撤去済みだった
// tickets.position から写した）。当時アーカイブ済み・削除済みだった分には行が無い。
// UPDATE だけだと、そういうチケットを復元したときに 0 行で失敗する。
func (q *Queries) UpsertTicketBacklogRank(ctx context.Context, arg UpsertTicketBacklogRankParams) error {
	_, err := q.db.ExecContext(ctx, upsertTicketBacklogRank,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TicketID,
		arg.Position,
	)
	return err
}
