// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_label.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addTicketLabel = `-- name: AddTicketLabel :execrows

INSERT INTO ticket_labels (workspace_id, ticket_id, label_id, created_at)
VALUES ($1, $2, $3, now())
ON CONFLICT DO NOTHING
`

type AddTicketLabelParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
	LabelID     uuid.UUID
}

// =============================================================================
// ticket_labels
// =============================================================================
// 付け外しは冪等（ticket_comment_reactions と同じ形 — 複合主キーの重複を無視する）。
func (q *Queries) AddTicketLabel(ctx context.Context, arg AddTicketLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addTicketLabel, arg.WorkspaceID, arg.TicketID, arg.LabelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createLabel = `-- name: CreateLabel :one


INSERT INTO labels (id, workspace_id, name, color, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, workspace_id, name, name_key, color, created_at, updated_at
`

type CreateLabelParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Color       string
}

// ラベル（labels）とチケットへの付け外し（ticket_labels）のクエリ。
// ラベルはワークスペース単位の語彙で、ページ（page_labels）とチケット（ticket_labels）の
// 両方から同じ行を引く（labels テーブルの doc コメント参照）。
// =============================================================================
// labels
// =============================================================================
func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, createLabel,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Color,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.NameKey,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLabel = `-- name: DeleteLabel :execrows
DELETE FROM labels WHERE workspace_id = $1 AND id = $2
`

type DeleteLabelParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// ticket_labels / page_labels は ON DELETE CASCADE で一緒に消える。
func (q *Queries) DeleteLabel(ctx context.Context, arg DeleteLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLabel, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findLabel = `-- name: FindLabel :one
SELECT id, workspace_id, name, name_key, color, created_at, updated_at FROM labels WHERE workspace_id = $1 AND id = $2
`

type FindLabelParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) FindLabel(ctx context.Context, arg FindLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, findLabel, arg.WorkspaceID, arg.ID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.NameKey,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLabels = `-- name: ListLabels :many
SELECT id, workspace_id, name, name_key, color, created_at, updated_at FROM labels WHERE workspace_id = $1 ORDER BY name_key
`

func (q *Queries) ListLabels(ctx context.Context, workspaceID uuid.UUID) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabels, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.NameKey,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByTicket = `-- name: ListLabelsByTicket :many
SELECT l.id, l.workspace_id, l.name, l.name_key, l.color, l.created_at, l.updated_at FROM labels l
JOIN ticket_labels tl ON tl.workspace_id = l.workspace_id AND tl.label_id = l.id
WHERE tl.workspace_id = $1 AND tl.ticket_id = $2
ORDER BY l.name_key
`

type ListLabelsByTicketParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
}

func (q *Queries) ListLabelsByTicket(ctx context.Context, arg ListLabelsByTicketParams) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabelsByTicket, arg.WorkspaceID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.NameKey,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByTicketIDs = `-- name: ListLabelsByTicketIDs :many
SELECT tl.ticket_id, l.id, l.workspace_id, l.name, l.name_key, l.color, l.created_at, l.updated_at FROM ticket_labels tl
JOIN labels l ON l.workspace_id = tl.workspace_id AND l.id = tl.label_id
WHERE tl.workspace_id = $1
  AND tl.ticket_id IN (
    SELECT value::uuid FROM json_array_elements_text($2::json) AS t(value)
  )
ORDER BY tl.ticket_id, l.name_key
`

type ListLabelsByTicketIDsParams struct {
	WorkspaceID uuid.UUID
	TicketIds   json.RawMessage
}

type ListLabelsByTicketIDsRow struct {
	TicketID    uuid.UUID
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	NameKey     sql.NullString
	Color       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// ticket_id ごとのラベル一覧を 1 回でまとめて引く（一覧画面の N+1 を避ける）。
// ticket_id 群は json 配列 1 個のパラメータで渡す（comment.sql の ListCommentsByThreadIDs と
// 同じ作法 — `= ANY(...)::uuid[]` は database/sql モードの sqlc で pq.Array() 依存になり
// ビルドが壊れるため使わない）。
func (q *Queries) ListLabelsByTicketIDs(ctx context.Context, arg ListLabelsByTicketIDsParams) ([]ListLabelsByTicketIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLabelsByTicketIDs, arg.WorkspaceID, arg.TicketIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsByTicketIDsRow{}
	for rows.Next() {
		var i ListLabelsByTicketIDsRow
		if err := rows.Scan(
			&i.TicketID,
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.NameKey,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTicketLabel = `-- name: RemoveTicketLabel :execrows
DELETE FROM ticket_labels WHERE workspace_id = $1 AND ticket_id = $2 AND label_id = $3
`

type RemoveTicketLabelParams struct {
	WorkspaceID uuid.UUID
	TicketID    uuid.UUID
	LabelID     uuid.UUID
}

func (q *Queries) RemoveTicketLabel(ctx context.Context, arg RemoveTicketLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeTicketLabel, arg.WorkspaceID, arg.TicketID, arg.LabelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE labels
SET name = $1, color = $2, updated_at = now()
WHERE workspace_id = $3 AND id = $4
RETURNING id, workspace_id, name, name_key, color, created_at, updated_at
`

type UpdateLabelParams struct {
	Name        string
	Color       string
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, updateLabel,
		arg.Name,
		arg.Color,
		arg.WorkspaceID,
		arg.ID,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.NameKey,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
