// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_chapter_views.sql

package sqlcgen

import (
	"context"
)

const getLastViewedUserChapterViewByCourse = `-- name: GetLastViewedUserChapterViewByCourse :one
SELECT user_id, chapter_id, course_id, first_viewed_at, last_viewed_at, view_count
FROM user_chapter_views
WHERE user_id = $1 AND course_id = $2
ORDER BY last_viewed_at DESC, chapter_id DESC
LIMIT 1
`

type GetLastViewedUserChapterViewByCourseParams struct {
	UserID   int64
	CourseID int64
}

// (user, course) の閲覧記録から last_viewed_at 最大の 1 件を返す（コース詳細のレジューム用）。
// 同時刻の章が複数あっても返る 1 件がぶれないよう chapter_id をタイブレークに置く。
func (q *Queries) GetLastViewedUserChapterViewByCourse(ctx context.Context, arg GetLastViewedUserChapterViewByCourseParams) (UserChapterView, error) {
	row := q.db.QueryRowContext(ctx, getLastViewedUserChapterViewByCourse, arg.UserID, arg.CourseID)
	var i UserChapterView
	err := row.Scan(
		&i.UserID,
		&i.ChapterID,
		&i.CourseID,
		&i.FirstViewedAt,
		&i.LastViewedAt,
		&i.ViewCount,
	)
	return i, err
}

const listRecentUserChapterViewsByUser = `-- name: ListRecentUserChapterViewsByUser :many
SELECT user_id, chapter_id, course_id, first_viewed_at, last_viewed_at, view_count
FROM user_chapter_views
WHERE user_id = $1
ORDER BY last_viewed_at DESC, chapter_id DESC
LIMIT $2
`

type ListRecentUserChapterViewsByUserParams struct {
	UserID   int64
	RowLimit int32
}

// 最後に閲覧した章を新しい順で最大 limit 件返す（「続きから」カード用）。
// last_viewed_at は一意でないため、user 固定内で PK の一部 chapter_id をタイブレークに置く。
func (q *Queries) ListRecentUserChapterViewsByUser(ctx context.Context, arg ListRecentUserChapterViewsByUserParams) ([]UserChapterView, error) {
	rows, err := q.db.QueryContext(ctx, listRecentUserChapterViewsByUser, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserChapterView{}
	for rows.Next() {
		var i UserChapterView
		if err := rows.Scan(
			&i.UserID,
			&i.ChapterID,
			&i.CourseID,
			&i.FirstViewedAt,
			&i.LastViewedAt,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserChapterView = `-- name: UpsertUserChapterView :exec

INSERT INTO user_chapter_views
  (user_id, chapter_id, course_id, first_viewed_at, last_viewed_at, view_count)
VALUES
  ($1, $2, $3, now(), now(), 1)
ON CONFLICT (user_id, chapter_id) DO UPDATE SET
  course_id      = EXCLUDED.course_id,
  last_viewed_at = now(),
  view_count     = user_chapter_views.view_count + 1
`

type UpsertUserChapterViewParams struct {
	UserID    int64
	ChapterID int64
	CourseID  int64
}

// 章閲覧記録（user_chapter_views）のクエリ。PK = (user_id, chapter_id)。
// first_viewed_at / last_viewed_at に DB 既定値は無いので、時刻はクエリ側で now() を明示する。
// 章閲覧を記録する。初回は view_count=1 で first/last をセット、2 回目以降は
// last_viewed_at を now() に、view_count を +1、course_id を最新値へ更新する。
// first_viewed_at は DO UPDATE で触らないので初回の値が保持される。
func (q *Queries) UpsertUserChapterView(ctx context.Context, arg UpsertUserChapterViewParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserChapterView, arg.UserID, arg.ChapterID, arg.CourseID)
	return err
}
