// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteOidcIdentitiesByUserID = `-- name: DeleteOidcIdentitiesByUserID :exec
DELETE FROM user_oidc_identities WHERE user_id = $1
`

// ユーザーの OIDC identity をすべて消し、subject の占有を解く（同じアカウントの再招待を可能にする）。
func (q *Queries) DeleteOidcIdentitiesByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteOidcIdentitiesByUserID, userID)
	return err
}

const getCognitoSubjectByUserID = `-- name: GetCognitoSubjectByUserID :one
SELECT subject FROM user_oidc_identities
WHERE user_id = $1 AND provider = 'cognito'
`

// ユーザーの OIDC subject を引く。
// (user_id, provider) は uq_user_oidc_user_provider で一意（最大 1 行）。
func (q *Queries) GetCognitoSubjectByUserID(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getCognitoSubjectByUserID, userID)
	var subject string
	err := row.Scan(&subject)
	return subject, err
}

const getOidcIdentityOwner = `-- name: GetOidcIdentityOwner :one
SELECT user_id FROM user_oidc_identities
WHERE provider = $1 AND subject = $2
`

type GetOidcIdentityOwnerParams struct {
	Provider string
	Subject  string
}

// (provider, subject) を持っているユーザーの id。挿入されなかったときの持ち主判定に使う。
func (q *Queries) GetOidcIdentityOwner(ctx context.Context, arg GetOidcIdentityOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOidcIdentityOwner, arg.Provider, arg.Subject)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByCognitoSub = `-- name: GetUserByCognitoSub :one
SELECT u.id, u.email, u.name, u.workspace_id, u.is_active, u.created_at, u.updated_at, u.deleted_at
FROM users u
WHERE u.deleted_at IS NULL
  AND u.id IN (
    SELECT oi.user_id FROM user_oidc_identities oi
    WHERE oi.provider = 'cognito' AND oi.subject = $1
  )
`

type GetUserByCognitoSubRow struct {
	ID          int64
	Email       string
	Name        string
	WorkspaceID uuid.NullUUID
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

func (q *Queries) GetUserByCognitoSub(ctx context.Context, subject string) (GetUserByCognitoSubRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByCognitoSub, subject)
	var i GetUserByCognitoSubRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.WorkspaceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.email, u.name, u.workspace_id, u.is_active, u.created_at, u.updated_at, u.deleted_at
FROM users u
WHERE u.id = $1 AND u.deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID          int64
	Email       string
	Name        string
	WorkspaceID uuid.NullUUID
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

// 内部 ID で 1 ユーザーを引く（論理削除は除外）。
func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.WorkspaceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertOidcIdentityIfAbsent = `-- name: InsertOidcIdentityIfAbsent :execrows
INSERT INTO user_oidc_identities (user_id, provider, subject, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
ON CONFLICT (provider, subject) DO NOTHING
`

type InsertOidcIdentityIfAbsentParams struct {
	UserID   int64
	Provider string
	Subject  string
}

// OIDC identity を冪等に挿入する。既に同じ (provider, subject) があれば 0 行で、
// 呼び出し側が持ち主を確かめる。(user_id, provider) の一意制約違反はそのままエラーになる。
func (q *Queries) InsertOidcIdentityIfAbsent(ctx context.Context, arg InsertOidcIdentityIfAbsentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertOidcIdentityIfAbsent, arg.UserID, arg.Provider, arg.Subject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
  email, password_hash, name, workspace_id,
  is_active, created_at, updated_at, deleted_at
)
VALUES (
  $1, $2, $3, $4, true, $5, $6, $7
)
RETURNING id, created_at, updated_at
`

type InsertUserParams struct {
	Email        string
	PasswordHash sql.NullString
	Name         string
	WorkspaceID  uuid.NullUUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type InsertUserRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

// ユーザーを 1 件作る（id は採番シーケンスに任せる）。created_at / updated_at は DB 既定値が
// 無いため呼び出し側が値を渡す。is_active は常に true（作成直後のアカウントは有効。無効化は
// UpdateUserActive の仕事）。RETURNING で id / created_at / updated_at を書き戻す。
//
// workspace_id は呼び出し側が解決した値をそのまま書く（companies へのサブクエリ参照はしない）。
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.WorkspaceID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i InsertUserRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertUserWithID = `-- name: InsertUserWithID :one
INSERT INTO users (
  id, email, password_hash, name, workspace_id,
  is_active, created_at, updated_at, deleted_at
)
VALUES (
  $1, $2, $3, $4, $5, true, $6, $7, $8
)
RETURNING id, created_at, updated_at
`

type InsertUserWithIDParams struct {
	ID           int64
	Email        string
	PasswordHash sql.NullString
	Name         string
	WorkspaceID  uuid.NullUUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type InsertUserWithIDRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

// id を呼び出し側が決める場合の InsertUser。列と既定の扱いは InsertUser と同じにすること
// （片方だけ列を足すと、id を指定する経路だけ値が入らない）。
func (q *Queries) InsertUserWithID(ctx context.Context, arg InsertUserWithIDParams) (InsertUserWithIDRow, error) {
	row := q.db.QueryRowContext(ctx, insertUserWithID,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.WorkspaceID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i InsertUserWithIDRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listActiveUsersByEmail = `-- name: ListActiveUsersByEmail :many
SELECT u.id, u.email, u.name, u.workspace_id, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.password_hash
FROM users u
WHERE lower(btrim(u.email, E'\t\n\x0B\f\r ')) = lower(btrim($1::text, E'\t\n\x0B\f\r '))
  AND btrim(u.email, E'\t\n\x0B\f\r ') <> '' AND u.deleted_at IS NULL AND u.is_active
`

type ListActiveUsersByEmailRow struct {
	ID           int64
	Email        string
	Name         string
	WorkspaceID  uuid.NullUUID
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
	PasswordHash sql.NullString
}

// email で有効ユーザーを引く（論理削除・無効化は除外）。ローカルのパスワードログイン専用で、
// ハッシュを含む唯一のクエリ。email は uq_users_email_active（lower(btrim(email, ...)) /
// deleted_at IS NULL AND btrim(email, ...) <> ”）でアクティブ行に対して一意だが、既存データの
// 重複で index 未作成のまま起動している環境では複数行になり得るため :many で受け、
// 呼び出し側が曖昧さを拒否する。
// 突き合わせは domain.NormalizeEmail と同じ正規形 lower(btrim(email, E'\t\n\x0B\f\r ')) で行う
// （索引・述語と同じ式なのでそのまま部分索引が使われ、正規化される前に入った大文字混じり・
// 前後空白付きの既存行も同じアドレスとして 1 つに解決される）。引数側も同じ式で畳むので、
// ログインフォームの生入力をそのまま渡してよい（引数は ::text を明示する。btrim には bytea
// 版もあり、キャストが無いと sqlc が引数を []byte と推論してしまう）。
func (q *Queries) ListActiveUsersByEmail(ctx context.Context, email string) ([]ListActiveUsersByEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUsersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveUsersByEmailRow{}
	for rows.Next() {
		var i ListActiveUsersByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.WorkspaceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByWorkspaceID = `-- name: ListUsersByWorkspaceID :many
SELECT u.id, u.email, u.name, u.workspace_id, u.is_active, u.created_at, u.updated_at, u.deleted_at
FROM users u
WHERE u.workspace_id = $1 AND u.deleted_at IS NULL
ORDER BY u.id ASC
`

type ListUsersByWorkspaceIDRow struct {
	ID          int64
	Email       string
	Name        string
	WorkspaceID uuid.NullUUID
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

// ワークスペース単位のユーザー一覧（論理削除は除外）。
func (q *Queries) ListUsersByWorkspaceID(ctx context.Context, workspaceID uuid.NullUUID) ([]ListUsersByWorkspaceIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByWorkspaceID, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByWorkspaceIDRow{}
	for rows.Next() {
		var i ListUsersByWorkspaceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.WorkspaceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// ユーザーを論理削除する。既に削除済み / 存在しない場合は 0 件（呼び出し側が not-found にする）。
func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserActive = `-- name: UpdateUserActive :execrows
UPDATE users SET is_active = $2, updated_at = now() WHERE id = $1
`

type UpdateUserActiveParams struct {
	ID       int64
	IsActive bool
}

// アカウントの有効/無効を更新する。0 件なら対象が存在しない（呼び出し側が not-found にする）。
func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserActive, arg.ID, arg.IsActive)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserName = `-- name: UpdateUserName :execrows
UPDATE users SET name = $2, updated_at = now() WHERE id = $1
`

type UpdateUserNameParams struct {
	ID   int64
	Name string
}

// 氏名だけを更新する。0 件なら対象の user が存在しない（呼び出し側が not-found にする）。
func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserName, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserWorkspaceID = `-- name: UpdateUserWorkspaceID :execrows
UPDATE users SET
  workspace_id = $1
WHERE id = $2
`

type UpdateUserWorkspaceIDParams struct {
	WorkspaceID uuid.NullUUID
	ID          int64
}

// 所属ワークスペースを付け替える。呼び出し側が既に解決した workspace_id をそのまま書く。
// ワークスペースが無いユーザーもあり得るため nullable。
// 0 件なら対象の user が存在しない（呼び出し側が not-found にする）。
func (q *Queries) UpdateUserWorkspaceID(ctx context.Context, arg UpdateUserWorkspaceIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserWorkspaceID, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
