// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_stats.sql

package sqlcgen

import (
	"context"
)

const computeUserStats = `-- name: ComputeUserStats :one
SELECT
  COUNT(*)::bigint AS total_sessions,
  COALESCE(AVG(overall_score), 0)::double precision AS average_score
FROM score_cards
WHERE user_id = $1::bigint
`

type ComputeUserStatsRow struct {
	TotalSessions int64
	AverageScore  float64
}

// score_cards からユーザーの提出数(COUNT)と平均スコア(AVG)を 1 行に集計する。
// overall_score は nullable numeric で、AVG は NULL 行を無視する。1 件も一致しなくても
// COUNT/AVG の集計は必ず 1 行返るため :one でよい。
// domain.UserStats.AverageScore が float64 なので AVG は double precision へ寄せる
// （GORM 版も numeric を float64 へ Scan していた。scan 先の型を保つ）。
// AVG が NULL（一致行なし or 全て NULL スコア）のときは COALESCE で 0 に倒す。
func (q *Queries) ComputeUserStats(ctx context.Context, userID int64) (ComputeUserStatsRow, error) {
	row := q.db.QueryRowContext(ctx, computeUserStats, userID)
	var i ComputeUserStatsRow
	err := row.Scan(&i.TotalSessions, &i.AverageScore)
	return i, err
}
