spring.application.name=backend
server.port=${PORT:8081}
server.servlet.context-path=/api/v2
management.endpoints.web.base-path=/
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.validation-timeout=1000
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.data-source-properties.socketTimeout=30
