-- master_exercises: 運営が用意した練習問題のマスタ。MasterExercise に対応。
-- 既存(GORM)テーブルと衝突しないよう IF NOT EXISTS。型は H2/PostgreSQL 双方で通る書き方。
CREATE TABLE IF NOT EXISTS master_exercises (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(64)  NOT NULL,
    language        VARCHAR(32)  NOT NULL,
    order_index     INT          NOT NULL DEFAULT 0,
    category        VARCHAR(64)  NOT NULL,
    title           VARCHAR(200) NOT NULL,
    description     TEXT         NOT NULL,
    starter_code    TEXT         NOT NULL,
    hint_text       TEXT,
    expected_output TEXT,
    mode            VARCHAR(16)  NOT NULL DEFAULT 'execute',
    explanation     TEXT         NOT NULL DEFAULT '',
    difficulty      SMALLINT     NOT NULL DEFAULT 1,
    is_published    BOOLEAN      NOT NULL DEFAULT TRUE,
    chapter_id      BIGINT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_master_exercises_slug ON master_exercises (slug);
CREATE INDEX IF NOT EXISTS idx_master_exercises_language ON master_exercises (language);
