-- exercise_submissions: trainee の提出履歴(append-only)。ExerciseSubmission に対応。
CREATE TABLE IF NOT EXISTS exercise_submissions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL,
    exercise_kind  VARCHAR(16) NOT NULL,
    exercise_id    BIGINT      NOT NULL,
    submitted_code TEXT        NOT NULL,
    stdout         TEXT,
    stderr         TEXT,
    exit_code      INT         NOT NULL DEFAULT 0,
    is_correct     BOOLEAN     NOT NULL DEFAULT FALSE,
    submitted_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ユーザーの提出を新しい順に引くための索引。
CREATE INDEX IF NOT EXISTS idx_submissions_user_at
    ON exercise_submissions (user_id, submitted_at DESC);
