-- companies に「trainee への AI エージェント機能を有効にするか」のフラグを追加する。
--
-- companies テーブルは本番では GORM が作成済(Flyway 管理外)。一方 H2(テスト/新規)には存在しない。
-- 双方で動くよう、まず CREATE TABLE IF NOT EXISTS で存在を担保してから列を追加する(冪等)。
-- 本番では既存テーブルがあるため CREATE はスキップされ、ADD COLUMN IF NOT EXISTS だけが効く。
CREATE TABLE IF NOT EXISTS companies (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 既定 TRUE: 現状(全 trainee が AI 利用可)を維持し後方互換にする。company_admin が OFF にして制限する。
ALTER TABLE companies
    ADD COLUMN IF NOT EXISTS ai_chat_enabled_for_trainees BOOLEAN NOT NULL DEFAULT TRUE;
