-- users: アプリ利用者。User エンティティに対応。
-- cognito_sub は Cognito の一意 subject(認証時の橋渡しキー)で UNIQUE。
-- 型は H2(PostgreSQL モード) と PostgreSQL の双方で通る書き方。
CREATE TABLE IF NOT EXISTS users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cognito_sub  VARCHAR(255),
    email        VARCHAR(255),
    display_name VARCHAR(255),
    company_id   BIGINT,
    role         VARCHAR(32),
    onboarded_at TIMESTAMP,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    deleted_at   TIMESTAMP
);

-- cognito_sub は認証のたびに引く橋渡しキー。一意かつ高速参照のため UNIQUE 索引。
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_cognito_sub ON users (cognito_sub);
