-- company_applications: 未登録企業の利用申請。CompanyApplication エンティティに対応。
-- 型は H2(PostgreSQL モード) と PostgreSQL の双方で通る書き方。
CREATE TABLE IF NOT EXISTS company_applications (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name   VARCHAR(200) NOT NULL,
    applicant_name VARCHAR(120) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    message        VARCHAR,
    status         VARCHAR(16)  NOT NULL DEFAULT 'pending',
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP
);

-- super_admin の一覧は status で絞り込むことがあるため索引を張る。
CREATE INDEX IF NOT EXISTS idx_company_applications_status ON company_applications (status);
