-- ai_chat_sessions: AI チャットの 1 セッション(メタデータ)。AiChatSession に対応。
-- メッセージ本体は DynamoDB に保存し、ここではセッションのメタ情報のみ持つ。
-- 既存(GORM)テーブルと衝突しないよう IF NOT EXISTS にする。
CREATE TABLE IF NOT EXISTS ai_chat_sessions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- セッションは必ずユーザーに紐づくため NOT NULL。
    user_id      BIGINT       NOT NULL,
    title        VARCHAR(255) NOT NULL DEFAULT '',
    -- free(自由会話) / practice(シナリオ練習)。
    session_type VARCHAR(255) NOT NULL DEFAULT 'free',
    -- practice 用シナリオ ID(free のときは NULL)。
    scenario_id  BIGINT,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 一覧はユーザー単位で引くため user_id に索引を張る。
CREATE INDEX IF NOT EXISTS idx_ai_chat_sessions_user_id ON ai_chat_sessions (user_id);
