-- ============================================================================
-- schema-postgres.sql
-- ============================================================================
-- FreStyle 本番 DB スキーマ (PostgreSQL 16+ 用)
--
-- 用途: Phase 0b 切替時に新規 RDS PostgreSQL に対して 1 度実行する。
--       既存 MariaDB のスキーマと「論理的に等価」になるように構築し、
--       その後データ移行スクリプトで行データを取り込む。
--
-- 対 MariaDB の主な変更:
--   - INT AUTO_INCREMENT → BIGINT GENERATED BY DEFAULT AS IDENTITY
--   - DATETIME → TIMESTAMPTZ (タイムゾーン込み、UTC で保存)
--   - DEFAULT CHARSET=utf8mb4 ... → 削除（PG はデフォルト UTF-8）
--   - ENGINE=InnoDB → 削除
--   - JSON → JSONB （部分 index と高速操作）
--   - ON UPDATE CURRENT_TIMESTAMP → trigger で代替（後述）
--   - ENUM(...) → CHECK 制約
--   - INDEX idx_x ON table(...) → 個別 CREATE INDEX
--
-- マルチテナント基盤 (007_multitenancy_foundation.sql) 相当も含めて
-- 1 ファイルで完結。
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. updated_at 自動更新トリガー
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 2. 会社 (テナント)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS companies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(50)  NOT NULL UNIQUE,
    name            VARCHAR(200) NOT NULL,
    display_name    VARCHAR(200),
    plan            VARCHAR(20)  NOT NULL DEFAULT 'free',
    status          VARCHAR(20)  NOT NULL DEFAULT 'active',
    contract_start  DATE,
    contract_end    DATE,
    max_seats       INTEGER,
    metadata        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_companies_status ON companies(status) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_companies_updated_at BEFORE UPDATE ON companies FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS company_signup_applications (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name        VARCHAR(200) NOT NULL,
    contact_email       VARCHAR(254) NOT NULL,
    contact_name        VARCHAR(200) NOT NULL,
    expected_seats      INTEGER,
    use_case_summary    TEXT,
    status              VARCHAR(20)  NOT NULL DEFAULT 'pending',
    reviewed_by         BIGINT,
    reviewed_at         TIMESTAMPTZ,
    created_company_id  BIGINT REFERENCES companies(id),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_signup_applications_status ON company_signup_applications(status);

-- ----------------------------------------------------------------------------
-- 3. ユーザー
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT REFERENCES companies(id) ON DELETE RESTRICT,
    role        VARCHAR(30)  NOT NULL DEFAULT 'trainee',
    username    VARCHAR(255) NOT NULL,
    email       VARCHAR(254) UNIQUE NOT NULL,
    icon_url    VARCHAR(255),
    bio         TEXT,
    status      VARCHAR(100),
    is_active   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT chk_users_role CHECK (role IN ('super_admin','company_admin','trainee')),
    CONSTRAINT chk_users_role_company CHECK (
        (role = 'super_admin' AND company_id IS NULL)
        OR (role IN ('company_admin','trainee') AND company_id IS NOT NULL)
    )
);
CREATE INDEX IF NOT EXISTS idx_users_company_id ON users(company_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_users_role       ON users(role);
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE company_signup_applications
    ADD CONSTRAINT fk_signup_apps_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS user_identities (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider     VARCHAR(255) NOT NULL,
    provider_sub VARCHAR(255) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (provider, provider_sub)
);

CREATE TABLE IF NOT EXISTS invitations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT       NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    email            VARCHAR(254) NOT NULL,
    role             VARCHAR(30)  NOT NULL DEFAULT 'trainee',
    token            VARCHAR(64)  NOT NULL UNIQUE,
    invited_by       BIGINT REFERENCES users(id) ON DELETE SET NULL,
    expires_at       TIMESTAMPTZ NOT NULL,
    accepted_at      TIMESTAMPTZ,
    accepted_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_invitations_company_email ON invitations(company_id, email);

-- ----------------------------------------------------------------------------
-- 4. チャット (RDB 側はメタのみ、メッセージは DynamoDB)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_rooms (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chat_rooms_company ON chat_rooms(company_id);
CREATE TRIGGER trg_chat_rooms_updated_at BEFORE UPDATE ON chat_rooms FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS room_members (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id)      ON DELETE CASCADE,
    UNIQUE (room_id, user_id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id    BIGINT NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    sender_id  BIGINT NOT NULL REFERENCES users(id)      ON DELETE CASCADE,
    content    TEXT   NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_chat_messages_updated_at BEFORE UPDATE ON chat_messages FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS unread_counts (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id)      ON DELETE CASCADE,
    room_id BIGINT NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    count   INTEGER NOT NULL DEFAULT 0,
    UNIQUE (user_id, room_id)
);

CREATE TABLE IF NOT EXISTS access_tokens (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_token  TEXT   NOT NULL,
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    refresh_token TEXT   NOT NULL,
    revoked       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- 5. AI チャット
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_chat_sessions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
    title           VARCHAR(255),
    related_room_id BIGINT REFERENCES chat_rooms(id) ON DELETE SET NULL,
    scene           VARCHAR(50),
    session_type    VARCHAR(20) DEFAULT 'normal',
    scenario_id     BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ai_chat_sessions_company  ON ai_chat_sessions(company_id);
CREATE INDEX IF NOT EXISTS idx_ai_chat_sessions_user_created ON ai_chat_sessions(user_id, created_at DESC);
CREATE TRIGGER trg_ai_chat_sessions_updated_at BEFORE UPDATE ON ai_chat_sessions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS ai_chat_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES ai_chat_sessions(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users(id)            ON DELETE CASCADE,
    role       VARCHAR(20) NOT NULL,
    content    TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_ai_chat_role CHECK (role IN ('user','assistant'))
);
CREATE INDEX IF NOT EXISTS idx_ai_chat_messages_session ON ai_chat_messages(session_id, created_at);

CREATE TABLE IF NOT EXISTS communication_scores (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    session_id BIGINT NOT NULL REFERENCES ai_chat_sessions(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    axis_name  VARCHAR(50) NOT NULL,
    score      INTEGER     NOT NULL,
    comment    TEXT,
    scene      VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_communication_scores_user_created ON communication_scores(user_id, created_at DESC);

-- ----------------------------------------------------------------------------
-- 6. 練習シナリオ + ブックマーク + テンプレート
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS practice_scenarios (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    name          VARCHAR(100) NOT NULL,
    description   TEXT,
    category      VARCHAR(50),
    role_name     VARCHAR(100) NOT NULL,
    difficulty    VARCHAR(20) DEFAULT 'intermediate',
    system_prompt TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_practice_scenarios_company ON practice_scenarios(company_id);

CREATE TABLE IF NOT EXISTS scenario_bookmarks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scenario_id BIGINT NOT NULL REFERENCES practice_scenarios(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, scenario_id)
);

CREATE TABLE IF NOT EXISTS conversation_templates (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    title           VARCHAR(100) NOT NULL,
    description     TEXT,
    category        VARCHAR(50)  NOT NULL,
    opening_message TEXT NOT NULL,
    system_context  TEXT NOT NULL,
    difficulty      VARCHAR(20) DEFAULT 'intermediate',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_conversation_templates_company ON conversation_templates(company_id);

-- ----------------------------------------------------------------------------
-- 7. ノート / 報告 / 目標 / 通知 / リマインダー
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS learning_reports (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id                BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    year                   INTEGER NOT NULL,
    month                  INTEGER NOT NULL,
    total_sessions         INTEGER NOT NULL DEFAULT 0,
    average_score          DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    previous_average_score DOUBLE PRECISION,
    best_axis              VARCHAR(50),
    worst_axis             VARCHAR(50),
    practice_days          INTEGER NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, year, month)
);

CREATE TABLE IF NOT EXISTS daily_goals (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    goal_date  DATE NOT NULL,
    target     INTEGER NOT NULL,
    completed  INTEGER NOT NULL DEFAULT 0,
    UNIQUE (user_id, goal_date)
);

CREATE TABLE IF NOT EXISTS score_goals (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    goal_score DOUBLE PRECISION NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS favorite_phrases (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    original_text   TEXT NOT NULL,
    rephrased_text  TEXT NOT NULL,
    pattern         VARCHAR(50) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type       VARCHAR(50)  NOT NULL,
    title      VARCHAR(255) NOT NULL,
    message    TEXT NOT NULL,
    is_read    BOOLEAN NOT NULL DEFAULT FALSE,
    related_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS session_notes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id BIGINT NOT NULL REFERENCES ai_chat_sessions(id) ON DELETE CASCADE,
    note       TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, session_id)
);

CREATE TABLE IF NOT EXISTS reminder_settings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    reminder_time VARCHAR(5) NOT NULL DEFAULT '20:00',
    days_of_week  VARCHAR(50) NOT NULL DEFAULT 'mon,tue,wed,thu,fri',
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id)
);
CREATE TRIGGER trg_reminder_settings_updated_at BEFORE UPDATE ON reminder_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS shared_sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    session_id  BIGINT NOT NULL REFERENCES ai_chat_sessions(id) ON DELETE CASCADE,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    description TEXT,
    is_public   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (session_id)
);
CREATE INDEX IF NOT EXISTS idx_shared_sessions_public_created ON shared_sessions(is_public, created_at DESC);

CREATE TABLE IF NOT EXISTS friendships (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id   BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    follower_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    following_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (follower_id, following_id)
);

CREATE TABLE IF NOT EXISTS weekly_challenges (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    title           VARCHAR(100) NOT NULL,
    description     TEXT NOT NULL,
    category        VARCHAR(50)  NOT NULL,
    target_sessions INTEGER NOT NULL DEFAULT 3,
    week_start      DATE NOT NULL,
    week_end        DATE NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, week_start)
);

CREATE TABLE IF NOT EXISTS user_challenge_progress (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    user_id            BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    challenge_id       BIGINT NOT NULL REFERENCES weekly_challenges(id) ON DELETE CASCADE,
    completed_sessions INTEGER NOT NULL DEFAULT 0,
    is_completed       BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, challenge_id)
);
CREATE TRIGGER trg_user_challenge_progress_updated_at BEFORE UPDATE ON user_challenge_progress FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ----------------------------------------------------------------------------
-- 8. Phase 1 学習プラットフォーム (新規追加: cutover 後に有効化)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS courses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    title           VARCHAR(200) NOT NULL,
    slug            VARCHAR(120) NOT NULL,
    description     TEXT,
    difficulty      VARCHAR(20),
    estimated_hours INTEGER,
    status          VARCHAR(20) NOT NULL DEFAULT 'draft',
    created_by      BIGINT REFERENCES users(id),
    updated_by      BIGINT REFERENCES users(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    UNIQUE (company_id, slug),
    CONSTRAINT chk_courses_status CHECK (status IN ('draft','published','archived'))
);
CREATE INDEX IF NOT EXISTS idx_courses_company_status ON courses(company_id, status) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_courses_updated_at BEFORE UPDATE ON courses FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS sections (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id     BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title         VARCHAR(200) NOT NULL,
    description   TEXT,
    display_order INTEGER NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (course_id, display_order)
);
CREATE TRIGGER trg_sections_updated_at BEFORE UPDATE ON sections FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS lessons (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id          BIGINT NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    title               VARCHAR(200) NOT NULL,
    type                VARCHAR(30)  NOT NULL,
    content             JSONB        NOT NULL,
    display_order       INTEGER      NOT NULL,
    estimated_minutes   INTEGER,
    required_to_advance BOOLEAN      NOT NULL DEFAULT FALSE,
    passing_score       INTEGER,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (section_id, display_order),
    CONSTRAINT chk_lessons_type CHECK (type IN ('reading','quiz','coding','shadowing','communication'))
);
CREATE INDEX IF NOT EXISTS idx_lessons_section_type ON lessons(section_id, type);
CREATE INDEX IF NOT EXISTS idx_lessons_content_gin ON lessons USING GIN (content jsonb_path_ops);
CREATE TRIGGER trg_lessons_updated_at BEFORE UPDATE ON lessons FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS user_course_enrollments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
    course_id    BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    enrolled_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    UNIQUE (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS user_lesson_progress (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
    lesson_id         BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    status            VARCHAR(20) NOT NULL DEFAULT 'not_started',
    best_score        INTEGER,
    attempts          INTEGER NOT NULL DEFAULT 0,
    started_at        TIMESTAMPTZ,
    completed_at      TIMESTAMPTZ,
    last_attempt_data JSONB,
    UNIQUE (user_id, lesson_id),
    CONSTRAINT chk_user_lesson_progress_status CHECK (status IN ('not_started','in_progress','completed','failed'))
);
CREATE INDEX IF NOT EXISTS idx_user_lesson_progress_user_status ON user_lesson_progress(user_id, status);

CREATE TABLE IF NOT EXISTS user_quiz_attempts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
    lesson_id     BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    score         INTEGER NOT NULL,
    total_count   INTEGER NOT NULL,
    correct_count INTEGER NOT NULL,
    answers       JSONB   NOT NULL,
    duration_ms   INTEGER,
    submitted_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_user_quiz_attempts_lesson ON user_quiz_attempts(lesson_id, submitted_at DESC);
